### ISSUE TITLE
rule URLs trimmed

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3857] opened 2020-11-14 08:13 UTC
In rule URLs like `<url>http://www.iec.cat/llengua/documents/ortografia_catalana_versio_digital.pdf#page=128</url>` the last part (`#page=128`) is trimmed and not shown to the users.

**Comment by danielnaber** [comment] 2020-11-14 09:15
Which add-on are you referring to? It works for me with the browser add-on.

**Comment by jaumeortola** [comment] 2020-11-14 09:37
From today, it happens everywhere: web, command-line, browser add-on... For example, with the text "greco-romana" in Catalan. 
Could it be related to [this change](https://github.com/languagetool-org/languagetool/commit/503a3734f6421e26e1f4e43609b0a673d299235a#diff-c1f64959885c2f8650c3921a1798ab8debc7f5f97b64ef24f23277a6de4deef7L726)?

**Comment by danielnaber** [comment] 2020-11-14 09:55
Yes, that is indeed the cause. @donnerpeter, could you have a look?

**Comment by donnerpeter** [comment] 2020-11-14 13:27
Yes, sorry! Removing the line with `url = new URL(internString(url.getProtocol()), internString(url.getHost()), url.getPort(), internString(url.getFile()));` should fix this (I can't submit a PR right now)

**Comment by danielnaber** [comment] 2020-11-14 13:31
Thanks, fixed now.

**Closed by danielnaber** 2020-11-14 13:31 UTC
