### ISSUE TITLE
[de] no (good) suggestions for misspellings of 'protokollieren'

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#829] opened 2017-11-08 20:21 UTC
The German spell checker does not make the expected suggestions for the following misspellings (and probably others):

- protokolieren
- protokullieren
- protokoliert
- protokollliert

Minor issue, but quite unexpected.

**Comment by InnovativeInventor** [comment] 2017-11-19 03:17
I don't know German, but it seems like it is a word.

https://en.wiktionary.org/wiki/protokollieren

**Comment by janschreiber** [comment] 2017-11-19 16:04
Thanks for the comment. Of course it is a word, but 'protokullieren' isn't. That's the whole point.

**Comment by plumaj** [comment] 2018-03-16 10:50
It does also not make the expected suggestion for "Duzende" (i.e. "Dutzende") when it is placed at the beginning of a sentence.

**Comment by danielnaber** [comment] 2018-05-17 12:27
Dupe of #993

**Closed by danielnaber** 2018-05-17 12:27 UTC
Labels: German
