### ISSUE TITLE
Returned RuleMatch contains null sentence 

### ISSUE THREAD

**Issue by MaciekKuna** [languagetool-org/languagetool#1707] opened 2019-07-11 15:36 UTC
Hello, 
when the result is returned, the sentence attribute is missing (null). Below example of German sentence.

LanguageTool - 4.5

Example sentence:
unberechtigten Personen (Endnutzern) bekannt zu machen bzw. diese in cc zu setzen

![image](https://user-images.githubusercontent.com/16246708/61064249-b9c30880-a401-11e9-9e2f-26b8b7abbd0f.png)

**Comment by danielnaber** [comment] 2019-07-11 15:39
Could you submit a small unit test to reproduce?

**Comment by MaciekKuna** [comment] 2019-07-11 15:45
Hi, no problem.

```
        JLanguageTool spellchecker = new JLanguageTool(new GermanyGerman());
                spellchecker.disableRule("WHITESPACE_RULE");
                spellchecker.disableRule("DOPPELTE_SATZZEICHEN");

        List<RuleMatch> result =spellchecker.check("unberechtigten Personen (Endnutzern) bekannt zu machen bzw. diese in cc zu setzen");

        assertNotNull(result.get(1).getSentence().getText());
```

**Comment by danielnaber** [comment] 2019-07-11 15:54
I cannot reproduce it with current master. It was maybe fixed after 4.5, probably the fix is also in 4.6.

**Comment by danielnaber** [comment] 2019-07-21 16:01
Closing, as it's probably fixed now.

**Closed by danielnaber** 2019-07-21 16:01 UTC
