### ISSUE TITLE
"Ignore Once" doesn't work in LO/OO

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#125] opened 2014-07-04 21:38 UTC
Call Tools -> LanguageTool -> Check Text with a text that contains errors detected by LT. Press "Ignore once" and the error will not be ignored, it will simply stay there. Tested with both LO 4.1 and OO 4.1. Happens only if AutospellCheck (i.e. the mode with the blue wavy underlines) is not activated.

Very old reports about this:
- https://issues.apache.org/ooo/show_bug.cgi?id=91668
- http://openoffice.2283327.n4.nabble.com/Proofreading-implementations-issues-td2792027.html

Original report in our forum: http://languagetool-user-forum.2306527.n4.nabble.com/quot-Ignore-once-quot-in-OpenOffice-4-1-0-LanguageTool-2-6-td4641679.html

**Comment by FredKruse** [comment] 2019-07-12 20:01
I'm not sure, if my changes are related to this bug. I can't reproduce it. After a trigger of ignore once the matches are hidden.
But they are shown again, after a change was made, which force a recheck of the paragraph. Now I solved this for a Ignore Once triggered by a context menu event. The matches are ignored for the whole session or till the paragraph is changed (this should be by definition).
For the spell check dialog, this doesn't work, because the function is used internal. So I see no possibility to solve the problem.
I think, the issue should be closed.

**Comment by FredKruse** [comment] 2020-04-22 11:37
@danielnaber The issue is solved as far it can be solved by LT. The marks disappear if the IgnoreOnce Button is called by mouse or dialog. It re-appears if the paragraph is changed as expected. Please close the issue.

**Closed** 2020-04-22 11:41 UTC
Labels: bug, office-integration
