### ISSUE TITLE
Can't use fromy to trace the error back to some sentences

### ISSUE THREAD

**Issue by motasay** [languagetool-org/languagetool#323] opened 2015-10-01 08:52 UTC
Hi,

I have a file, where each line contains exactly one sentence (according to NLTK's sent_tokenize). I pass this file to the command line interface of languagetool. However, some issues have a value in `fromy` that's greater than the number of lines in the file. Why would this happen?

The DTD has this about `fromy`:
> The line in which the error starts. Counting starts at 0.

To replicate:

1. Download this file: https://www.dropbox.com/s/45rq5v5qh4myb7n/lt_test.txt.zip?dl=1
2. In the terminal, call: `java -jar languagetool-commandline.jar --api --language en-GB lt_test.txt`
3. The last error has: `fromy="1520"`
4. But the result of `wc -l lt_test.txt` is `1450 lt_test.txt` which basically is the number of lines in the file.

I'd suspect that the tool does its own tokenisation, but I'd leave it to the experts instead of guessing.

Any help would be very much appreciated.

**Comment by danielnaber** [comment] 2015-10-01 17:40
Something is strange with the line endings in the input. For example, the line with `cheerful and undefeated.` has 4 bytes for the line ending.

**Comment by motasay** [comment] 2015-10-01 19:41
@danielnaber Thanks. May I ask how did you find this? Or how can I see these 4 bytes? I'm using python to read/write the file (as utf-8) using the codecs library and it doesn't show me anything strange. Is this specific to Java or the way LanguageTool reads files?

Cheers.

**Comment by danielnaber** [comment] 2015-10-01 19:53
I opened the file with a hex editor (e.g. `ghex` on Ubuntu). I haven't debugged *why* LT gets confused by these line endings (if that's the reason, but I guess so), but I guess they should not be there.

**Comment by motasay** [comment] 2015-10-01 19:55
Alright I see. I appreciate your help! I'll give it another go tomorrow.

**Comment by danielnaber** [comment] 2015-10-09 09:12
Closing, I assume this was caused by broken/strange input.

**Closed by danielnaber** 2015-10-09 09:12 UTC
