### ISSUE TITLE
Not working in Facebook on Firefox

### ISSUE THREAD

**Issue by MontyFlange** [languagetool-org/languagetool#3795] opened 2020-11-05 00:08 UTC
The check as you type isn't working now

**Comment by danielnaber** [comment] 2020-11-05 07:35
Could you send a screenshot and the URL where this is the case?

**Comment by MontyFlange** [comment] 2020-11-05 11:52
Not really, How do I take a screen shot of something not working ?

All of Facebook. I think it's probably down to the new style

**Comment by tiff** [comment] 2020-11-05 13:03
It works for me in Firefox, I tested status update and comments. Anyone else who is having this problem?

**Comment by udomai** [comment] 2020-11-09 08:20
No problems on Firefox here, either (I use the new interface)

**Comment by tiff** [comment] 2021-02-25 07:59
I'm closing this as we have found no way to reproduce this and we have no other users complaining about this

**Closed by tiff** 2021-02-25 07:59 UTC
Labels: browser-add-on
