### ISSUE TITLE
LanguageTool Painfully Slow in Medium / Large Sized Google Docs

### ISSUE THREAD

**Issue by SethFalco** [languagetool-org/languagetool#3265] opened 2020-07-15 11:52 UTC
I'm a user of LanguageToolPlus and recently ran into issues with document editing being painfully slow in Google Docs when LanguageTool is enabled.

This appears to be due to the size of the document, which isn't large, but certainly much larger than most documents I write or maintain, unfortunately, I've had to disable it as a result for Google Docs.

![image](https://user-images.githubusercontent.com/22801583/87541547-b3fda400-c6a1-11ea-9ed8-ceb93ec8a648.png)

I can see that LanguageTool shows it's "processing icon" (I think) as soon as I start typing anything, could an option by introduced so that it only actually processes when the user **stops** typing, rather than while the user is typing, which would circumvent the issue? 

For example, even in this issue I've probably only paused 2 or 3 times, it could be nice for it to wait until a character hasn't been typed for 1-2 seconds first, then scan.

**Comment by danielnaber** [comment] 2020-07-15 12:56
Can you provide the document (or a similar document) for testing? Only the current page should be checked, so the size of the whole document shouldn't make a difference.

**Comment by tiff** [comment] 2020-07-15 14:45
@SethiPandi also, do you have other (maybe similar) extensions installed?

**Comment by tiff** [comment] 2020-07-15 14:48
BTW: The "progress icon" doesn't necessarily mean that the text is continuously being checked. It should just indicate that the changes to the text haven't been checked yet.

**Comment by SethiPandi** [comment] 2020-07-18 11:51
> Can you provide the document (or a similar document) for testing? Only the current page should be checked, so the size of the whole document shouldn't make a difference.

Unfortunately, I've been busy and unable to respond to this issue yet. Tomorrow I'll get around to obfuscating and sharing the document here since I don't want to share the original contents, but I was unable to recreate the exact problem in a fresh document without starting from a clone of the original. Sorry for such a long delay!

Meanwhile, just responding so the issue doesn't become stale, and giving more information which may or may not be handy.

Just want to say first, I've just tested the performance in 4 documents, unfortunately I couldn't find a good package to visually represent my key presses so it might not be as reliable but I've just taken some GIFs. I typed in all 4 of them at roughly the same speed.

**The document referred to by this issue:**
![1](https://user-images.githubusercontent.com/22801583/87655377-760f8700-c758-11ea-93f3-0b0dadbfad59.gif)  
This is the primary problem, I can vouch disabling LanguageTool solves the performance issues as well. I've also verified your per page statement as the performance issues occur on some pages, but not on others.

**A new document, with 60+ pages of lorem ipsum:**
![2](https://user-images.githubusercontent.com/22801583/87655487-9b9c9080-c758-11ea-8504-e9473ab3b74a.gif)  
And once again, as you said clearly size doesn't matter, as this is multiple times larger than prior document but still works relatively fine.

**A new document, but empty:**
![Peek 2020-07-16 11-37](https://user-images.githubusercontent.com/22801583/87655592-c25ac700-c758-11ea-8440-a167759b463a.gif)

**A new document, with LanguageTool disabled:**
![4](https://user-images.githubusercontent.com/22801583/87655714-e28a8600-c758-11ea-9792-c8911290d520.gif)

> @SethiPandi also, do you have other (maybe similar) extensions installed?

And if you mean Google Doc extensions, then no, LanguageTool is the only one I have.
If you mean browser (Firefox) extensions, then yes I have several, but none which should affect documents/text fields.

Firefox extensions:
* Bitwarden
* Web of Trust (WoT)
* uBlock Origin
* Honey
* Vue Devtools
* React Developer Tools
* Firefox Private Relay
* LanguageTool

> BTW: The "progress icon" doesn't necessarily mean that the text is continuously being checked. It should just indicate that the changes to the text haven't been checked yet.

And understood, sorry, I assumed the icon meant it was actually doing some kind of processing, this was my bad.

**Comment by tiff** [comment] 2020-07-20 07:00
@SethiPandi thank you so much for the detailed information. It would be really helpful to see the document. You can even share it in private with me (christopher.blum [ at ] languagetooler.com)

Does the problem maybe only happen on pages that have a lot of spelling errors?

**Comment by SethiPandi** [comment] 2020-07-21 11:01
Sorry I took so long! Ended up decided to over-engineer a solution to obfuscate documents for me in case I ever want to report a bug again and took longer than I expected. ^-^' 

_A small heads up, `over engineer` has a warning with `This is normally spelled as one word.`, but after applying the correction we get `overengineer` with the error `Possible spelling mistake found.`, and wants me to change it back._

The issue varies from page to page, but I believe page 12 is the biggest offender in the following document.
[temp.zip](https://github.com/languagetool-org/languagetool/files/4953077/temp.zip)

![image](https://user-images.githubusercontent.com/22801583/88047663-44306300-cb52-11ea-949f-aec54ce12bb6.png)

I've also invited your email address to have editor permissions on the document if that's preferred over downloading and re-uploading the file.

> Does the problem maybe only happen on pages that have a lot of spelling errors?

No, the original document did have a few warnings here and there, but no spelling errors, they were either valid words, or words that were in my custom dictionary.

**Comment by tiff** [comment] 2020-07-21 11:40
@SethiPandi no worries, we will have a look over the next days. Thank you so much.
We will also fix the issue with "over engineer". That word is simply missing from our dictionary.

**Comment by SethiPandi** [comment] 2020-09-24 09:26
We're moving away from G Suite, so we'll no longer be using Google Drive or Google Docs. As a result the document you were invited to will no longer exist very soon.

The document that reproduces the issue was exported as a file and attached to an earlier comment though, it can be imported to Google Drive to test on. Sorry for the inconvenience!

As a side note, I have **not** been debugging LanguageTool not benchmarking its performance, but since opening this issue, my experience suggests that the performance issues have something to do with tables on Google Docs. The performance issues are most visible when I have a table on the page, and it's even worse when the page consists of rows from a table that started from the page before.

**Comment by tiff** [comment] 2021-03-04 12:26
@SethFalco we have fixed many performance problems caused by tables in one of the recent releases. I'm closing this. Let us know if this still happens.

**Closed by tiff** 2021-03-04 12:26 UTC
