### ISSUE TITLE
LibreOffice - Server URL must not end with a '/'

### ISSUE THREAD

**Issue by KnowZero** [languagetool-org/languagetool#3007] opened 2020-06-02 10:14 UTC
![lo_error1](https://user-images.githubusercontent.com/1638787/83508435-ef4c6680-a497-11ea-93c4-0ffbd6e22721.png)

I am locked out of the options due to setting a remote server url ending in '/' on LibreOffice 6.0 linux mint. I can't change it since it keeps trying to ping the server before opening the options and give an error.

Also, side request, is it possible to put errors in a textarea that we can copy and paste so we don't need to take a screenshot?

**Comment by danielnaber** [comment] 2020-06-02 11:05
@FredKruse I guess we could check that field so that invalid values never get stored?

**Comment by FredKruse** [comment] 2020-06-03 11:13
The issue is solved. While typing the server URL it is colored red until the URL has the right form (e.g.no "/" at the end). A malformed URL will not be saved to or read from the configuration file. 
 Please test it tomorrow and close the issue.

**Comment by FredKruse** [comment] 2020-09-26 15:24
The problem is solved, I close the issue.

**Closed by FredKruse** 2020-09-26 15:24 UTC
Labels: office-integration
