### ISSUE TITLE
Field command fixed date in heading line is underlined in blue without any suggestions

### ISSUE THREAD

**Issue by GiantCrocodile** [languagetool-org/languagetool#824] opened 2017-11-05 01:32 UTC
See title, happens in German but I think it is a general issue, not related to German texts.

**Comment by GiantCrocodile** [comment] 2017-11-05 12:53
I just noticed that this happens with any field command date, regardless its position or place it is used.

**Comment by GiantCrocodile** [comment] 2017-11-05 12:57
I noticed something else: I also get issues marked in my table of content with 3 entries without any suggestion visible. I don't know what it does detect but I think it is a false positive.

**Comment by FredKruse** [comment] 2018-03-14 09:44
This issue is related to issue to issue #575. There are two problems:

1. the LO/OO - Interface represent Functions and footnotes as ZERO_WIDTH_SPACE (0x200b). The MultipleWhitespaceRule doesn't handle this characters correct. It is treated as a white character and so the rule want to delete it, when it occurs in combination with a blanc.
2. The footnotes are excluded by the annotation mechanism of LT for rules at the sentence level. I don't know, if this is necessary for other rules. For all rules dealing with white spaces this is problem, because the rule can not identify a footnote between two tokens. The easiest way would be to leave the ZERO_WIDTH_SPACE as it is and handle it separately in every rule.

I would like to redesign the MultipleWhitespaceRule. But to handle also footnotes correct either the markup of footnotes has to removed in the LO/OO extension or the rule has to be changed to a textlevel rule.
@danielnaber: Do you remember the reason why footnotes are marked up and don't leave as ZERO_WIDTH_SPACE?

**Comment by FredKruse** [comment] 2018-03-15 20:24
Now the field commands are handled in all rules as far as I see.
The issue can be closed.

**Comment by FredKruse** [comment] 2020-04-23 12:39
@danielnaber: The issue is solved. Please close the issue

**Closed** 2020-04-23 12:40 UTC
Labels: office-integration
