### ISSUE TITLE
CLI: class not found: GermanRuleDisambiguator

### ISSUE THREAD

**Issue by pschwede** [languagetool-org/languagetool#1490] opened 2019-03-28 17:21 UTC
CLI-IO was:
```
$ java -jar languagetool-commandline.jar -l de-AT <<< "Reichthum ist kein Satz."
Expected text language: German (Austria)
Working on STDIN...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
        at org.languagetool.MultiThreadedJLanguageTool.analyzeSentences(MultiThreadedJLanguageTool.java:153)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:724)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:702)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:693)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:652)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:636)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:106)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:82)
        at org.languagetool.commandline.Main.runOnFile(Main.java:194)
        at org.languagetool.commandline.Main.main(Main.java:466)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at org.languagetool.MultiThreadedJLanguageTool.analyzeSentences(MultiThreadedJLanguageTool.java:146)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        ... 10 more
Caused by: java.lang.NoClassDefFoundError: org/languagetool/tagging/disambiguation/rules/de/GermanRuleDisambiguator
        at org.languagetool.language.German.getDisambiguator(German.java:88)
        at org.languagetool.JLanguageTool.getAnalyzedSentence(JLanguageTool.java:951)
        at org.languagetool.MultiThreadedJLanguageTool$AnalyzeSentenceCallable.call(MultiThreadedJLanguageTool.java:208)
        at org.languagetool.MultiThreadedJLanguageTool$ParagraphEndAnalyzeSentenceCallable.call(MultiThreadedJLanguageTool.java:219)
        at org.languagetool.MultiThreadedJLanguageTool$ParagraphEndAnalyzeSentenceCallable.call(MultiThreadedJLanguageTool.java:212)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.languagetool.tagging.disambiguation.rules.de.GermanRuleDisambiguator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more
```

**Comment by danielnaber** [comment] 2019-03-28 17:25
I cannot reproduce, which version of LT is this? The class is at `./org/languagetool/tagging/disambiguation/rules/de/GermanRuleDisambiguator.class`  (i.e. not in a JAR)

**Comment by pschwede** [comment] 2019-03-28 17:26
It's https://languagetool.org/download/LanguageTool-4.5.zip

**Comment by danielnaber** [comment] 2019-04-10 10:06
Still cannot reproduce - which version of Java do you use?

**Comment by danielnaber** [comment] 2021-03-12 19:44
Closing, no reply

**Closed by danielnaber** 2021-03-12 19:44 UTC
