### ISSUE TITLE
error when starting LT on libreoffice

### ISSUE THREAD

**Issue by icf20** [languagetool-org/languagetool#4089] opened 2021-01-04 10:51 UTC
![image](https://user-images.githubusercontent.com/17784575/103527712-0d8da100-4e83-11eb-9876-57bf072d3d1b.png)

sadly i cant copy paste the error from the image

**Comment by danielnaber** [comment] 2021-01-04 11:12
Does this also happen with LT 5.2? https://languagetool.org/download/LanguageTool-5.2.oxt

**Comment by FredKruse** [comment] 2021-03-26 07:28
@icf20 This should be solved with 5.3. Please test and close the issue.

**Comment by FredKruse** [comment] 2021-11-18 19:18
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:18 UTC
Labels: office-integration
