### ISSUE TITLE
[en] 'testrules' disambiguation test is not working with snapshot 2020-11-06

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3810] opened 2020-11-07 12:30 UTC
Testrules does not work correctly. It tests the grammar rules, then hangs (hence, 'terminate batch job'). I tried 3 times, and on the final time, waited more than 1 minute to make sure it was not just slow.

```
Running XML pattern tests...
LanguageTool version 5.2-SNAPSHOT (2020-11-06 19:44, 740b35e)
Known languages: [Arabic, English, English (US), English (GB), English (Australian), English (Canadian), English (New Zealand),
 <snip>
Testing rule 4200...
Skipped 0 rules for variant language to avoid checking rules more than once
4204 rules tested.
Tests finished!
Terminate batch job (Y/N)? y
```

**Comment by danielnaber** [comment] 2020-11-07 14:24
This was caused by https://github.com/languagetool-org/languagetool/pull/3743, it should be fixed now.

**Closed by danielnaber** 2020-11-07 14:24 UTC
Labels: bug, code/java

**Comment by MikeUnwalla** [comment] 2020-11-08 09:35
@danielnaber , thank you.
