### ISSUE TITLE
In German it is "jedes Mal" not "jedes mal"

### ISSUE THREAD

**Issue by Cherubin7th** [languagetool-org/languagetool#738] opened 2017-07-14 09:06 UTC
LT things that in German "jedes mal" is OK, but it is wrong it must be "jedes Mal" with capital M.

**Comment by danielnaber** [comment] 2017-07-14 09:18
Can you provide a complete sentence? I cannot reproduce this issue - "mal" is marked as an error for me, and "Mal" is correctly suggested.

**Comment by Cherubin7th** [comment] 2017-07-14 09:46
Sorry, it was my mistake.

**Closed** 2017-07-14 09:46 UTC
