### ISSUE TITLE
Idea: always use server for LibreOffice add-on?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1929] opened 2019-09-10 14:12 UTC
Now that access to an HTTP server has been added (#971, thanks to @FredKruse), I wonder: would it maybe simplify our code if the server would be used all the time? The user wouldn't have to notice, it could be started in the background. What do you think, @FredKruse?

**Comment by TiagoSantos81** [comment] 2019-09-10 14:40
Apart from opening ports when they are not needed nor wanted?

**Comment by danielnaber** [comment] 2019-09-10 14:46
The server is attaching itself to 127.0.0.1 only by default, so it cannot be accessed from elsewhere.

**Comment by TiagoSantos81** [comment] 2019-09-10 14:54
By principle, Internet code should not run in intended offline instances. Everything works as intended until it doesn't. It is a very slippery slope.
As is, having the option to use with the server appeases the specific requests that have appeared, like the self hosted language-server, without damaging too much the remaining group. 
Typical LibreOffice users do not usually want the server side, since that will only work for corporate users, that already have IT personnel to handle the server configuration. I see no other use case scenario.

**Comment by danielnaber** [comment] 2019-09-10 15:14
> I see no other use case scenario.

That's why I asked @FredKruse:  "would it maybe simplify our code if the server would be used all the time?". This is not about a new use case. It's about whether our LibreOffice code, which is really complex, would benefit from using a server in terms of complexity.

**Comment by TiagoSantos81** [comment] 2019-09-10 15:39
Good code is complex, because it is a cumulative construction, as you know. 
Simplification can not be above reliability and security, especially when this creates issues where they do not exist. 
Most distro do not integrate LanguagTool because of the Java prerequisites, but recently a few have started to integrate standalone and LibreOffice extension, since they are decently isolated offline modules. This change will create further (and I would add reasonable) doubts about its inclusion.

**Comment by TiagoSantos81** [comment] 2019-09-10 15:42
Hearbleed comes to my mind on this. It was just a simplification:
https://www.csoonline.com/article/3223203/what-is-the-heartbleed-bug-how-does-it-work-and-how-was-it-fixed.html

**Comment by danielnaber** [comment] 2019-09-10 15:47
Thanks @TiagoSantos81, let's wait for Fred to answer my original question.

**Comment by FredKruse** [comment] 2019-09-10 20:14
I think, it wouldn't be a simplification of code. The office extension use the same engine as the server. So there is no duplication of code. If we implement a server, a office user has to install more applications and it will be more complicate. Another point is, that the implementation of the current code needs the whole engine in the background. It controls the requests to the server.
The idea was to add a remote access, to give user a chance to reduce local CPU load and to use ngram and word2vec on a remote server without installing the big amount of data local.
Also, the remote access is still experimental, it is not finished today.

**Comment by baarsrj** [comment] 2019-09-27 08:58
I know of some organizations that (almost) completely isolate themselves from all public networks.

**Comment by KnowZero** [comment] 2019-10-03 15:02
> The idea was to add a remote access, to give user a chance to reduce local CPU load and to use ngram and word2vec on a remote server without installing the big amount of data local.
> Also, the remote access is still experimental, it is not finished today.

The thing is, Word2Vec doesn't even work on LibreOffice
#1689

Speaking of offloading data, it would be nice to have an optional setting to cache large documents. Every time I open my documents with 100,000+ words libreoffice goes into crazy cpu usage for at least an hour. (I am using ngrams). If there was an optional setting to cache large documents, would save a lot of load when I reopen the files.

Anyways, back on topic. Applications binding on 127.0.0.1 are pretty common these days even from the big vendors. But having 2 versions and see what people prefer might be the way to go.

**Comment by FredKruse** [comment] 2019-10-28 19:31
I like the idea of create to versions of LO extension with and without network support. 

As I described above the installation and handling of the internal checker is much easier without introducing a local server. On the other hand a network support can give benefits to the user. An idea for future development of the network version could be to add the possibility of premium support (running on the remote server) (@danielnaber what do you think about this idea).

There is to do some work to split the internal check from the remote check. I am working on this. Today I took a big step in this direction. But the existing installation is still a work around. Some components of the remote check needs still the internal checker.

**Comment by danielnaber** [comment] 2019-10-28 20:14
> create two versions of LO extension

I see two issues: 1. does it really help to have two extensions, compared to one version with a configuration option (from the user's point of view)?  2. How can we communicate to the user they are using the non-local version? depending on what server they use, this has privacy implications (localhost vs languagetool.org vs. some company-internal server)

**Comment by FredKruse** [comment] 2019-11-05 13:59
1. I'm not really sure. The remote installation could be smaller, because the rules etc. haven't to be stored. Also, a hint of the risks of using the remote version could be set on the download side. On the other hand a switch to a local/internal check when connection fails (like it is installed now) isn't possible anymore. I think, we should leave it, as it is.
2. A pop-up window could be installed, that informs the user of the risks of a remote check analog to the installation e.g. in firefox. It should popup when the remote option is chosen.  Is there a text which I could use (in different languages at best)?

**Comment by danielnaber** [comment] 2019-11-05 14:49
This is what the browser add-on shows: "This extension will check your text by sending it to LanguageTool.org over an encrypted connection. Your text will not be stored.". We have that for severla (though probably not all languages). Anyway, could we also maybe show an item in the context menu, reminding users they are in "remote server mode"? People tend to agree to this kind of stuff and then later forget about it.

**Comment by FredKruse** [comment] 2020-04-23 09:49
The pop up window is installed.
@danielnaber : The extension as it is, gives the user the most freedom of choice. I think, we should close this issue.

**Closed** 2020-04-23 10:02 UTC
Labels: enhancement, office-integration

**Comment by phirestalker** [comment] 2021-12-08 18:48
I know I'm late to the party, but does this mean there is no way to enter a server address into the LibreOffice plugin? I am running a LanguageTool server on my local network that has all the big files. I have all the browser extensions pointed to it.

If there is a way, can someone point me in the right direction?

**Comment by KnowZero** [comment] 2021-12-09 09:16
@phirestalker This is an old thread, you can use a server just fine in LibreOffice. Just open a document and go to Tools->LanguageTool->Options...->General->Technical Settings and select Use remote server to check text, then select Use Server and put the local network server url in there.
