### ISSUE TITLE
[en] wrong tagging for 's

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4542] opened 2021-03-04 08:37 UTC
These sentences cause false alarms in APOSTROPHE_PLURAL ([see last two examples](https://github.com/languagetool-org/languagetool/commit/09e846dac9f5d812e1f251c96077ace97d60c593)) for

>My hair's messed up this morning.
>Your mother's brought each of you something.

If we make the 3rd token in APOSTROPHE_PLURAL[1] `<token>'s<exception inflected="yes" regexp="yes">have|be</exception></token>`, it won't work for now, because the disambiguator rule POS_ADD[7] stops `'s` from being tagged as VBZ.

→ make POS_ADD[7] see `'s` as a VBZ in those cases
→ add "be" to exception in \3
→ activate the last two examples to see if it works

**Comment by MikeUnwalla** [comment] 2021-03-04 12:08
@udomai , I found and fixed some other incorrect taggings.

APOSTROPHE_PLURAL[1] has this 'incorrect' example:
`<example correction="teachers">7 reasons why <marker>teacher's</marker> found us top class</example>`

This sentence is ambiguous:
7 reasons why teacher has found us [to be] top class
where _teacher_ is a zero-article job role.

I have not tried to fix the POS for this ambiguous sentence.

If the regression is OK, I will close tomorrow.

**Comment by MikeUnwalla** [comment] 2021-03-05 09:10
APOSTROPHE_PLURAL[1] errors not found now (2021-03-05):

- [ ] I am probably dreaming, but didn't know if **CEO's** had people like that working directly for them. [Wrong tagging of` 's`]
- [ ] The basis for this is a calculation of **FTE's** based on 2002 Planned allocations from ENA support departments to your business unit. [Wrong tagging of` 's`]
- [ ] ...omments to the NDA's or review forms of **NDA's** provided by counterparties. [Wrong tagging of` 's`]
- [ ] Last month, however, the ISO's **attorney's** alerted the WSCC that the...  [No tagging of` 's` as POS only]
- [ ] Steve will fax me a copy of the notice they received if Oneok's **attorney's** approve.

APOSTROPHE_PLURAL[1] modified that are FP or possible FP:
- [ ] Even worse, my family stop for bite to eat there Friday night when **Chili's** was packed. [In this context Chili's is possibly a proper noun.]
- [ ] Franklin also noted that the new strategy concentrates on **Southern Company's** regulated retail business, which represents 90 percent of the company's business
- [ ] We are covering Europe for ourselves and don't really see why we should pick up a share of **Corp's** spend on Kyoto etc. 2.
- [ ] A friend of my **Dad's** gave him dice to hang on the rear view mirror of his new 2001 Cadillac.
- [ ] **Dan's** was fabulous. [Possibly an FP, possibly not.]
- [ ] Meant only for Weather Deals Equity Derivatives only Language/Only for IR, FX, Currency Options & **FRA's** Please let me know how you want to be updated on future restricted Agreements [wrong suggestion: Fras]
- [ ] **Data Fortress's** managed services products have been well accepted into the marketplace. 
- [ ] **Id's** emailed which will give us access to EnronOnline temporarily... [wrong suggestion: Ids]
- [ ] Two TV's, two VCR's, two guns, 3 coin banks and some ammo was taken, **LOT'S** was overlooked [wrong suggestion, use LOTS]
- [ ] Slower sales growth reflects softer overall demand for **MOT's** equip., particularly w/in wireless infra. 
- [ ] Barcelona A grade II listed building, **Crabwell Manor's** pamper package includes use of the Spa with indoor pool, ...
- [ ] Our dinner at **Sambuca's** took quite awhile, I think we made it to you guys had a good time, and I'm always up for another night out.
- [ ] The insurance companies involved, so far, are Fireman's Fund and **Traveler's** contemplate needing to have those two insurance companies "agent" a deal that will involve more names. [possible FP]
- [ ] The **Soviet Union's** was scrapped in 1953, in 1957 and (back under her original name, , since 1942) in 1956-7.
- [ ] An established partnership might have agreed that as hearts were not supported after **opener's** rebid, 4 cannot possibly show support, and must be ace asking in diamonds. [wrong suggestion. Use "the opener's"]

@udomai , from the perspective of the tagging for the false alarms, the issue if corrected. But, as the sentences here show, there are more problems with APOSTROPHE_PLURAL.

What is your preference?
* Close this issue and make a new issue for the problems noted in this comment.
* Keep this issue open and continue to fix the problems.

**Closed** 2021-04-28 10:41 UTC
Labels: English
