### ISSUE TITLE
Incorrectly suggesting capitalization of "guten Rutsch"

### ISSUE THREAD

**Issue by phillipoertel** [languagetool-org/languagetool#2269] opened 2019-12-30 15:39 UTC
See screenshot. LT is suggesting capitalization of all three words, which is wrong in all three cases IMHO.

<img width="218" alt="Bildschirmfoto 2019-12-30 um 16 35 26" src="https://user-images.githubusercontent.com/5188/71588672-a6783680-2b22-11ea-97ac-ed6b99c5276f.png">

**Comment by danielnaber** [comment] 2019-12-30 15:56
Thanks for the report. I cannot reproduce that - are you sure the correct language was detected? If so, how did you use LT (add-on, website, ...)?

**Comment by tiff** [comment] 2019-12-30 18:47
Das sieht für mich nach Grammarly aus

**Comment by tiff** [comment] 2020-01-02 07:52
@phillipoertel I'm closing this. I wasn't able to reproduce this with LanguageTool but with Grammarly (which doesn't support German).

**Closed by tiff** 2020-01-02 07:52 UTC
