### ISSUE TITLE
Fails to work on https://dev.to

### ISSUE THREAD

**Issue by bernd-wechner** [languagetool-org/languagetool#6314] opened 2022-02-10 02:04 UTC
Love Language Tool. Noticed that when posting and commenting on https:/dev.to though, that it is absent. Clearly, something at that site is interfering with LT's ability to notice a text entry box.  Could be a symptom of a wider problem.

**Comment by tiff** [comment] 2022-02-10 09:33
They have set a `spellcheck=false` on the text field which disallows any spell checker to run there. We could ignore it. I'm not sure though if this would break anything

**Comment by bernd-wechner** [comment] 2022-02-10 10:20
Thanks kindly for pointing that out. I was about to file an issue with forem (the framework behind dev.to) and it's already there:

https://github.com/forem/forem/issues/13859

So I added what I've learned here and shared some test results tweaking it in the Browser's Inspector. 

All that said, I think as a side issue, that it would be a rather large boon if and feather in Language Tools Cap if it had an option to override this. Two implementations strike me as feasible and appealing:

1. On the Language Tools menu under Settings for this website add  "Ignore spellcheck=false" as an option, off by default.
![image](https://user-images.githubusercontent.com/7296506/153386124-22061f2c-e5f0-43ab-b267-d1d87ed45cf3.png)

2. On the little lower right check mark icon that appears by default, display instead a question mark (?) and when it's clicked, pop up a question: "This box requests spellcheckers be disabled. Enable Language Tools here", which we could click to override manually for that text box. 
![image](https://user-images.githubusercontent.com/7296506/153386630-31f0cef6-13aa-41a4-9006-c6095cbb10de.png)

Essentially that puts the risk taking decision in the hands of the user. The option can be introduced with a caveat if need be. That the designers chose to disable spell checkers for a reason. 

In this case, I doubt forem did intend that for any good reason and that they will fix this. I made a case for that in the issue above.

**Comment by Defman21** [comment] 2022-02-10 12:51
@tiff does the web extension handle `data-gramm_editor=false` somehow? I've seen some observers for the `data-gramm` property in the Firefox debugger:

![image](https://user-images.githubusercontent.com/7100645/153411930-a1bf2042-8c84-4493-b6e5-b3fb792d98bd.png)

If the extension disables itself when it sees the property, then that's the cause of the issue.

**Comment by tiff** [comment] 2022-02-10 20:54
It appears that our extension is excluding itself from the text field by setting `spellcheck="false"`. This happens because forem is cloning the textarea that initially received the user's focus. The initial textarea is then removed from the dom. This confuses our add-on. We will make the add-on more robust to beter handle such cases.

**Comment by tiff** [comment] 2022-02-24 13:51
We are rolling out a fix for this. It will take 1-2 weeks until it reached every user.

**Closed by tiff** 2022-02-24 13:51 UTC
Labels: browser-add-on
