### ISSUE TITLE
NoClassDefFoundError: com/sun/star/task/XJobExecutor

### ISSUE THREAD

**Issue by madmanRB** [languagetool-org/languagetool#5192] opened 2021-06-13 04:25 UTC
`(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000ajava stack trace:\X000ajava.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000a\X0009at java.base/java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)\X000a\X0009at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)\X000a\X0009at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:514)\X000a\X0009at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:422)\X000a\X0009at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:416)\X000a\X0009at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)\X000a\X0009at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:415)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:576)\X000a\X0009at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:855)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000aCaused by: java.lang.ClassNotFoundException: com.sun.star.task.XJobExecutor\X000a\X0009at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)\X000a\X0009... 14 more\X000a", Context = (com.sun.star.uno.XInterface) @0 } }`

trying to install languagetool in Kubuntu 20.04, java is installed

**Comment by dpelle** [comment] 2021-06-13 05:23
Try:
```
$ sudo apt install libreoffice-java-common
```

Solution found here among other places:
https://forum.languagetool.org/t/error-while-adding-it-with-extension-manager-in-libreoffice-6/4399
https://forum.languagetool.org/t/breton-grammar-checker/49/4

There used to be a FAQ about common problems on languagetool.org but I don't see it now.
Maybe I missed it.

**Comment by madmanRB** [comment] 2021-06-13 05:26
Nope have that, tried reinstalling java too.
Very odd, I may have to reset LibreOffice or something

**Comment by dpelle** [comment] 2021-06-13 05:40
Which version of LanguageTool have you installed?
I've just installed the latest stable version from https://extensions.libreoffice.org/en/extensions/show/languagetool (i.e. release 5.3) on my xubuntu-18.04.5 and it worked without problems.

I was pretty sure that the error "UNO calling Java method ..." was caused by the missing package "libreoffice-java-common" but you said you have that package. I have to see that the instruction to install this package are rather hidden nowadays on the website :-(

What does this print?
```
$ env | grep -i java
```
```

**Comment by madmanRB** [comment] 2021-06-13 17:01
I was installing 5.3.

I will have to get back to you later if I don't work out what happened here, I am going through some of my settings elsewhere as the issue may have been caused by an update.
All I know so far is that I had a system hiccup before this happened, but what from I have no idea, thus why I am backtracking a bit.
It may be related to java but its very hard to tell at this point

**Comment by FredKruse** [comment] 2021-11-18 18:57
The issue seems not be related direct to LT. It seems to be related to the LO or Java installation. I close it. Please open a new issue, if an exception should occur at the latest version.

**Closed by FredKruse** 2021-11-18 18:57 UTC
Labels: office-integration

**Comment by robstoll** [comment] 2022-05-05 08:04
same issue here.

LibreOffice Version: 6.4.7.2
Java openjdk 11.0.15 2022-04-19

`sudo apt install libreoffice-java-common`

did the trick
