### ISSUE TITLE
Does LT make LibreOffice 7.2 to crash?

### ISSUE THREAD

**Issue by jeanpat** [languagetool-org/languagetool#5799] opened 2021-10-10 13:15 UTC
Hello,
Libreoffice 7.2 is completely unstable under ubuntu 20.04:

```
$ libreoffice 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

(soffice:56628): Gdk-WARNING **: 19:36:54.513: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.

(soffice:56628): Gtk-ERROR **: 19:36:54.528: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported


Fatal exception: Signal 5
Stack:
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x3e9a3)[0x7f03bbf449a3]
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x3eb1a)[0x7f03bbf44b1a]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f03bbd2b210]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x58295)[0x7f03bb461295]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_log_default_handler+0xb9)[0x7f03bb462319]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_logv+0x21c)[0x7f03bb46255c]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_log+0x93)[0x7f03bb462743]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(+0x13ab18)[0x7f0301152b18]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_option_context_parse+0x9f)[0x7f03bb467b2f]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_parse_args+0xb0)[0x7f0301152e70]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_init_check+0xd)[0x7f0301152edd]
/usr/lib/jvm/java-8-oracle/jre/lib/amd64/libawt_xawt.so(+0x3cd0d)[0x7f0301b15d0d]
/usr/lib/jvm/java-8-oracle/jre/lib/amd64/libawt_xawt.so(Java_sun_awt_UNIXToolkit_load_1gtk+0x9)[0x7f0301b11bf9]
[0x7f0385016347]
```
Is languagetool guilty?

**Comment by FredKruse** [comment] 2021-11-18 18:23
The issue is solved. I close the issue.

**Closed by FredKruse** 2021-11-18 18:23 UTC
Labels: office-integration
