### ISSUE TITLE
LanguageTool add-on for LibreOffice hangs (nightly)

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#2941] opened 2020-05-17 10:01 UTC
@FredKruse 

Hello!

I am having several issues with LT.

For example, I have been adding words to spelling.txt plus added.txt and the words in the document I have been using for the task underlines them as red but if we right-click it shows no options (the add-on supposedly added them to LibreOffice but it isn't working 100% okay).

Now for the ticket issue:
For sometime that LT add-on hangs on certain occasions.

Here is attached a file that if you go to the new tab in LibreOffice and select "Check Grammar", LT opens a window and hangs.

Could you take a look at it?

Thanks!

[LT_hangs_20200517.zip](https://github.com/languagetool-org/languagetool/files/4640021/LT_hangs_20200517.zip)

**Comment by yakovru** [comment] 2020-05-17 10:30
See also: https://github.com/languagetool-org/languagetool/issues/2802

**Comment by yakovru** [comment] 2020-05-17 13:51
I get  error on Win10(x64) With LO 6.3(x64), when  I call LT configuration dialog.
![Error LT5 0 on LO6 3](https://user-images.githubusercontent.com/5228814/82148971-344c8800-985e-11ea-843e-a0145b3b2135.jpg)

**Comment by yakovru** [comment] 2020-05-17 14:11
On Linux with LO6.3 LT configuration dialog working correctly.

**Comment by FredKruse** [comment] 2020-05-18 11:46
@yakovru The problem you mentioned should be solved by the last update. Please test it tomorrow. I work with Linux, so I can't test the Windows issue.

**Comment by FredKruse** [comment] 2020-05-18 11:53
@marcoagpinto I opened your file and start check text (F7) or Button at the new LanguageTool toolbar. It works fine. It shows a grammar message that can be handled. Could you please describe what exactly you did, to get the issue?

**Comment by marcoagpinto** [comment] 2020-05-18 12:09
@FredKruse 

I am on Windows 10 x64 and LO 6.4.3.

I simply opened the document and clicked on the first button of the new LT toolbar (check grammar).

It opened an empty window and did nothing  (hang).

**Comment by marcoagpinto** [comment] 2020-05-18 12:13
@FredKruse 
See attached screenshot:
![LO_blank_window_20200518](https://user-images.githubusercontent.com/5192600/82211756-49cabc00-9909-11ea-87ea-95d633f143c1.png)

**Comment by yakovru** [comment] 2020-05-19 04:59
@FredKruse

Hello!
Config dialog work correctly on LO Win10 now.

**Comment by FredKruse** [comment] 2020-05-19 05:58
@marcoagpinto Please test with the new nightly build. I'm not sure if the changes solve the problem, but we should test it.

**Comment by marcoagpinto** [comment] 2020-05-19 06:27
@FredKruse 

It still happens. :-(

Also, There are proper names I have added to the Portuguese spelling.txt plus added.txt and they still appear as typos :-(

"As equações de estatística (Fisher, Bayes, Markow, Dempster e Schaffer)."

**Comment by marcoagpinto** [comment] 2020-05-21 08:06
@FredKruse 
Hello!

Could you at least make the old behaviour of adding words from the added.txt plus spelling.txt to the LibreOffice dictionary?

One of your last changes broke it.

Thanks!

**Comment by FredKruse** [comment] 2020-05-22 10:47
@marcoagpinto 
Hello,
under this issue you talk about two different problems:

1. The spelling dialog hangs: I installed a Windows 10 (64 bit) for tests. I used LO 6.4.4.2 and Java 8. I installed the latest LT-Snapshot. Everything worked fine. I was able to open the dialog and it showed the message of the blue wavy underlining: "Esta frase nao tem verbo. ...". So I can not reproduce the error. Please remove your LO installation and install a new version. I hope this will solve the problem.
2. The Typos problem: The automatic dictionary I have installed, effects only the spell check (red wavy underlining) which is done by LO (not LT). The typos messages are produced by Portuguese rules of LT. I'm not involved in the development of those rules. This is not a bug of LT extension. By the way, these messages did not appear in my tests with the latest snapshot.

**Comment by marcoagpinto** [comment] 2020-05-22 11:12
@FredKruse 

I have created a video of the issues:
https://youtu.be/6_H9jetEmPA

**Comment by marcoagpinto** [comment] 2020-05-22 11:14
ahhhh... LO 6.4.4.2 is out?

Let me download and install it.

I will shortly comment.

**Comment by marcoagpinto** [comment] 2020-05-22 11:25
@FredKruse 

It still happens with LO 6.4.4.2 :-(

I am so sad!

**Comment by FredKruse** [comment] 2020-05-24 12:02
I am a bit frustrated, too. I got no solution and can't still reproduce the issue. The only idea I got, is a systematic analysis. Please do the following steps:

1. Open LO and deactivate LT inside the extension manager. Restart LO. Open the spelling dialog (F7) (the default dialog is also used by LT). If the spelling dialog doesn't work, this is not a LT issue and  you should discuss it with the LO developer team. Otherwise, go to next step.
2. Activate LT again and restart LO. Open the LT-dialog, go to the "general"-tab and give me here a screenshot from your settings. Go to the next step.
3. Save your settings by clicking OK inside the option panel. Close LO. Open your config file. It is named: LanguageTool.cfg. It is stored in directory: C:\users\YOUR_USERNAME\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice. (YOUR_USERNAME is your personal user name. If you don't see the directory AppData, you have to activate the show hidden files option in your Windows explorer settings.) After you had opend the config file add the line:
logLevel=3
at the beginning of the config file. Save the changes and close the file. Then open again your test file and open the dialog. After that close LO and post the LT log file (LanguageTool.log; in the same directory as the config file) here. Hopefully I can see the problem inside the logging data.

Good luck!
Fred

**Comment by marcoagpinto** [comment] 2020-05-24 12:18
@FredKruse 
I swear I don't know what happened:
![lt_general_tab_20200524](https://user-images.githubusercontent.com/5192600/82753844-efc26e80-9dc0-11ea-9616-5735c5b7469a.png)

I went to settings and pressed the close button.

Then, it all works, both the button in the toolbar and the words no longer appear as typos...

It is very weird.

**Comment by marcoagpinto** [comment] 2020-05-24 13:21
@FredKruse 
I have just installed the latest LT and it got red underlining again.

But, going to the menu on the screenshot above and clicking on "OK" fixed it.

Isn't there a way of it being automatic?

**Comment by FredKruse** [comment] 2020-05-24 17:16
I found an error by adding spelling.txt. This could cause the red underlining (see issue #292). Please try again with the snapshot tomorrow.

**Comment by marcoagpinto** [comment] 2020-05-24 17:20
Thanks!

**Comment by marcoagpinto** [comment] 2020-05-26 07:17
@FredKruse 

The issue still happens.

See the video:
https://youtu.be/tm11uWEcECc

This is fixable by manually going to LT settings → General → OK

See in the video that after I press OK, the "Homo Sapiens Sapiens" turns to blue underlining instead of red.

I added "sapiens" yesterday.

Can't you code something that does the same as clicking OK in the settings general?

**Comment by FredKruse** [comment] 2020-06-02 18:31
A refresh is added after the dictionary is added. Please test it and close the issue if it works.

**Comment by FredKruse** [comment] 2020-09-26 15:29
solved

**Closed by FredKruse** 2020-09-26 15:29 UTC
Labels: bug, office-integration
