### ISSUE TITLE
[pt-br] Any substantive used as adjective remain invariable

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#5624] opened 2021-09-03 01:13 UTC
LT (LanguageTool) doesn't detect the grammatical error in the sentence below:

> As meninas curtem livros de capas rosas.

The correct one is:

> As meninas curtem livros de capas rosa.

The adjective "rosa" _("pink")_ comes from the substantive "rosa" _("rose")_, that's why the adjective "rosa" _("pink")_ doesn't go to the plural.

The same goes to the cases below:

> blusas cinza

> calças laranja

**Comment by marcoagpinto** [comment] 2021-09-03 07:03
@hmslima 

Hello!

I will fix it on Monday.

Thank you for your feedback!

**Comment by hmslima** [comment] 2021-09-03 15:28
@marcoagpinto , thank you. I just cited three examples (_"rosa"_, _"cinza"_ and _"laranja"_), but there are more words in this category. For example:

> blusas violeta
> paredes gelo
> calças vinho
> cortinas creme

I don't know how do you guys do the programming, but it's better to see some articles before, here are some good articles:

* [O plural das cores – 11Editora](https://www.11editora.com.br/index.php/blog/o-plural-das-cores/)
* [Plural das cores – Só Português](https://www.soportugues.com.br/secoes/FAQresposta.php?id=130)

**Comment by marcoagpinto** [comment] 2021-09-04 03:59
I will be at my job during the weekend.

Can the word before the singular adj+noun also be a plural adj+noun?

`AQ0.P.+|NC.P.+ **FOLLOWED** BY AQ0.S.+|NC.S.+`
?

**Comment by hmslima** [comment] 2021-09-05 20:36
@marcoagpinto 

> Can the word before the singular adj+noun also be a plural adj+noun?

I am not sure whether I understood your question, which "word" you mean (do you mean the article?). But here is the explanation.

As you know, the adjective agrees with the noun in number and gender:

> a camisa vermelha
> as camisas vermelhas
> o lenço vermelho
> os lenços vermelho
> a camisa velha e vermelha

**Comment by hmslima** [comment] 2021-09-05 21:18
@marcoagpinto 

> Can the word before the singular adj+noun also be a plural adj+noun?

I am not sure whether I understood your question, which "word" you mean *(do you mean the article?)*. But here is the explanation.

As you know, the adjective agrees with the noun in number and gender:

> a camisa vermelha *(the red shirt)*
> as camisas vermelhas *(the red shirts)*
> o lenço vermelho *(the red scarf)*
> os lenços vermelho *(the red scarfs)*
> a camisa velha e vermelha *(the old and red shirt)*
> as camisa velhas e vermelhas *(the old and red shirts)*

If you can give me a sentence or phrase as an example *(it can be in English)*, I can try to give you a better answer.

Perhaps you mean a *"locução adjetiva"* *(¿adjective phrase?¿adjective locution? It's the combination of preposition + noun/adverb that has the role of an adjective)*:

> **noite de chuva** ***(night of rain)*** = noite chuvosa *(rainy night)*
> **noites de chuva** ***(nights of rain)*** = noites chuvosas *(rainy nights)*
> **atitudes de anjo** ***(attitudes of angel)*** = atitudes angelicais *(angel(ical) attitudes)*
> **menino do Brasil** ***(boy from Brazil)*** = menino brasileiro *(brazilian boy)*
> **menina do Brasil** ***(girl from Brazil)*** = menina brasileira *(brazilian girl)*
> **homem sem coragem** ***(man without courage)*** = *(courageless man)*
> **TV em cores** ***(TV in colors)*** = TV colorida *(color TV)*

Even in a *"locução"*, nothing changes:

> **um cesto de bolas amarelas** = a basket of yellow balls (a yellow ball basket)
> **um cesto de bolas cinza** = a basket of gray balls (a gray ball basket)
> **um cesto de chapéus amarelos** = a basket of yellow hats (a yellow hat basket)
> **um cesto de chapéus cinza** = a basket of gray hats (a gray hat basket)
*In this case, the words "cesto", "bolas" and "chapéus" remain as nouns, "amarelo" is a normal adjective, and "cinza" is an adjective (gray) that came from a noun (ash). This last one – "cinza" – is our special case, I only put the example with "amarelo" to show how an ordinary adjective behaves*

Anyway, the case that I brought here *(invariable adjectives)* is special, so I suppose that it is better to treat it as an "***exception***" in the LanguageTool's code than a *norm*.

<hr>

> In simple words: can the plural noun before be an adjective too?

I am no grammarian, but as far as I know, a noun is a noun. Once you define the role of a word in the phrase/sentence, you cannot imagine that it has other rule.

> **Tem uma rosa no meu jardim** = There’s a rose in my garden
*"rosa" here is a noun, nothing can change that.*

> **Tem um vaso rosa no meu jardim** = There’s a pink vase in my garden
*"rosa" here is an adjective, nothing can change that.*

**Comment by marcoagpinto** [comment] 2021-09-06 07:11
@hmslima 

Hello!

I have started by creating an antipattern in the number agreement rule so that it does trigger false positives:
https://github.com/languagetool-org/languagetool/commit/6639fb25c883c25c03b89c83843b9b2a846ac519

Could you check the diff of the .txt files to see if only correct sentences have been removed?
[before_antipattern.txt](https://github.com/languagetool-org/languagetool/files/7113987/before_antipattern.txt)
[after_antipattern.txt](https://github.com/languagetool-org/languagetool/files/7113989/after_antipattern.txt)

**Comment by marcoagpinto** [comment] 2021-09-06 08:40
@hmslima 

The rule generates too many false positives:
```
SentenceSourceChecker: org.languagetool.dev.dumpcheck.DocumentLimitReachedException: Maximum number of documents (600000) reached
Portuguese (Portugal): 146793 total matches
Portuguese (Portugal): ø0.24 rule matches per sentence
Portuguese (Portugal): 0 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

Because:
As blusas violetas. → As blusas violeta.
As paredes gelos. → As paredes gelo.
As calças vinhos. → As calças vinho.
As cortinas cremes. → As cortinas creme.

"gelos", "vinhos" and "cremes" are not adjectives, so I tried to use nouns in the rule, and it triggers tons of false positives.

@jaumeortola @udomai 
Any way of going around this?

**Comment by marcoagpinto** [comment] 2021-09-06 08:41
Also,

`As blusas violetas.`

"violetas" appears as an adjective and not also as a noun, although I added morphological information to also be a noun.

**Comment by marcoagpinto** [comment] 2021-09-06 08:43
ahhh.. the synthesiser says it is also a noun, but used after "blusas" it is shown as an adjective.

**Comment by marcoagpinto** [comment] 2021-09-06 08:47
```
	<!-- AS BLUSAS VIOLETAS as blusas violeta -->
    <rulegroup id='SUBSTANTIVOS_USADOS_COMO_ADJETIVOS_INVARIAVEIS' name="Substantivos usados como adjetivos invariáveis" type='style'>
    <!--      Created by Marco A.G.Pinto, Portuguese rule 2021-09-06 (25-JUN-2021+)      -->
	<!-- Thanks to hmslima (GitHub) -->
	<!--
As blusas violetas. → As blusas violeta.
As paredes gelos. → As paredes gelo.
As calças vinhos. → As calças vinho.
As cortinas cremes. → As cortinas creme.
	-->	
	<rule>
      <pattern>
		<token postag='NC.P.+' postag_regexp='yes'/>
		<marker>
			<token postag='AQ0.P.+' postag_regexp='yes'/>
		</marker>
      </pattern>
	  <message>Os substantivos usados como adjetivos mantêm-se invariáveis.</message>
	  <suggestion><match no='2' postag="AQ0(.)P0" postag_replace='AQ0$1S0' postag_regexp="yes"/></suggestion>	  
      <example correction="violeta">O Rui quer as blusas <marker>violetas</marker>.</example>
	  <example>As blusas violeta.</example>
	  <example>As paredes gelo.</example>
	  <example>As calças vinho.</example>
	  <example>As cortinas creme.</example>
	</rule>
	
	<rule>
      <pattern>
		<token postag='NC.P.+' postag_regexp='yes'/>
		<marker>
			<token postag='NC.P.+' postag_regexp='yes'/>
		</marker>
      </pattern>
	  <message>Os substantivos usados como adjetivos mantêm-se invariáveis.</message>
	  <suggestion><match no='2' postag="NC(.)P000" postag_replace='NC$1S000' postag_regexp="yes"/></suggestion>	  
      <example correction="gelo">O Rui quer as blusas <marker>gelos</marker>.</example>
	  <example>As blusas violeta.</example>
	  <example>As paredes gelo.</example>
	  <example>As calças vinho.</example>
	  <example>As cortinas creme.</example>
    </rule>	  
    </rulegroup>
```

**Comment by marcoagpinto** [comment] 2021-09-06 10:15
@hmslima 

Could you please give as many examples as possible of the right way of writing?

Now I am confused about what is wrong and right:
```
um cesto de bolas amarelas = a basket of yellow balls (a yellow ball basket)
um cesto de bolas cinza = a basket of gray balls (a gray ball basket)
um cesto de chapéus amarelos = a basket of yellow hats (a yellow hat basket)
um cesto de chapéus cinza = a basket of gray hats (a gray hat basket)

I guess I will need to strict the rule.
```

**Comment by hmslima** [comment] 2021-09-06 19:36
@marcoagpinto 
> Could you check the diff of the .txt files to see if only correct sentences have been removed?
> [before_antipattern.txt](https://github.com/languagetool-org/languagetool/files/7113987/before_antipattern.txt)
> [after_antipattern.txt](https://github.com/languagetool-org/languagetool/files/7113989/after_antipattern.txt)

It's true that I do a bit of programming, but I am not an actual programmer. I only *amateurishly* make software for my personal needs. I am sorry, I cannot help here.

<hr>

> "gelos", "vinhos" and "cremes" are not adjectives, so I tried to use nouns in the rule, and it triggers tons of false positives.

The good news is that although the list of words is not small, it's not thaaaat big:
* rosa
* cinza
* laranja
* gelo
* vinho
* creme
* ferrugem
* *And you can put here all names from [here](https://pt.wikipedia.org/wiki/Lista_de_cores)* ***that came from*** *fruits ("[ameixa](https://pt.wikipedia.org/wiki/Ameixeira)"), flowers ("[lilás](https://pt.wikipedia.org/wiki/Syringa)"), stones ("[ametista](https://pt.wikipedia.org/wiki/Ametista)"), and other things. Most color names don't have an own origin, there are even colors like ["magenta" that exist thanks to a battle](https://en.wikipedia.org/wiki/Magenta,_Lombardy)!*

I don't know how you guys do the coding of LanguageTool, and much likely what I am going to propose is unrealistic, but a start would be put all of these words in a specific list – let's call it *"color_origin"* in this example –, so if there is this structure:

    plural_noun + word_from_the_"color_origin"_list_in_the_plural_form

LanguageTools warns the user that if `"color_origin"` is a color, this word must be invariable. I don't know whether you already tried it and whether it causes any false positives.

<hr>

> "violetas" appears as an adjective and not also as a noun, although I added morphological information to also be a noun.

Although, nowadays, people mostly use the word "violeta" as an adjective, actually it is the name of a flower, you can read the Wikipedia article [here](https://pt.wikipedia.org/wiki/Violaceae). Other words in the same situation are: "[lilás](https://pt.wikipedia.org/wiki/Syringa)" and "[fúchsia](https://pt.wikipedia.org/wiki/Fuchsia)".

<hr>

> ahhh.. the synthesiser says it is also a noun, but used after "blusas" it is shown as an adjective.

The synthesiser is 100% correct, the real problem is not the classification of the word, but how LanguageTool deals with them since they are no ordinary adjectives.

> Presenteei minha namorada com uma violeta = I gifted my girlfriend with a violet

*Here "violeta" is a noun*

> Presenteei minha namorada com uma blusa violeta = I gifted my girlfriend with a violet blouse

*Here "violeta" is an adjective. But notice, an adjective like "violeta" is not like an adjective like "vermelho" ("red") or "branco" ("white").*

The problem is that since "violeta" comes from a noun, this word cannot behave like other adjectives like "azul" *("blue")* or "amarelo" *("yellow")*

<hr>

> Could you please give as many examples as possible of the right way of writing?

> Now I am confused about what is wrong and right:

> > um cesto de bolas amarelas = a basket of yellow balls (a yellow ball basket)
> >um cesto de bolas cinza = a basket of gray balls (a gray ball basket)
> >um cesto de chapéus amarelos = a basket of yellow hats (a yellow hat basket)
> >um cesto de chapéus cinza = a basket of gray hats (a gray hat basket)

> I guess I will need to strict the rule.

It's very simple, **they all are adjectives** in the context of those sentences: *"amarelo"*,* "cinza"*, *"violeta"*, *"vermelho"*, etc. The problem is that if the adjective comes from a noun, it will not agree with the gender and number of the noun.

**Normal adjectives:**

* **o chapéu vermelho** = the red hat
* **a camisa vermelha** = the red shirt
* **os chapéus vermelhos** = the red hats
* **as camisas vermelhas** = the red shirts
* **o chapéu branco** = the white hat
* **a camisa branca** = the white shirt
* **os chapéus brancos** = the white hats
* **as camisas brancas** = the white shirts
* **o chapéu verde** = the green hat
* **a camisa verde** = the green shirt
* **os chapéus verdes** = the green hats
* **as camisas verdes** = the green shirts
* **o chapéu amarelo** = the yellow hat
* **a camisa amarela** = the yellow shirt
* **os chapéus amarelos** = the yellow hats
* **as camisas amarelas** = the yellow shirts
* **o chapéu azul** = the blue hat
* **a camisa azul** = the blue shirt
* **os chapéus azuis** = the blue hats
* **as camisas azuis** = the blue shirts

**Adjectives that came from a noun:**

* **o chapéu rosa** = the pink hat
* **a camisa rosa** = the pink shirt
* **os chapéus rosa** = the pink hats
* **as camisas rosa** = the pink shirts
* **o chapéu cinza** = the gray hat
* **a camisa cinza** = the gray shirt
* **os chapéus cinza** = the gray hats
* **as camisas cinza** = the gray shirts
* **o chapéu violeta** = the violet hat
* **a camisa violeta** = the violet shirt
* **os chapéus violeta** = the violet hats
* **as camisas violeta** = the violet shirts
* **o chapéu laranja** = the orange hat
* **a camisa laranja** = the orange shirt
* **os chapéus laranja** = the orange hats
* **as camisas laranja** = the orange shirts

.

So, let's go back to my previous example:

> um cesto de bolas amarelas = a basket of yellow balls (a yellow ball basket)
>um cesto de bolas cinza = a basket of gray balls (a gray ball basket)
>um cesto de chapéus amarelos = a basket of yellow hats (a yellow hat basket)
>um cesto de chapéus cinza = a basket of gray hats (a gray hat basket)

All of them are correct! 🙂 Sorry if I didn't make it clear.
"amarelas" and "amarelos" agree in  gender and number with their respective nouns because "amarelo" is a "pure adjective", while "cinza" ("gray") is invariable because it comes from a noun that means "ash".

**Comment by marcoagpinto** [comment] 2021-09-06 20:34
ahhh... I will have another go at it at 5am 🙂 

Creating a small list of words is easy 🙂

**Comment by hmslima** [comment] 2021-09-06 22:48
@marcoagpinto 

I cannot help you with the programming, but I will always try to help with information.

By the way, I checked your profile and I noticed you are from Portugal. It seems that even European Portuguese follow the same rule of Brazilian Portuguese in this aspect, as you can see in the articles of the links below:

* [«Olhos cinza»](https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/olhos-cinza/35017)
* [O plural de adjetivos simples referentes a cor](https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/o-plural-de-adjetivos-simples-referentes-a-cor/32726)

**Comment by marcoagpinto** [comment] 2021-09-07 05:39
@hmslima 

Hello!

Is this okay?:
```
	<!ENTITY cores_invariaveis "açafrão|água|alizarina|amarelo|âmbar|ameixa|amêndoa|ametista|aspargo|azul|bege|bordô|borgonha|branco|branco|brasil|bronze|caqui|caramelo|cardo|carmesim|carmim|castanho|cenoura|cereja|chocolate|ciano|cinza|cinza|cobre|concha|coral|creme|creme|dainise|dourado|ébano|eminência|escarlate|esmeralda|eucalipto|fandango|feldspato|ferrugem|ferrugem|flerte|fúchsia|fuligem|gainsboro|gelo|glitter|goiaba|grená|heliotrópio|herbal|independência|índigo|iris|jade|jambo|jasmine|kiwi|kobi|kobicha|laranja|laranja|lavanda|lemon|lilás|lima|linho|madeira|magenta|malva|mamão|maná|marfim|marrom|milho|mocassim|mostarda|naval|neve|nyanza|ocre|oliva|orquídea|ouro|pardo|pêssego|prata|preto|púrpura|quantum|quartz|renda|rosa|rosa|roxo|rútilo|salmão|sépia|siena|tangerina|terracota|tijolo|tomate|triássico|trigo|turquesa|ube|urucum|verde|vermelho|vinho|violeta|xanadu|zaffre">
    <!-- Taken from: https://pt.wikipedia.org/wiki/Lista_de_cores -->
```

I am about to implement it into code.

**Comment by marcoagpinto** [comment] 2021-09-07 06:26
@hmslima 

Hello!

I have implemented the rule:
https://github.com/languagetool-org/languagetool/commit/e5f869f15d38c75330e94d5aa2e3ce4d27032bcb

However, I am not convinced with the results.

Could you check the attachment txt with a 900 000 sentences test?

I believe some colours must be removed from the list.

Thanks!

[before.txt](https://github.com/languagetool-org/languagetool/files/7119389/before.txt)

**Comment by hmslima** [comment] 2021-09-07 19:03
> Is this okay?:
> 
> ```
> 	<!ENTITY cores_invariaveis "açafrão|água|alizarina|amarelo|âmbar|ameixa|amêndoa|ametista|aspargo|azul|bege|bordô|borgonha|branco|branco|brasil|bronze|caqui|caramelo|cardo|carmesim|carmim|castanho|cenoura|cereja|chocolate|ciano|cinza|cinza|cobre|concha|coral|creme|creme|dainise|dourado|ébano|eminência|escarlate|esmeralda|eucalipto|fandango|feldspato|ferrugem|ferrugem|flerte|fúchsia|fuligem|gainsboro|gelo|glitter|goiaba|grená|heliotrópio|herbal|independência|índigo|iris|jade|jambo|jasmine|kiwi|kobi|kobicha|laranja|laranja|lavanda|lemon|lilás|lima|linho|madeira|magenta|malva|mamão|maná|marfim|marrom|milho|mocassim|mostarda|naval|neve|nyanza|ocre|oliva|orquídea|ouro|pardo|pêssego|prata|preto|púrpura|quantum|quartz|renda|rosa|rosa|roxo|rútilo|salmão|sépia|siena|tangerina|terracota|tijolo|tomate|triássico|trigo|turquesa|ube|urucum|verde|vermelho|vinho|violeta|xanadu|zaffre">
>     
> ```

All words in this list are considered invariable adjectives? If it's that so, the answer is no, you've mixed the variable adjectives with the invariable ones, your list must be only for the invariable adjectives.

The good news is that you only need to remove few words from this list, remove these:

* amarelo
* azul
* branco *(why this word is duplicated? Anyway, remove both)*
* castanho
* dourado
* escarlate
* marrom
* pardo
* preto
* roxo
* rútilo
* vermelho
* verde

Maybe I made some mistake *(I mean, perhaps I considered a variable adjective as an invariable one or I forgot a variable adjective in the list)*, but if there are errors, we can correct them over time.

<hr>

Not all colors are invariable. Let me show you some examples:

**Variable adjectives:**

* **o carro amarelo** = the yellow car
* **a pedra amarela** = the yellow stone
* **os carros amarelos** = the yellow cars
* **as pedras amarelas** = the yellow stones

**Invariable adjectives:**

* **o carro cinza** = the gray car
* **a pedra cinza** = the gray stone
* **os carros cinza** = the gray cars
* **as pedras cinza** = the gray stones

***How do I know whether an adjective is variable or invariable?*** *By researching its origin, we know that a phrase like "as pedras cinzas" is wrong because the adjective "cinza" ("gray") came from the noun "cinza" ("ash"). On the other hand, "amarelo" is a variable adjective because the word itself is a "natural" adjective. Since it a thing that requires research, many native speakers commit mistakes in this topic.*

<hr>

By the way, there are some duplicates in the list, is that supposed to happen? Here are the duplicated ones:

* cinza
* creme
* ferrugem
* laranja
* rosa

**Comment by marcoagpinto** [comment] 2021-09-07 19:11
@hmslima 

Thank you, I will remove the colours at 5am because the nightly will come out in a few hours and the fixes will only appear in tomorrow's nightly (too late for tonight's).

Yes, there are duplicates in the list. I pasted the words here and only when I was testing them, the command TESTRULES PT complained about duplicates which I removed.

At 5am I will fix the list and tomorrow night I will paste the URL generated by the nightly so that you can check if all is well.

Thank you!

**Comment by hmslima** [comment] 2021-09-07 20:14
@marcoagpinto 

> Thank you, I will remove the colours at 5am because the nightly will come out in a few hours and the fixes will only appear in tomorrow's nightly (too late for tonight's).

> At 5am I will fix the list colours and tomorrow night I will paste the URL generated by the nightly so that you can check if all is well.

Good, because of the fact that list contain(ed) the variable adjectives that I pointed out, which shouldn't be there, there are some bizarre false positives like the ones below:

> O jardim estava cheio de flores **amarelas**.
> Isso inclui estrelas **azuis** em outras galáxias, que têm sido alvos de várias pesquisas nesta área.
> nas três primeiras filas horizontais, as peças **brancas**; e, nas três últimas, as peças **pretas**.
> Os anos de seu governo são lembrados como "Os Anos **Dourados**"
> Morre o último exemplar da espécie dos pandas **marrons**.
> Contagem referida aos faixas **pretas**, os faixas coloridas recebem o nome de Gub
> Ele quer copos **vermelhos**.
> Ouvi dizer que você não come verduras **verdes**. Você diz que é comida para animais.

All sentences above are correct. I hope not to see these false positives in the next test.

**Comment by hmslima** [comment] 2021-09-07 21:48
@marcoagpinto 

Even if we ignore the false positives caused by the variable adjectives that I asked you to remove, unfortunately still there are false positives caused by the other words that I fear **still will be present in the next test** unless you manage to deal with them in the code. Therefore, I think I can advance my analysis for you, so pay attention to my notes:

<hr>
<hr>

The sentences below are false positives because the words in question are already "native" adjectives if I am not mistaken.

> Sílvio Mota ordenou a prisão dos líderes do movimento, enviando um destacamento dos fuzileiros **navais**

> Do período em Lüneburg sobrevivem poucas obras, entre elas algumas variações **corais** no estilo de Böhm.

Here is the list of words to be removed from the list:

* bege
* coral
* fandango 
* flerte
* herbal
* naval
* pardo

<hr>
<hr>

**This is by far the biggest issue:**

The false positives from the sentences below follow a pattern: when the words are after an adjective *(or something equivalent like a numeral or past participle)*, it seems that LanguageTool thinks they're adjectives.

> ... dos Romanos, que ali iam fazer as suas curas e tanto bebiam como lavavam os seus corpos nas santas **águas**, para curar os seus males.

> ...abrigo, configurado como uma construção de madeira composta por quatro paredes e um telhado de duas **águas**.

> ...a grega que, quando morria, entrava em auto-combustão e, passado algum tempo, renascia das próprias **cinzas**.

> Em seu interior existem dobras chamadas **conchas** nasais, que forçam o ar a turbilhonar.

> Brassavola nodosaOriginária da América Central, foi uma das primeiras **orquídeas** americanas a serem levadas para a Europa.

> A Hungria perdeu dois **ouros**

> sa-tenista polonesa Natalia Partyka, que é dona de quatro medalhas paraolímpicas (dois **ouros** e duas **pratas**)

> A renda local cresceu bastante, propiciando a Nauru uma das maiores **rendas** per capita do mundo.

> Cada cidade custa dois **trigos** e três pedras.

> ...neros agrícolas da região, sendo de destacar as culturas de cereais, batata, legumes, frutas e bons **vinhos** de mesa, sobretudo o afamado vinho da Pipa e atá as cerejas.

The challenge is to make LanguageTool able to identify whether the word is a noun or an adjective...

<hr>
<hr>

> 1930 - Gilmar dos Santos **Neves**, ex-futebolista brasileiro.

Here, LanguageTool gave a false positive in a surname. I don't know how you could safely explain to a machine how to identify whether the word is an adjective or a noun in a case like this. Unless there is a resource that can deal with that, maybe it's better to sacrifice this entry *(I mean, remove "neve" from the list)*.

<hr>
<hr>

> Como não dispunham de pedras, os babilônios usavam em suas construções **tijolos** de barro cozido e azulejos esmaltados.

This is a tricky situation, I don't know how to "programmingly" solve this one.

<hr>
<hr>

> Já o arco íris, nas cores lilás e laranja, representavam o acordo oferecido aos que quisessem unir seus destinos aos de Pernambuco....

False positive too! "lilás" is already the singular form of the word *(OK, there is "lilá", but its synonym "lilás" is accepted as singular too)*, it would be wrong if the word "lilases" were used as an adjective.

<hr>
<hr>

I commented a lot about false positives, but there are situations where the error is not spotted:

> Os fotões vermelhos, **laranjas**, amarelos e verdes tendem a conseguir continuar em frente.

It should be *"Os fotões vermelhos, laranja, amarelos..."*

As I said, the problem is that it seems that LanguageTool cannot say whether the word is a noun or an adjective.

But I admit that there are situations that it's very difficult to a machine to know the class of the word, like in the sentence just below:

> ... é também por isso que ao pôr do Sol o céu não é azulado no horizonte, perto do Sol: há mais fotões amarelos e mesmo **laranjas** que vêm dessa direção depois de serem difundidos a partir da luz do Sol.

*I can understand why LanguageTool can see no error here.*

<hr>
<hr>
<hr>
<hr>
<hr>
<hr>

The good news is that LanguageTool finally can detect errors in the sentences below:

> Camisa laranja, calção e meias **laranjas**;

> Camisa cinza, calção e meias **cinzas**.

**Comment by marcoagpinto** [comment] 2021-09-08 00:37
@hmslima 

Here are the results by removing:
- cinza
- creme
- ferrugem
- laranja
- rosa

Now I am going to try to add some negate POS code.
[after.txt](https://github.com/languagetool-org/languagetool/files/7124941/after.txt)

**Comment by marcoagpinto** [comment] 2021-09-08 01:00
@hmslima 

I have just fixed:
```
	  <example>Sílvio Mota ordenou a prisão dos líderes do movimento, enviando um destacamento dos fuzileiros navais.</example>
	  <example>Do período em Lüneburg sobrevivem poucas obras, entre elas algumas variações corais no estilo de Böhm.</example>
```

By adding the command:
`<token negate_pos="yes" postag='SPS.+|DI.+' postag_regexp='yes'/>`

Results in attachment.
[after2.txt](https://github.com/languagetool-org/languagetool/files/7125007/after2.txt)

**Comment by marcoagpinto** [comment] 2021-09-08 01:22
@hmslima 

Proper names fixed:
```
[after3.txt](https://github.com/languagetool-org/languagetool/files/7125088/after3.txt)
```  

See attachment.

**Comment by marcoagpinto** [comment] 2021-09-08 01:41
@hmslima 

Fixed the numeric expressions:
```
	  <example>Cada cidade custa dois trigos e três pedras.</example>
	  <example>A Hungria perdeu dois ouros.</example>	
```

See attachment.
[after4.txt](https://github.com/languagetool-org/languagetool/files/7125143/after4.txt)

**Comment by marcoagpinto** [comment] 2021-09-08 03:53
@hmslima 
Fixed:
```
	  <example>Sendo de destacar as culturas de cereais, batata, legumes, frutas e bons vinhos de mesa.</example>
	  <example>Os babilónios usavam nas suas construções tijolos de barro cozido.</example>
	  <example>Já o arco-íris, nas cores lilás e laranja, representavam o acordo oferecido aos que quisessem unir os seus destinos aos de Pernambuco.</example>	  
	  <example>No seu interior existem dobras chamadas conchas nasais.</example>
```


But the rules can't tell the difference if the token "meias" is a verb or not. It doesn't trigger:
```
Uniforme Alternativo: Camisa cinza, calção preto e meias cinzas.
Camisa cinza, calções e meias cinzas.
```

The final result of the rule fixes is in the attachment.

Could you check for more false positives in it, since I am quite stressed to have a look? Thanks!
[after5.txt](https://github.com/languagetool-org/languagetool/files/7125699/after5.txt)

**Comment by marcoagpinto** [comment] 2021-09-08 04:55
@hmslima 
I am improving the rule even more.

Now it will detect:
```
Uniforme Alternativo: Camisa cinza, calção preto e meias cinzas.
Camisa cinza, calções e meias cinzas.
```
and I have removed some more false positives, by removing some more colours like you suggested, like "naval".

Give me a few minutes for the check against a 900 000 corpora.

**Comment by marcoagpinto** [comment] 2021-09-08 05:44
Well, I removed the antipattern for the "meias cinzas" since it damaged other sentences.

I have committed the changes:
https://github.com/languagetool-org/languagetool/commit/0d9df7d5f47d315b25cb57f513ecadfbfef0756c

So, here was the initial rule results:
[before.txt](https://github.com/languagetool-org/languagetool/files/7126133/before.txt)

And here is the last results:
[after6.txt](https://github.com/languagetool-org/languagetool/files/7126136/after6.txt)

It produced very few hits, and they were false positives I believe, which means I need to tweak the rule even more.

Maybe next week, I have already dedicated a full night to it and I can no longer look at the code.

Could you tell if there are other false positives?

A way of testing it is to download the nightly for LibreOffice, unzip it and replace its PT grammar.xml with this one:
[grammar.zip](https://github.com/languagetool-org/languagetool/files/7126159/grammar.zip)

and remove the:
`default="temp_off"`
from
`<rulegroup id='SUBSTANTIVOS_USADOS_COMO_ADJETIVOS_INVARIAVEIS' name="Substantivos usados como adjetivos invariáveis" type='style' default="temp_off">`

zip and rename back to .oxt and open with LibreOffice.

Then make some tests.

Thanks!

**Comment by hmslima** [comment] 2021-09-08 18:56
@marcoagpinto
> But the rules can't tell the difference if the token "meias" is a verb or not. It doesn't trigger:

If you think carefully about the phrases "meias cinzas" and "meias laranjas", theoretically, they could mean respectively  "half ashes" and "half oranges", what would be grammatically correct, "meias cinzas" and "meias laranjas" are wrong only in the context where they mean respectively "gray socks" and "orange socks".

<hr>
<hr>

> It produced very few hits, and they were false positives I believe, which means I need to tweak the rule even more.

That's very sad, the idea was detecting invariable adjectives, but it caused a lot of bugs and the tentative to solve them not only undid almost all the work, but also left some "bugs".  😢

<hr>
<hr>

> A way of testing it is to download the nightly for LibreOffice, unzip it and replace its PT grammar.xml with this one:
[grammar.zip](https://github.com/languagetool-org/languagetool/files/7126159/grammar.zip)

I followed your instructions, but it didn't work. I saw no difference. I pasted the sentences that this grammar mark as wrong, but I got now signal.

**Comment by marcoagpinto** [comment] 2021-09-08 19:06
@hmslima 

I will work again on the rule on Monday, as I came up with some ideas for it.

**Comment by marcoagpinto** [comment] 2021-09-08 19:08
The official LanguageTool release is only at the end of the month, so we still have around three weeks.

**Comment by marcoagpinto** [comment] 2021-09-10 09:06
@hmslima 

Hello!

With a clear mind, I have created an antipattern to the rule, and now it seems to be fully operational:
https://github.com/languagetool-org/languagetool/commit/d2d218e185b483b9aad501e6b9be4d6ae7adc004

I renamed the rule ID adding a "_V2" so that we can get fresh results tonight in the nightly.

If you don't have access to the nightly diffs, I will post the URL here tomorrow.

🙂

**Comment by marcoagpinto** [comment] 2021-09-11 04:23
@hmslima 

The rule gave zero hits:
https://internal1.languagetool.org/regression-tests//20210910/result_pt-PT_20210910_table.html

https://internal1.languagetool.org/regression-tests//20210910/result_pt-BR_20210910_table.html

So, we can call it "stable" and I have just enabled it:
https://github.com/languagetool-org/languagetool/commit/fc43af027b07afde9a6f4d444eda659bd9e9bff6

Sunday night it will be working normally in LibreOffice's nightly, then you can make some tests.

Right now, I am closing this ticket and only if you have ideas I will enhance the rule.

**Closed by marcoagpinto** 2021-09-11 04:23 UTC
Labels: Portuguese

**Comment by hmslima** [comment] 2021-09-11 23:34
@marcoagpinto 

> Os botões viraram lindas rosas vermelhas.

But "rosas" in this sentence is a noun, therefore this sentence is 100% correct! LanguageTool shouldn't recognize that as an error.

_The buds became beautiful red roses_

<hr>

> If you don't have access to the nightly diffs, I will post the URL here tomorrow.

I don't know what is that? Is it similar to that file `grammar.zip` that you asked me to install in my LibreOffice installation? If is that so, I was not able to activate it.

**Comment by marcoagpinto** [comment] 2021-09-12 04:40
@hmslima 

Hello!

My antipattern fixes the "Os botões viraram lindas rosas vermelhas.".

The rule that it triggers is not this one, but the hyphen missing one.

So, all working fine.

Forget the grammar.zip I suggested, since you can now use the nightly to test the rule.

I said Sunday night, but I meant Saturday night.

My idea of changing the .oxt was simple:
1) Rename the oxt to zip and extract it,
2) Replace its PT grammar.xml with the one attached here;
3) Compress back to zip;
4) Double-click on LibreOffice and install it.

This is how I test some rules directly in LibreOffice, but now it is not needed.

Thanks!

**Comment by hmslima** [comment] 2021-09-12 19:36
@marcoagpinto 
> Forget the grammar.zip I suggested, since you can now use the nightly to test the rule.

I cannot find the link to download the nightly version of LibreOffice's LanguageTool. Can you give me the link?

**Comment by marcoagpinto** [comment] 2021-09-12 21:47
@hmslima 

https://internal1.languagetool.org/snapshots/
