### ISSUE TITLE
Manage HTML entities interpretAs in error checking

### ISSUE THREAD

**Issue by maxiplay** [languagetool-org/languagetool#2118] opened 2019-11-05 07:59 UTC
Hello,

My text editor use HTML entities. 

For example `&nbsp;` for "non bracking space" or `&eacute;` for "é".

I tried to use AnnotatedTextBuilder to consider HTML entities like markup and use the "interpretAs" parameter to explain what is the markup.

For example : builder.addMarkup('`&eacute;`','é');

The problem is the interpretAs is not taken in account during checking.

Before checking
![image](https://user-images.githubusercontent.com/8363127/68188294-19dd4c00-ffa9-11e9-9309-f885450fcd23.png)

After checking 
![image](https://user-images.githubusercontent.com/8363127/68188647-ecdd6900-ffa9-11e9-9497-4c1ad72186aa.png)

The problem is the "é" is not underlined. Languagetool just analyse the word "chapatoire".

If I replace the "é" par "e" the checking is good because no usage of "interpretAs"

![image](https://user-images.githubusercontent.com/8363127/68188880-7ab95400-ffaa-11e9-8921-e27b0f8553c8.png)

**Comment by danielnaber** [comment] 2019-11-06 19:55
Thanks for the report, I cannot reproduce it, though. Could you write a test case?

**Comment by maxiplay** [comment] 2019-11-12 11:09
Yes, no problem. Will do it this afternoon.

**Comment by maxiplay** [comment] 2019-11-12 11:45
The test should be perhaps in the French package. To Test with others languages.

```
    @Test
    public void test() throws IOException {

        //"échapatoire" should be "échappatoire" with two 'p'
        String textToCheck = "Une &eacute;chapatoire est possible.";

        AnnotatedTextBuilder builder = new AnnotatedTextBuilder()

                .addText("Une ")
                .addMarkup("&eacute;", "é")
                .addText("chapatoire est possible.");
        JLanguageTool lt = new JLanguageTool(new French());
        RuleMatch match = lt.check(builder.build()).get(0);


        String hightlightedWord = textToCheck.substring(match.getFromPos(), match.getToPos());
        String wordThanShouldBeHighlighted = "&eacute;chapatoire";

        assertThat(hightlightedWord, is(wordThanShouldBeHighlighted));
    }
```

**Comment by danielnaber** [comment] 2019-11-12 16:39
Thanks, I can reproduce now. It seems the mapping created in https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/markup/AnnotatedTextBuilder.java#L118-L127 is not correct. I can put this on my to-do list, but I have no idea when I might have time to fix this. PRs welcome.

**Comment by danielnaber** [comment] 2019-11-12 16:39
Tests already exist at https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/fr/src/test/java/org/languagetool/rules/fr/AnnotatedTextTest.java

**Comment by maxiplay** [comment] 2019-11-12 16:55
Will contribute with pleasure.

**Comment by maxiplay** [comment] 2019-11-14 14:53
https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/fr/src/test/java/org/languagetool/rules/fr/AnnotatedTextTest.java
 

Do not compile. It would need to import languagetool-core into fr module. 
![Sans titre](https://user-images.githubusercontent.com/8363127/68867782-af3db600-06f6-11ea-9c7f-a6bc9c7939d6.png)


Will directly on languagetool\languagetool-core\src\test\java\org\languagetool\markup\AnnotatedTextTest.java

**Comment by maxiplay** [comment] 2019-11-14 15:02
Same problem in core project.

Would need to add fr module in core test dependency

```
        <dependency>
            <groupId>org.languagetool</groupId>
            <artifactId>language-fr</artifactId>
            <version>4.8-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
```

**Comment by danielnaber** [comment] 2019-11-14 15:06
This means you have not properly imported all modules into IntelliJ. You can usually just import the top-level `pom.xml` and select the option that says to import sub-modules (or something like that) and everything should be set up fine. core is then available in language-fr, but not vice versa.

**Comment by maxiplay** [comment] 2019-11-14 15:08
That's good. Thanks.

**Comment by danielnaber** [comment] 2019-11-19 15:45
I have manually merged your RP and made some very small cleanup. Thanks for the patch!

**Closed by danielnaber** 2019-11-19 15:45 UTC
