### ISSUE TITLE
Display line numbers in the textbox of the standalone version

### ISSUE THREAD

**Issue by fekete-robert** [languagetool-org/languagetool#336] opened 2015-11-17 15:10 UTC
Hi, 
The textbox of the standalone languagetool GUI does not display line numbers. If there are many errors in the text, this makes it difficult to find a specific error, because the error messages refer to the line numbers. This is especially true for longer texts.

Would it be possible to include line numbers in the textbox?

**Comment by danielnaber** [comment] 2015-12-21 11:53
Closing, it's basically a duplicate of https://github.com/languagetool-org/languagetool/issues/40

**Closed by danielnaber** 2015-12-21 11:53 UTC
Labels: enhancement
