### ISSUE TITLE
LT does not longer work on Edge Version 130.0.2849.46 (Official build) (64-bit)

### ISSUE THREAD

**Issue by talder** [languagetool-org/languagetool#10955] opened 2024-10-19 07:43 UTC
Hi,

Today i installed LT on a brand new computer with edge 130.x and LT does not work anymore. You can not click anything in the plugin dropdown. Also typing errors are not longer corrected nor can you seen the little menu on the left while i edit Google docs.

My son does use LT a lot for his dyslexia and it worked fine on 129, but when he installed his updates today, LT also stop working on Edge 130.x whit the same symptoms.

It seems like Edge version 130.x broke somethin for LT.

Kind regards,

Tim

**Comment by danielnaber** [comment] 2024-10-19 11:32
Thanks for the report, does this only happen on Google Docs or also on other sites (if so, which ones)?

**Comment by talder** [comment] 2024-10-19 11:51
Unfortunaly all sites, apps you use in the browser.

**Comment by danielnaber** [comment] 2024-10-20 18:40
Does the problem also appear with very simply pages as https://languagetool.org/development/textarea.html? I just tried it with the same Edge version, and it still works for me. If it doesn't work for you, do you have other add-ons running? Could you please turn them off temporarily to see if they interfere with LT?

**Comment by JTCHE** [comment] 2024-10-21 08:48
Hi there, I'll add my two cents to this issue by confirming that LT no longer works on any websites, including https://languagetool.org/development/textarea.html. I'm also running Edge 130.x !

**Comment by rubencastello90** [comment] 2024-10-21 10:05
Same here, reported that 2 months ago while I was on BETA CHANNEL for Edge and was ignored.

Thant was the response:
```
Hi,

Thank you for reaching out.

Please uninstall and install the Add-in, as it might be missing certain rules.
```

Rolling back to previous version of Edge Worked. Now is not possible.

**Comment by Misticos68** [comment] 2024-10-21 10:24
> O mesmo aqui, relatei isso há 2 meses enquanto eu estava no CANAL BETA para Edge e fui ignorado.
> 
> Thant foi a resposta:
> 
> ```
> Hi,
> 
> Thank you for reaching out.
> 
> Please uninstall and install the Add-in, as it might be missing certain rules.
> ```
> 
> Reverter para a versão anterior do Edge funcionou. Agora não é possível.

The same thing happened to me. Now it doesn’t work anywhere. :(

**Comment by tiff** [comment] 2024-10-21 12:17
We at LanguageTool currently cannot reproduce this problem. It might be related to a certain configuration, language or country. Would anyone here be available for a quick Zoom call to allow us investigating this issue remotely?

**Comment by rubencastello90** [comment] 2024-10-21 12:22
You got a mail from me

**Comment by danielnaber** [comment] 2024-10-21 14:07
Thanks to everyone involved in debugging. We think we have found the issue, and we're hopeful the update with a fix can be rolled out at the end of the week.

**Comment by tiff** [comment] 2024-10-22 12:01
I'm closing this. A fix is now available for all who installed the extension from the Edge store. For the one, who installed it from the Chrome store, we are in the progress of rolling it out.

**Closed by tiff** 2024-10-22 12:01 UTC
Labels: browser-add-on

**Comment by tiff** [comment] 2024-10-22 12:03
Also some background on the actual problem: Microsoft broke an extension API with it's latest release. Unfortunately we weren't able to see it coming because until today we are unable to reproduce the issue on our own testing machines. 

https://github.com/microsoft/MicrosoftEdge-Extensions/issues/179

**Comment by talder** [comment] 2024-10-22 17:50
I can confirm it is working again after updating the plugin. Thank you!
________________________________
Van: Christopher Blum ***@***.***>
Verzonden: dinsdag 22 oktober 2024 14:02
Aan: languagetool-org/languagetool ***@***.***>
CC: talder ***@***.***>; Author ***@***.***>
Onderwerp: Re: [languagetool-org/languagetool] LT does not longer work on Edge Version 130.0.2849.46 (Official build) (64-bit) (Issue #10955)


I'm closing this. A fix is now available for all who installed the extension from the Edge store. For the one, who installed it from the Chrome store, we are in the progress of rolling it out.
