### ISSUE TITLE
Build Failure for LanguageTool Wikipedia tools (Java 9)

### ISSUE THREAD

**Issue by rhlbns** [languagetool-org/languagetool#1039] opened 2018-07-02 06:38 UTC
I am on a mac system and trying to install languagetool. I cloned the git repository and did "mvn clean test", but I am getting following build error.

[INFO] LanguageTool Wikipedia tools ....................... FAILURE [ 22.146 s]
[INFO] LanguageTool HTTP API client ....................... SKIPPED
[INFO] LanguageTool development tools ..................... SKIPPED
[INFO] LanguageTool RPM 4.3-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:43 min
[INFO] Finished at: 2018-07-02T11:58:10+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project languagetool-wikipedia: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/home/languagetool/languagetool-wikipedia/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :languagetool-wikipedia

**Comment by danielnaber** [comment] 2018-07-02 07:17
Please paste the complete output of Wikipedia tools, the actual error is missing from the text you pasted.

**Comment by rhlbns** [comment] 2018-07-02 07:53
Hi Daniel please find the attached file containing complete terminal output on executing mvn clean test.
Do let me know if you need any surefire-reports, I will upload them accordingly.

This is the output of java --version
```
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```
I am on MacOS High Sierra 10.13.3
[logs.txt](https://github.com/languagetool-org/languagetool/files/2154298/logs.txt)

**Comment by danielnaber** [comment] 2018-07-02 08:18
Either remove `<module>languagetool-wikipedia</module>` from top-level `pom.xml` (if you don't need it) or compile with Java 8. Java 9 should work at runtime, but there's still a compilation issue.

**Comment by rhlbns** [comment] 2018-07-02 09:21
Hi Daniel, I switched to java 8 and build was successful. Thank you so much.

**Comment by dpelle** [comment] 2018-07-02 09:44
> or compile with Java 8. Java 9 should work at runtime, but there's still a compilation issue.

Can't we make it portable to build with Java 8 or Java 9?
I remember also stumbling upon the same issue weeks ago.

**Comment by danielnaber** [comment] 2018-07-02 10:44
> Can't we make it portable to build with Java 8 or Java 9?

That shouldn't be difficult, but I don't have time for that now. If you want to give it a try, that would be great.

**Comment by danielnaber** [comment] 2018-07-24 12:54
Duplicate of #1001

**Closed by danielnaber** 2018-07-24 12:54 UTC
