### ISSUE TITLE
[de] "wegen dem" false alarm?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1485] opened 2019-03-26 12:23 UTC
> Er war langsam wegen dem Verkehr.

![Bildschirmfoto 2019-03-26 um 13 21 40](https://user-images.githubusercontent.com/37363/54996638-2092f200-4fca-11e9-8ebf-733bd0e38168.png)

**Comment by tiff** [comment] 2019-03-26 12:30
ok got it, suggestion seems helpful and Duden Mentor is suggesting the same thing. Would it be possible to have a better error description? Something that suggests the usage of "wegen des"

**Comment by Discostu36** [comment] 2019-03-26 12:31
Duplicate of #1272

**Comment by tiff** [comment] 2019-03-26 12:32
Danke @Discostu36

**Closed** 2019-03-26 12:31 UTC
