### ISSUE TITLE
LibreOffice hangs if "LanguageTool check is complete." dialog is ignored

### ISSUE THREAD

**Issue by Elaborendum** [languagetool-org/languagetool#4697] opened 2021-03-28 05:58 UTC
For example, after clicking "Next spelling or grammar mistake" after all checks have been made, the dialog "LanguageTool check is complete." will pop up. If I click anywhere else while it's up, LibreOffice will hang.

Plus, even if completely frozen, LibreOffice will instantly turn back to normal if I just click "Accept" on that dialog. But due to the way LibreOffice is, it can be inconvenient to find once the mistake is done.

I don't know if this is just a "thing that happens" with LibreOffice extensions since I don't use many other extensions or if it's just my installation.

Log:
LT office integration log from Sun Mar 28 00:32:43 COT 2021
Java-Version: 1.8.0_281, max. Heap-Space: 3598 MB, LT Heap Space Limit: 3238 MB
Not a file URL: private:factory/swriter
getCachePath: documentPath == null!
Document 0 created; docID = 1
Internal LT dicitionary for language es added: Number of words = 654

Tested with the 5.3-snapshot, but the bug happens in previous versions too.

**Comment by caralu74** [comment] 2021-03-30 21:44
I have a similar issue, but when I try to open a file LO freezes, so I should uninstall the LanguageTool
[espanol tarea 2.zip](https://github.com/languagetool-org/languagetool/files/6232397/espanol.tarea.2.zip)
 to edit the file.

**Comment by FredKruse** [comment] 2021-04-02 18:40
The problem is solved. Please check it with the last snapshot and close the issue, if solved.

**Comment by Elaborendum** [comment] 2021-04-11 04:44
It seems to work in the lastest 5.4 snapshot, but now it disappears in such a way that it can't be found by alt-tabbing, unlike before and unlike the other dialogs. Clicking the button one more time doesn't show anything either.

Its reappearance behaviour is kinda inconsistent too, but it reappears most of the time when double clicking "Next spelling or grammar mistake" (as in, can be found when switching windows, not on top) or when clicking in any of the other extension buttons that open a dialog (in which case the "LanguageTool check is complete" dialog flashes for a second and closes itself).

Additionally, maybe relevant or not, I just noticed that the dialog changes after the first time you open any of the other dialogs in the extension:

From 
![image](https://user-images.githubusercontent.com/71190696/114292665-a66d2300-9a55-11eb-88fe-4285f832d37e.png)
to
![image](https://user-images.githubusercontent.com/71190696/114292667-acfb9a80-9a55-11eb-98fd-b2de9958eaaa.png)

**Comment by caralu74** [comment] 2021-04-22 22:52
For me the latest release solve my problem as well. So I could WRITE  SOLVED. Thanks you!

**Comment by Elaborendum** [comment] 2021-04-25 21:29
Just a few things, I tested today's snapshot and if I click anywhere else the first time the dialog opens, it will close itself. But doing it the second time won't work unless I manually close or accept it. This behaviour "reboots" after the dialog is manually closed.

If I click "Next spelling or grammar mistake" while another dialog is open and then close or accept the former (and bring it to the foreground if it was in the background), the latter will go into the background (and reappear if I click its respective button, change to any other window or look for it by alt-tabbing). This doesn't happen with the settings dialog, as it instead prevents me from interacting with the "LanguageTool check is complete." dialog until it (settings) is closed.

Also, a really minor thing, the current dialog has the (i) icon cut off as it can be seen in my previous comment.

A thing that happened with yesterday's snapshot is that when clicking "Next spelling or grammar mistake" thrice, the dialog turned fully white. Strangely enough, this fixed itself for a while and started happening again later on, it comes and goes. Thus, I'm not sure if it's also happening with today's snapshot.
![image](https://user-images.githubusercontent.com/71190696/116004764-dece3e80-a5c9-11eb-841f-16ee1dd6dffb.png)

Thank you for your work, hope I'm not being nitpicky.

**Comment by FredKruse** [comment] 2021-11-18 19:08
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:08 UTC
Labels: office-integration
