### ISSUE TITLE
suppress suggestions that cannot be synthesized

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#2787] opened 2020-04-22 11:08 UTC
Rules can be designed in a way that minimizes suggestions that cannot be synthesized. But it is impossible to ensure that it is always so. 

It would be useful to suppress optionally these suggestions in the same way we suppress misspelled suggestions with `suppress_misspelled="yes"`.

We could use the same attribute (`suppress_misspelled`) or another one, and suppress suggestions containing the characters `( )`.

**Comment by tiff** [comment] 2020-04-22 13:14
@jaumeortola here's a hacky trick (that's undocumented), I don't know if that works for Spanish too:

If you have the `<suggestion suppress_misspelled=yes>` within the `<message>` of the rule then it won't match if the suggestion could not be generated. See English rule `CD_NN` for example

**Comment by jaumeortola** [comment] 2020-04-22 17:02
Thank you. It doesn't seem to work. I will try to make it work even for suggestions outside the message.

**Comment by tiff** [comment] 2020-04-22 17:09
Thanks, looking forward to that.

**Comment by jaumeortola** [comment] 2020-04-23 06:46
I see what happens. The behavior is slightly unstable. `suppress_misspelled` can be an attribute of `<suggestion>` and attribute of `<match>`.

What would be the desired behavior? I think that sometimes we need to suppress the suggestions but not the rule match. Other times we want to suppress the rule match. 

I would do this:
- Use `suppress_misspelled` in `<message>` or in `<suggestion>` (inside or outside the message), not in `<match>`.
- When using it in `<suggestion>`, suppress the suggestion if any of the `<match>` elements in the suggestion cannot be synthesized. 
- When using it in `<message>`, suppress the rule match if there is no good suggestion.

Can we handle this change with the existing uses of `suppress_misspelled` (81 cases now in total)? (Some of them are meaningless. For example, in Portuguese `suppress_misspelled` & `regexp_replace` do nothing.)

What do you think? @danielnaber, @tiff.

**Comment by danielnaber** [comment] 2020-04-23 08:32
@jaumeortola Sounds good. However, any change might break current behavior, but we have tests for that. Also, the reason for the current bugs might also be the fact that the code is quite ugly and difficult to understand (e.g. `MatchState`). So it *might* be a good idea to first clean up the code and add more tests before changing behavior.

**Comment by jaumeortola** [comment] 2020-04-23 08:50
> So it _might_ be a good idea to first clean up the code and add more tests before changing behavior.

I will try to do that.  The code is certainly difficult to understand.

**Comment by tiff** [comment] 2020-04-23 08:52
@jaumeortola sounds good. This might also help with some of our French rules (ACCORD_NOMBRE, ACCORD_GENRE) where we often suggest words in parentheses.

**Comment by jaumeortola** [comment] 2020-04-24 09:12
I have implemented this with few changes in the code. All tests passed successfully with minor changes in grammar.xml files. 

Now the language maintainers can decide whether to suppress the suggestion or the rule match, for example in `en/grammar.xml` in `correction="many (18-year-old)"`. The option of suppressing only a `<match>` but not the entire `<suggestion>` will be not available because it makes no sense (e.g. `correction="many "` instead of `correction="many (18-year-old)"`) @MikeUnwalla 

What do I do now? Do I push the branch or make a pull request so that you can take a look?

Other comments:
There is a part of the code (`combineLists()` in `PatternRuleMatcher`) that I don't fully understand. It seems to be never used with `suppress_misspelled`.
There is a bug when in a suggestion with several synthesized matches, the first match has more than one result. In this case the suggestions are not well-formed. But it is an infrequent case.

**Comment by danielnaber** [comment] 2020-04-24 09:58
Thanks! I think a PR is a good idea. Maybe you could also run a regression test locally, e.g. run the command-line version on 10,000+ sentence before and after your change, and see if the diff looks okay.

**Comment by jaumeortola** [comment] 2020-04-24 10:14
>  e.g. run the command-line version on 10,000+ sentence before and after your change, and see if the diff looks okay.

I will do that in English, that is the language that uses `suppress_misspelled` the most. And some other language too?

**Comment by danielnaber** [comment] 2020-04-24 10:43
> And some other language too?

Doing it for EN, FR, DE, ES, NL, PT would be good.

**Comment by MikeUnwalla** [comment] 2020-04-24 11:59
@jaumeortola , thanks for your comment. I will change the suggestion in `en/grammar.xml`.

When all the changes are done, please update the documentation. "It is possible to conditionally suppress parts of suggestions if they are misspelled (for this, you need to use element match with attribute suppress_misspelled set to yes)." (http://wiki.languagetool.org/development-overview#toc6).

**Comment by jaumeortola** [comment] 2020-04-24 13:43
Making regression tests in English I found this differences (I will post more). In this rule (MANY_NN[1]), it seems reasonable to add `suppress_misspelled` to the message. But then there will be no rule match for "many 18-year-old" (Perhaps we need a specific rule for his kind of expressions). @MikeUnwalla: You decide what is the best solution. Don't do many changes to the rules because we'll have to solve conflicts later. 

```
+Message: Possible agreement error. The noun think seems to be countable; consider using: 'many (think)'.
+Suggestion: many (think)
 ...The expectations of Africans were great, but many think that the second term of President Obama will...
                                                 ^^^^^^^^^^
+Message: Possible agreement error. The noun think seems to be countable; consider using: 'many (think)'.
+Suggestion: many (think)
 ...e news immediately triggered online outrage; many think the university has violated student privacy ...
                                                 ^^^^^^^^^^
+Message: Possible agreement error. The noun Twitter seems to be countable; consider using: 'several (Twitter)'.
+Suggestion: several (Twitter)
 Today he has several Twitter and Facebook accounts managed by three Cabin...
              ^^^^^^^^^^^^^^^
-Suggestion: several 
+Message: Possible agreement error. The noun Roma seems to be countable; consider using: 'several (Roma)'.
+Suggestion: several (Roma)
 ... perpetrators of the cold-blooded murders of several Roma in Hungary.
                                                 ^^^^^^^^^^^^
```

**Comment by jaumeortola** [comment] 2020-04-24 15:18
The other differences in English are in the rule `POSSESSIVE_APOSTROPHE` and the words `clothes` and `Reuters`. 

The new code works as expected. There is no singular of the noun "clothes" and the suggestion is suppressed. In Reuters something strange happens. The synthesizer creates a singular form (reuter), but then the tagger doesn't recognize this form. Tagger and synthesizer dictionaries seem inconsistent. 

We only need to adjust the message this way:

```
<message>Apostrophe might be missing.</message>
<suggestion><match no="3"/>'</suggestion>
<suggestion suppress_misspelled="yes"><match no="3" postag="NN(P)?S" postag_regexp="yes" postag_replace="NN$1(:U.?)?" setpos="no"/>'s</suggestion>
<example correction="clothes'">Blank noise doing a <marker>clothes</marker> installation to say</example>
<example correction="Reuters'">including a <marker>Reuters</marker> photographer Gleb Garanich</example>
```

I expect to find the same kind of minor issues in the other languages. I can make these changes myself. But afterwards the maintainers should check them.

**Comment by MikeUnwalla** [comment] 2020-04-25 08:00
@jaumeortola , now, I will correct the FP for MANY_NN and POSSESSIVE_APOSTROPHE .

**Comment by MikeUnwalla** [comment] 2020-04-25 09:34
@jaumeortola , for now, I won't use `suppress_misspelled` in the message:

1. If we hide unwanted suggestions, we won't find spelling errors and missing POS (Roma, Tuscarora)
2. `testrules,bat` gives this error message:
```
Running XML validation for en/grammar.xml...
cvc-complex-type.3.2.2: Attribute 'suppress_misspelled' is not allowed to appear in element 'message'. Problem found at line 34271, column 48.
Exception in thread "main" java.io.IOException: Cannot load or parse '/org/languagetool/rules/en/grammar.xml'
```

**Comment by MikeUnwalla** [comment] 2020-04-25 09:42
@jaumeortola , MANY_NN now has this correction: `<example correction="many (18-year-old)">`

Why doesn't the rule suggests "many 18-year-olds"?

**Comment by MikeUnwalla** [comment] 2020-04-25 09:57
@jaumeortola , when I add your code to POSSESSIVE_APOSTROPHE, testrules gives this message:

```
Exception in thread "main" org.junit.internal.runners.model.MultipleFailureException: There were 2 errors:
  org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure(Test failure for rule POSSESSIVE_APOSTROPHE[2] in file /org/languagetool/rules/en/grammar.xml: Blank noise doing a clothes installation to say"
Errors expected: 1
Errors found   : 0
Message: Apostrophe might be missing.<pleasespellme/>
Analyzed token readings: [/SENT_START*] Blank[Blank/NNP*,blank/JJ*,blank/NN:UN*,blank/VB*,blank/VBP*,B-NP-singular]  [ /null*] noise[noise/NN:UN,E-NP-singular]  [ /null*] doing[doing/NN:UN,do/VBG,B-VP]  [ /null*] a[a/DT,B-NP-plural]  [ /null*] clothes[clothes/NNS,I-NP-plural]  [ /null*] installation[installation/NN:UN,E-NP-plural]  [ /null*] to[to/IN,to/TO,B-VP]  [ /null*] say[say/JJ,say/NN,say/VB,say/VBP,say/SENT_END,I-VP]
Matches: [])
  org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure(Test failure for rule POSSESSIVE_APOSTROPHE[2] in file /org/languagetool/rules/en/grammar.xml: including a Reuters photographer Gleb Garanich"
Errors expected: 1
Errors found   : 0
Message: Apostrophe might be missing.<pleasespellme/>
Analyzed token readings: [/SENT_START*] including[including/IN*,include/VBG*,B-PP]  [ /null*] a[a/DT,B-NP-singular]  [ /null*] Reuters[Reuter/NNPS,I-NP-singular]  [ /null*] photographer[photographer/NN,I-NP-singular]  [ /null*] Gleb[Gleb/null,I-NP-singular]  [ /null*] Garanich[Garanich/SENT_END,E-NP-singular]
Matches: [])
```

So, I will leave POSSESSIVE_APOSTROPHE for you to deal with.

**Comment by jaumeortola** [comment] 2020-04-25 12:09
> Why doesn't the rule suggests "many 18-year-olds"?

The rule tries to synthesize the plural of "18-year-old" using the synthesis dictionary, but there is not such a word in the dictionary. We need to write a new rule if we want to give the right suggestion.

**Comment by jaumeortola** [comment] 2020-04-25 12:11
@MikeUnwalla My changes are not yet in the master branch. I will make tests in other languages, and then I will make a pull request.

**Comment by MikeUnwalla** [comment] 2020-04-25 12:41
@jaumeortola , thank you for your clarifications.

**Comment by jaumeortola** [comment] 2020-04-25 12:56
> for now, I won't use `suppress_misspelled` in the message:
> 
>     1. If we hide unwanted suggestions, we won't find spelling errors and missing POS (Roma, Tuscarora)

That seems a good idea. Perhaps we should disable `suppress_misspelled` in the message always when testing.

**Comment by jaumeortola** [comment] 2020-04-25 15:54
I didn't find issues in the other languages. Just one probable false alarm in English: 

```
+Rule ID: CD_NN[1]
+Message: Possible agreement error. The noun 'mph' seems to be countable, so consider using: .
+The speedometer was indicating 95 mph. 
+                                  ^^^ 
 ```

**Comment by jaumeortola** [comment] 2020-04-27 10:03
Fixed here: https://github.com/languagetool-org/languagetool/commit/666e61ad0cc1e1900221cac2a3e92e66bef40191 and following. 
I will document the changes in the wiki.

**Comment by jaumeortola** [comment] 2020-04-27 10:13
Documented here: http://wiki.languagetool.org/development-overview#toc6

**Comment by tiff** [comment] 2020-04-28 06:44
@jaumeortola @MikeUnwalla there are quite a few false alarms in the recent nightly regression test:
https://internal1.languagetool.org/regression-tests/20200427/result_en_20200427.html

Could you have a look?

**Comment by MikeUnwalla** [comment] 2020-04-28 07:26
@jaumeortola , I will deal with the false alarms that are caused by units of measurement and abbreviations (m2, vols and so on).

**Comment by jaumeortola** [comment] 2020-04-28 07:27
Possible fixes:
SUPERLATIVE_THAN: move suppress_misspelled to message
THERE_RE_MANY: move suppress_misspelled to message
CD_NN: fix the tags of some words or move suppress_misspelled to message

In POSSESSIVE_APOSTROPHE I moved the suggestions outside the message. If there are suggestions that can be suppressed, we could get a message like "Did you mean '' or ''?" with empty suggestions. Previously, in these cases the rule match was suppressed.

**Comment by tiff** [comment] 2020-04-28 07:28
I'm reopening this issue, feel free to close when false alarms have been handled

**Comment by jaumeortola** [comment] 2020-04-28 08:47
As said before, suppressing messages can be good for production but bad for testing and development. It would be useful to have some kind of "testing mode" where rule matches are never suppressed.

**Comment by MikeUnwalla** [comment] 2020-04-28 09:05
@jaumeortola , @tiff , the errors in THERE_RE_MANY and CD_NN are now fixed.

**Comment by tiff** [comment] 2020-04-28 09:07
Ok, let's wait a few days, collect data and then set "suppress_misspelled" if necessary on "SUPERLATIVE_THAN" and "THERE_RE_MANY" as @jaumeortola suggested. I will assign myself to this.

**Comment by jaumeortola** [comment] 2020-04-28 10:26
Another general idea. Using `suppress_misspelled` in suggestions inside the message (but not in the message element) can result in malformed messages like `Did you mean '' or ''?`. It would be advisable to make a warning against this use in some way. How can you do it? A warning in tests?

**Comment by danielnaber** [comment] 2020-04-28 11:14
> A warning in tests?

Test warnings tend to be ignored... but is making the test fail a better solution? What would the rule editor do on this warning, move the `<suggestion>` out of the `<message>`?

**Comment by jaumeortola** [comment] 2020-04-28 11:27
>  but is making the test fail a better solution?

Yes, that solution is fine: do not allow `suppress_misspelled` in suggestions inside the message. 

> What would the rule editor do on this warning, move the `<suggestion>` out of the `<message>`?
1. move the `<suggestion>` out of the `<message>`, or
2. add `suppress_misspelled` to the message

**Closed** 2023-06-20 15:58 UTC
