### ISSUE TITLE
[en] False warning DO_YOU_WHAT

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3596] opened 2020-09-18 14:50 UTC
DO_YOU_WHAT suggest that a verb is missing:

> I do **them when** I think they are needed.

**Comment by SkyCharger001** [comment] 2020-09-19 19:29
seems to be caused by a missing comma.

**Comment by tiff** [comment] 2020-09-21 08:23
Fixed via https://github.com/languagetool-org/languagetool/commit/88d14a0d68f1219d17380d526f4d7cfea73d9866

**Closed by tiff** 2020-09-21 08:23 UTC
Labels: English, bug
