### ISSUE TITLE
Word 'lockbox' is not recognised by JlanguageTool

### ISSUE THREAD

**Issue by santosh-09** [languagetool-org/languagetool#871] opened 2018-01-03 08:51 UTC
When trying to validate the input text using JLanguageTool, I see a rule fails for the word 'lockbox'.  This word is a valid word in Oxford and Merriam dictionary. I also tried passing different languages to JLanguageTool (new AmericanEnglish(), new BritishEnglish()..etc..), but nothing works.
**Code:**
JLanguageTool testTool = new JLanguageTool(new AmericanEnglish());
List<RuleMatch> matches = testTool.check("lockbox");
**Output:**
[MORFOLOGIK_RULE_EN_US:0-7:Possible spelling mistake found].

Please look into it.

**Regards**,
Santosh

**Comment by danielnaber** [comment] 2018-01-03 09:15
Thanks for the report. I cannot reproduce it, but I get an error because the "sentence" doesn't start with an uppercase word. `check()` works on sentences and not on single words. Does `testTool.check("A lockbox")` work for you? Which version of LT are you using?

**Comment by santosh-09** [comment] 2018-01-03 10:30
Thank you for the quick reply.LT version used is 3.7. Now I tried 4.0 and it works fine for testTool.check(“Lockbox”), But if the String starts with lowercase i.e. “lockbox”, it fails with the error you mentioned below. For both cases (lower & upper) it also fails for version 3.9.
In our scenario, most of the times upper case will be passed.

**Comment by danielnaber** [comment] 2018-01-03 10:50
Okay, so I'm closing this as the behavior of LT 4.0 seems to be okay.

**Closed by danielnaber** 2018-01-03 10:50 UTC
