### ISSUE TITLE
LT plugin slow for long text with contenteditable

### ISSUE THREAD

**Issue by rezaffm** [languagetool-org/languagetool#6163] opened 2021-12-18 07:38 UTC
Hi guys,
I got a premium version of LT as I really love it and it improved my writing in EN and DE.
I recently migrated my WYSIWYG editor from tinymce to tiptap, based on prosemirror. Tiptap and LanguageTool is a dream team for me.

Prosemirror itself uses contenteditable.

Here is the problem:

Once I write more than 1.500-2.000 words I noticed that writing gets some kind of laggy, still works, but not a pleasure. Maybe just an observation but I also noticed that the further down the text I write, the more laggy it is.

I don’t have similar issues writing in Gdoc as there LanguageTool plugin is split over pages, something tiptap doesn’t provide.

Implementing words pagination would be out of scope for the guys at tiptap and also not sure if that would be the right solution.

As far as I could understand when I type the LanguageTool Plugin (both on Firefox and chrome) runs immediately on every input.

I presume that this slows it down, the bigger the text gets. Such issues I usually solve with some debouncing and throttling - however, I have no idea how to do that with the LanguageTool Plugin.

Maybe, a potential solution could be to make the Plugin more clever.

So, when the plugin realizes it is long text (> 1.000 words) it starts to throttle with 500ms, then 1 second and so on.

This is just an idea… If this is already a well-known thing and you have a solution please tell me :-)

And thanks again for this great tool, it helped us a lot.

**Comment by danielnaber** [comment] 2021-12-18 09:50
Thanks for the report. Is there a page where we can reproduce this?

**Comment by rezaffm** [comment] 2021-12-18 11:32
I can provide a sandbox with da realistic text that includes some images, more complex html structures, lists er cetera if that helps?

**Comment by danielnaber** [comment] 2021-12-18 11:43
That might help. Please keep the content as simple as possible to still reproduce the issue.

**Comment by rezaffm** [comment] 2021-12-18 14:30
Sure, I won’t overdue it - Apparently I can already show the issue with just plain text. I will use German as language.

**Comment by rezaffm** [comment] 2021-12-18 18:06
Hi, while setting up the sandbox, I noticed it is a good idea to "debounce" also the word count function from the editor. I am uncertain if this did the trick, actually. Could it be that at certain times, the LanguageTool Server is faster/slower? I need to observe this issue during the next days and if laggs will come back again, I would share the sandbox with you.

**Comment by rezaffm** [comment] 2021-12-18 18:34
Okay, I tested it again, also in the sandbox and the laggs are back again. Here is the sandbox: https://codesandbox.io/s/editor-sandbox-pj3ki and when you copy from here 3400 words and 99 paragraphs that will come close to the text I have written: https://www.blindtextgenerator.de/

As soon as I switch off LanguageTool Plugin, everything works fine. (Please note there are some issues with Chrome and contenteditable textes when spellcheck is on, so rather use Firefox or another browser of your choice).

**Comment by rezaffm** [comment] 2021-12-18 18:56
...and maybe aother weird observation: When I work on ubuntu (Ubuntu 20.04.3 LTS) there seems to be also no laggs at all vs. Windows.

**Comment by tiff** [comment] 2021-12-19 16:52
On Mac, I'm unable to reproduce this with both Chrome and Firefox. Do you have any other plugins installed on your Windows machine?

**Comment by tiff** [comment] 2021-12-19 16:58
... and on Windows, does it happen both with Chrome and FF?

**Comment by rezaffm** [comment] 2021-12-19 17:46
Hi, I have been playing around with this. The issue appears especially when there are a lot of suggestions and errors. It is a bid difficult to show - but I will try to provide an example. It normally laggs in Firefox and chrome. Same on Ubuntu, windows and Mac :-)

**Comment by rezaffm** [comment] 2021-12-19 18:39
Hi,

I copied a text from the mentioned link with 3,400 words and included some typos.

In general, the more typos, errors, suggestions you include, the more laggier the whole editor becomes.

You can see the effect specially, when you keep a letter on your keyboard pressed, such as "f" or whatever.

**Here is the text you can copy into the editor to see the effect yourself:**

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns untrzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, eien Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Shmerz an sich liebt, scht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns untrzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Scmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Scherz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer vn uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und chmerz ihm große Freude bereiten können.

Um ein triviales Beipiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denenMühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstregender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmez vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm groe Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der de Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengeder körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, wecher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Sschmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ih große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmrz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je astrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je antrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermedet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Shmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die ntscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Müen und Schmerz ihm grosse Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trift, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht ein, einen Menschen zu tadel, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, such oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerzen vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, suct oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wüncht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstregender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, eien Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht der wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu geniessen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstregender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, dr die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trift, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrenender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht? Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen? Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Scherz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?

Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmez ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?

Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einn, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht? Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können.

Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen? Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entcheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen ht, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht? Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, auße

**Comment by rezaffm** [comment] 2021-12-19 19:08
Hi,

I checked in Google Chrome extensions what happens, when I initially copy the text into the editor.

I see 6 requestes are fired, basically the text is chunked in several parts which makes a lot of sense.

I then did the following.

At the bottom I kept the "." button my keyboard pressed to see whats happening, I kept it pressed until two lines were full of "."s.

This lead to 16 fetch requestes fired, it's always the same two requests, one with the dots as data and the other one with, I believe it's the beginning of the whole text (not sure).

Anyhow, am I correct that no debouncing or throttling was implemented?

That's a bit of a surprise to me actually :-) in UX terms a 500ms debounce/throttle is the de factor, not only to avoid laggs and poor user experience but also to prevent unneccessary requests to the server.

In Javascript that's not a big deal (https://schier.co/blog/wait-for-user-to-stop-typing-using-javascript) - but I believe it shouldnt be too much of an issue in Java too.

If you don't like the idea ot debouncing/throttling, maybe you could make the Plugin a bit more clever. As I initially said, for short textes < 500 words no debouncing/throttling and then you increase the time.

However, I don't see any good reason why not implenting at least a 200ms-300ms debounce in general, it's also much better for overall server performance.

Let me know what you think.

![image](https://user-images.githubusercontent.com/40648929/146687530-42bc825d-0320-49ef-be96-214762e4bf3a.png)

**Comment by tiff** [comment] 2021-12-20 09:42
Thanks for providing these details. I will have a closer look in the next days.
There's a lot of throttling happening regarding when and how to send requests. However, for the repositioning of the underlines, we have to do it instantly. Otherwise, you will have incorrectly positioned underlines while you type which can be quite annoying.

**Comment by tiff** [comment] 2021-12-22 10:39
@rezaffm thanks for providing all these details. I had a closer look:
It seems that the performance issues are especially critical when checking the text in that specific text field (https://codesandbox.io/s/editor-sandbox-pj3ki).
I copied the text you sent me via email into this [alternative rich-text editor](https://fiddle.tiny.cloud/) and there it seems fine (still a tiny bit laggy but much better). Can you confirm?

**Comment by rezaffm** [comment] 2021-12-22 12:59
Hi, well, we know tinymce as we used to work with it and replaced it with tiptap editor, as extension development is easier and also it integrates vue, react et cetera very well. I can confirm what you wrote, as initially mentioned, the issue is relevant for contenteditable fields :-) (tiptap i based on contetenteditable whereas tinymce is not)

I believe the only solution would be to come up with something like this: https://www.tiny.cloud/tinymce/features/spell-checker-pro **for LanguageTool** - as the only way I see to get rid of the laggs is to debounce the server calls - which, from what I understood, is something the plugin cant provide without funky underlines, correct?

On your website you demontrated well how something like this could look like actually: https://languagetool.org/editor

**Comment by tiff** [comment] 2021-12-22 13:07
Thanks for re-checking.

* Please note that TinyMCE and our own editor are based on contenteditable as well
* We are now checking what exactly is the reason why this happens with "tiptap" and not with other contenteditable editors
* Debouncing or delaying server calls, which is already the case and which happens async, will not make it faster (the bottleneck here is the reparsing of the text on every keystroke)

**Comment by rezaffm** [comment] 2021-12-22 13:20
Oh okay, I see, back then we still used tinyMCE 4 so good to know they caught up and are now using contenteditable.

Your editor also works without the plugin as far as I noticed, so that's why I want to come up with an own extension.

Unfortunately, I cannot tell why it is happening with tiptap and not the other editors, maybe the guys at tiptap can help [@Philipp](https://github.com/philippkuehn) or https://github.com/hanspagel

But maybe this is helpful for you:

https://discuss.prosemirror.net/t/very-long-delay-between-textinput-and-input-events/3679/6

Chrome has many issues with tiptap / Prosemirror when spell checking is on. The issue was recently solved, but kind of re-introduced with Chrome 97.

Did you also test with e.g. firefox or safari?

**Comment by rezaffm** [comment] 2021-12-22 13:29
One more thing, in the sandbox I provided, you see the following code:

```javascript
      /*editorProps: {
        attributes: {
          spellcheck: "true",
        },
      },*/
```

If you uncomment and set spellcheck to false, lagging stops immediately - worth noticing that it not only lags with LT plugin, but also with native spell checking of Chrome.

Actually, I have to disable native spell checking in Chrome, otherwise I cannot write at all, having the LT plugin activated.

As you see, I spent some time with this issue and couldn't find any solution at all.

**Comment by tiff** [comment] 2021-12-29 11:32
We have identified the performance issue happening with Tiptap/ProseMirror editors and a fix will be released over the next weeks.

**Closed by tiff** 2021-12-29 11:32 UTC
Labels: browser-add-on

**Comment by rezaffm** [comment] 2021-12-29 11:35
Hi, thank you, we also started to develop a custom extension for tiptap (got inspired by your editor actually) and also good to know that you are working on a solution for the extension. If you don't mind, what's the exact issue happening with TipTap/ProseMirror editors?

**Comment by tiff** [comment] 2021-12-29 15:01
Unlike other editors, ProseMirror was constantly changing the class name of the parent editing element on every keystroke, which invalidated our DOM node cache.

**Comment by rezaffm** [comment] 2021-12-29 15:09
Oh cool that you figured that out. Personally I really appreciate LT and  best of luck to you and the rest of the team members in 2022.

**Comment by Xyncgas** [comment] 2023-08-16 06:12
it still lags with 200k CJK characters, perhaps we should file a bug to chrome & mozilla
