### ISSUE TITLE
Word Split breaks in docs with weird margians

### ISSUE THREAD

**Issue by Rdna123** [languagetool-org/languagetool#4661] opened 2021-03-23 23:10 UTC
Split 'cat' and 'in' using language tools to show: [Google Doc with Error](https://docs.google.com/document/d/1mn8i0a_twOA5dJVsa1NVtznkvbflwlx3oqr7GL1Upnk/edit?usp=sharing)

e.i. turns "The catin the hat" to "Thecat in the hat"

**Comment by danielnaber** [comment] 2021-03-24 06:51
Thanks for the report. I cannot reproduce that, could you send screenshots or a screencast? Which browser do you use?

**Comment by tiff** [comment] 2021-03-24 08:58
I can reproduce it.

**Comment by tiff** [comment] 2021-03-24 09:02
It happens when the browser is zoomed in. @Rdna123 can you confirm?

**Comment by Rdna123** [comment] 2021-03-24 09:37
My browser is at 100% view both browser and google doc.

**Comment by tiff** [comment] 2021-04-01 06:36
@Rdna123 which browser are you using?

**Comment by Rdna123** [comment] 2021-04-01 06:37
I am using Google Chrome

**Comment by tiff** [comment] 2021-04-01 06:39
Yesterday we have released a new version of our Chrome extension with a few fixes concerning Google Docs.
Could you re-check? For this, you would need to uninstall and re-install the extension here (otherwise it will take days to weeks until the new version reaches your computer):
https://chrome.google.com/webstore/detail/grammar-and-spell-checker/oldceeleldhonbafppcapldpdifcinji

**Comment by Rdna123** [comment] 2021-04-01 07:09
@tiff I am unable to check till the end of spring break

**Comment by danielnaber** [comment] 2023-01-01 20:26
Closing, as there was no reply

**Closed by danielnaber** 2023-01-01 20:26 UTC
Labels: browser-add-on
