### ISSUE TITLE
Missing replacement suggestions ?!

### ISSUE THREAD

**Issue by robert-hoffmann** [languagetool-org/languagetool#850] opened 2017-11-28 15:02 UTC
I like the idea and tooling behind languagetool, but as far as replacements go ..where are they ?

It seems like languagetool proposes even less replacements than the default spell checkers integrated into our browsers (which are all based on hunspell too, like languagetool) ..yet it manages to find more "potential" errors than them, but only talks about why "maybe" something is wrong, without actually proposing a fix.

Am i missing something ?
Thanks !

**Comment by danielnaber** [comment] 2017-11-28 15:05
How are you using LT? The API, the website, an add-on? Can you provide an example error without suggestions?

**Comment by robert-hoffmann** [comment] 2017-11-28 15:25
Tested on website, via navigator plugin, and local server : results are at least consistent :-)

You can compare with native browser suggestions, and this one which gives a pretty complete rundown of the errors found: http://www.cordial-enligne.fr/indexLarousse.php

Thanks !

Test text (with errors) taken from a website that compared multiple tools including languagetool :
> La porte s’entr’ouvre, une main jette quelque chose et une lumière scialitique baignent la pièce. Dominique fait feux au travers du bâtant. Un cri de souffrance répond à la détonnation.
> 
> Très vite elle se colle dos au mûr de droite. Le battant est plaquer contre la cloison par un grand coup de pieds, un homme trapue entre sans prècipitation, avec un petit sot de côté tout à fait dérisoire ; il lève le museau de son pistolet mitrailleur vert le lit et… n’a pas le loisir de faire la moindre grimaces de surprise, la lame de couteau s’enfonce jusqu’à la garde sous son menton.
> 
> Dominique ponctue son cou mortel d’une cri inouie, un hurlement de bête. De l’autre nain elle tire deux bales dans l’escalier. Mouche : d’autres cris. Puis des hurlements d’enfants. Une raffale déchire le sommier entre mes jambes et se paire contre le mur.

And errors that correspond to the text:
![image](https://user-images.githubusercontent.com/5472296/33327386-a7ca898a-d457-11e7-98e4-eba723dbfa9a.png)

**Comment by robert-hoffmann** [comment] 2017-11-28 15:31
I've been testing this for one of the biggest supermarket chains in france, right now LT, Cordial, and Prolexis are the only ones i found to seem to be any good, but the lack of replacement suggestions is a bit preoccupying. LT is the only open-source project in our current short-list

**Comment by danielnaber** [comment] 2017-11-28 15:35
Yes, there are no suggestions for French (unlike for most languages), see the "spelling column" on https://languagetool.org/languages/. It's probably less than one day of work, but someone would have to do it.

**Comment by robert-hoffmann** [comment] 2017-11-28 16:12
I did get "some" very limited suggestions for some stuff with an older text, but not with this new text.

Really a shame, hope someone does do it ..especially if it's not a lot of work. Then again if it's so simple, it would have probably already been done. But this makes LT kinda unusable in languages that don't do suggestions ..the user just knows something "might" be wrong, but will have to dig around himself to figure out what it is.

Thanks for your help and clarification

**Comment by robert-hoffmann** [comment] 2017-11-28 16:25
btw, is this a LT problem or with the dictionaries ? I suppose LT, since most browsers use hunspell too and give replacement suggestions ?

**Comment by robert-hoffmann** [comment] 2017-11-28 16:46
Sure i can mail you (..where ? ^^)

I saw you have LT Plus .. honestly if you can get the other languages working ..even just up to browser level replacement suggestions, you have a good tool that can compete with some of the big ones like : yahoo api / bing api ..is even worse than LT (at least in french !)

**Comment by danielnaber** [comment] 2017-11-28 16:47
You can find my email at https://languagetool.org/legal/

**Comment by danielnaber** [comment] 2017-11-28 20:50
I've created a version of LT with suggestions for French at http://danielnaber.de/tmp/LanguageTool-4.0-SNAPSHOT-20171128-fr-spelling.zip, could you test that? I've used https://gist.github.com/danielnaber/fd20cff8d86a4608c22143dcf1fe62b0, which is based on `create_dict.sh` in our github repo. Other than that, a class `MorfologikFrenchSpellerRule` and `fr_FR.info` needed to be created but that's basically it.

**Comment by robert-hoffmann** [comment] 2017-11-28 21:40
Sounds great, thanks, i'll download it and try it on the demo server i set up at work tomorrow !

**Comment by robert-hoffmann** [comment] 2017-11-29 08:52
Hi,

Just gave it a try. Much better !

Here are some problems i see so far:
- seems like it catches some other odd stuff like spaces ` `, apostrophes like the `l'` et the beginning of `l'escalier`, and ` : `
- it seems like it can't tell the difference between suggesting the capital or lowercase version of a word, and proposes both
- some words like `inouie` trigger weird behavior, .

![image](https://user-images.githubusercontent.com/5472296/33365939-1ca07c32-d4ea-11e7-8ae6-d28447b86a86.png)

![image](https://user-images.githubusercontent.com/5472296/33366131-a13643c8-d4ea-11e7-9674-bd565cf30660.png)

**Comment by danielnaber** [comment] 2017-11-29 09:14
> seems like it catches some other odd stuff like spaces

Are you sure this didn't happen before? Maybe it's a special character and not a normal space character?

**Comment by danielnaber** [comment] 2017-11-29 10:09
> some words like inouie trigger weird behavior

You mean the large number of suggestions? I've just fixed that, it seems for some languages there was simply no limit in the stand-alone UI.

**Comment by danielnaber** [comment] 2017-11-29 10:22
> it seems like it can't tell the difference between suggesting the capital or lowercase version of a word, and proposes both

This seems to be a special case, it's caused by `fsa.dict.speller.replacement-pairs` containing `ll l`. It might be a bug(?) in Morfologik.

**Comment by robert-hoffmann** [comment] 2017-11-29 10:31
No it's not special characters, i'm still using the same sample text in my 2nd post, just normal white spaces.

Try the text, it was written by a french grammar specialist for the comparison of multiple spell checkers

**Comment by robert-hoffmann** [comment] 2017-11-29 10:44
In green are errors with suggestions, red are errors with explanations

![image](https://user-images.githubusercontent.com/5472296/33371297-8e69f504-d4fa-11e7-94ec-99edf1566472.png)

**Comment by danielnaber** [comment] 2017-11-29 10:44
At least the space error at `l'escalier` I cannot reproduce. I use this command: `java -jar languagetool-commandline.jar -l fr test.txt` with `test.txt` being your text from above. Can you also reproduce the issue with the command line version? Or with the web service, could you get the exact JSON output for that error?

**Comment by robert-hoffmann** [comment] 2017-11-29 11:08
Ok, it might be my richtextbox that's doing some crazy stuff :  i replaced all double spaces with single spaces before launching a check and now get this

![image](https://user-images.githubusercontent.com/5472296/33371894-73b7336e-d4fc-11e7-889a-ae252cc658b4.png)

And the response

```json
{
	" software ": {
		" name ": " LanguageTool ",
		" version ": " 4.0 - SNAPSHOT ",
		" buildDate ": " 2017 - 11 - 28 20: 18 ",
		" apiVersion ": 1,
		" status ": " "
	},
	" warnings ": {
		" incompleteResults ": false
	},
	" language ": {
		" name ": " French ",
		" code ": " fr "
	},
	" matches ": [{
			" message ": " Faute de frappe possible trouvée ",
			" shortMessage ": " Faute de frappe ",
			" replacements ": [{
					" value ": " entre "
				}, {
					" value ": " enter "
				}, {
					" value ": " en tr "
				}
			],
			" offset ": 11,
			" length ": 4,
			" context ": {
				" text ": " La porte s’entr’ouvre, une main jette quelque chose et...",
				" offset ": 11,
				" length ": 4
			},
			" rule ": {
				" id ": " MORFOLOGIK_RULE_FR_FR ",
				" description ": " Faute de frappe possible ",
				" issueType ": " misspelling ",
				" category ": {
					" id ": " TYPOS ",
					" name ": " Faute de frappe possible "
				}
			}
		}, {
			" message ": " Faute de frappe possible trouvée ",
			" shortMessage ": " Faute de frappe ",
			" replacements ": [{
					" value ": " scialytique "
				}
			],
			" offset ": 67,
			" length ": 11,
			" context ": {
				" text ": "...main jette quelque chose et une lumière scialitique baignent la pièce.Dominique fait feux...",
				" offset ": 43,
				" length ": 11
			},
			" rule ": {
				" id ": " MORFOLOGIK_RULE_FR_FR ",
				" description ": " Faute de frappe possible ",
				" issueType ": " misspelling ",
				" category ": {
					" id ": " TYPOS ",
					" name ": " Faute de frappe possible "
				}
			}
		}, {
			" message ": " Incohérence : « du » ne peut pas se trouver devant « bâtant ».",
			" shortMessage ": " ",
			" replacements ": [],
			" offset ": 129,
			" length ": 9,
			" context ": {
				" text ": "...a pièce.Dominique fait feux au travers du bâtant.Un cri de souffrance répond à la déton...",
				" offset ": 43,
				" length ": 9
			},
			" rule ": {
				" id ": " DU_LE ",
				" subId ": " 1 ",
				" description ": " du le ",
				" issueType ": " uncategorized ",
				" category ": {
					" id ": " CAT_GRAMMAIRE ",
					" name ": " Grammaire "
				}
			}
		}, {
			" message ": " Faute de frappe possible trouvée ",
			" shortMessage ": " Faute de frappe ",
			" replacements ": [{
					" value ": " intonation "
				}
			],
			" offset ": 173,
			" length ": 11,
			" context ": {
				" text ": "...âtant.Un cri de souffrance répond à la détonnation.Très vite elle se colle dos au mûr de...",
				" offset ": 43,
				" length ": 11
			},
			" rule ": {
				" id ": " MORFOLOGIK_RULE_FR_FR ",
				" description ": " Faute de frappe possible ",
				" issueType ": " misspelling ",
				" category ": {
					" id ": " TYPOS ",
					" name ": " Faute de frappe possible "
				}
			}
		}, {
			" message ": " Après l’auxiliaire « est », le verbe devrait être au participe passé.",
			" shortMessage ": " ",
			" replacements ": [],
			" offset ": 248,
			" length ": 7,
			" context ": {
				" text ": "...le dos au mûr de droite.Le battant est plaquer contre la cloison par un grand coup de...",
				" offset ": 43,
				" length ": 7
			},
			" rule ": {
				" id ": " AUX_ETRE_VCONJ ",
				" subId ": " 1 ",
				" description ": " Auxiliaire suivi d’un verbe conjugué ",
				" issueType ": " uncategorized ",
				" category ": {
					" id ": " CAT_GRAMMAIRE ",
					" name ": " Grammaire "
				}
			}
		}, {
			" message ": " « homme » et « trapue » ne semblent pas bien accordés en genre.",
			" shortMessage ": " ",
			" replacements ": [],
			" offset ": 305,
			" length ": 12,
			" context ": {
				" text ": "...cloison par un grand coup de pieds, un homme trapue entre sans prècipitation, avec un petit...",
				" offset ": 43,
				" length ": 12
			},
			" rule ": {
				" id ": " ACCORD_GENRE ",
				" subId ": " 2 ",
				" description ": " nom masculin suivi du féminin ",
				" issueType ": " uncategorized ",
				" category ": {
					" id ": " CAT_GRAMMAIRE ",
					" name ": " Grammaire "
				}
			}
		}, {
			" message ": " Faute de frappe possible trouvée ",
			" shortMessage ": " Faute de frappe ",
			" replacements ": [],
			" offset ": 329,
			" length ": 13,
			" context ": {
				" text ": "...up de pieds, un homme trapue entre sans prècipitation, avec un petit sot de côté tout à fait...",
				" offset ": 43,
				" length ": 13
			},
			" rule ": {
				" id ": " MORFOLOGIK_RULE_FR_FR ",
				" description ": " Faute de frappe possible ",
				" issueType ": " misspelling ",
				" category ": {
					" id ": " TYPOS ",
					" name ": " Faute de frappe possible "
				}
			}
		}, {
			" message ": " Point - virgule est précédé d 'une espace fine insécable.",
			"shortMessage": "Insérer un espace insécable",
			"replacements": [{
					"value": " ;"
				}
			],
			"offset": 391,
			"length": 2,
			"context": {
				"text": "... petit sot de côté tout à fait dérisoire ; il lève le museau de son pistolet mitra...",
				"offset": 43,
				"length": 2
			},
			"rule": {
				"id": "FRENCH_WHITESPACE",
				"description": "Insertion des espaces fines insécables",
				"issueType": "uncategorized",
				"category": {
					"id": "MISC",
					"name": "Règles de base"
				}
			}
		}, {
			"message": "Cette phrase ne commence pas par une majuscule",
			"shortMessage": "",
			"replacements": [{
					"value": "N"
				}
			],
			"offset": 456,
			"length": 1,
			"context": {
				"text": "...on pistolet mitrailleur vert le lit et… n’a pas le loisir de faire la moindre gri...",
				"offset": 43,
				"length": 1
			},
			"rule": {
				"id": "UPPERCASE_SENTENCE_START",
				"description": "Absence de majuscule en début de phrase",
				"issueType": "typographical",
				"category": {
					"id": "CASING",
					"name": "Majuscules"
				}
			}
		}, {
			"message": "Le verbe « a » devrait être à l’impératif.",
			"shortMessage": "",
			"replacements": [],
			"offset": 458,
			"length": 1,
			"context": {
				"text": "... pistolet mitrailleur vert le lit et… n’a pas le loisir de faire la moindre grima...",
				"offset": 43,
				"length": 1
			},
			"rule": {
				"id": "NE_IMP_PAS",
				"subId": "1",
				"description": "Ne + impératif + pas",
				"issueType": "uncategorized",
				"category": {
					"id": "CAT_GRAMMAIRE",
					"name": "Grammaire"
				}
			}
		}, {
			"message": "« une » et « cri » ne semblent pas bien accordés en genre.",
			"shortMessage": "",
			"replacements": [],
			"offset": 615,
			"length": 7,
			"context": {
				"text": "...on.  Dominique ponctue son cou mortel d’une cri inouie, un hurlement de bête. De l’autr...",
				"offset": 43,
				"length": 7
			},
			"rule": {
				"id": "ACCORD_GENRE",
				"subId": "3",
				"description": "féminin suivi du masculin",
				"issueType": "uncategorized",
				"category": {
					"id": "CAT_GRAMMAIRE",
					"name": "Grammaire"
				}
			}
		}, {
			"message": "Faute de frappe possible trouvée",
			"shortMessage": "Faute de frappe",
			"replacements": [{
					"value": "induit"
				}, {
					"value": "induire"
				}, {
					"value": "ironie"
				}, {
					"value": "noue"
				}, {
					"value": "injure"
				}, {
					"value": "incube"
				}, {
					"value": "indue"
				}, {
					"value": "anomie"
				}, {
					"value": "indusie"
				}, {
					"value": "infuse"
				}, {
					"value": "anoure"
				}, {
					"value": "incurie"
				}, {
					"value": "induvie"
				}, {
					"value": "inule"
				}, {
					"value": "anoxie"
				}, {
					"value": "binouze"
				}, {
					"value": "gnosie"
				}, {
					"value": "incuite"
				}, {
					"value": "incuse"
				}, {
					"value": "indoue"
				}, {
					"value": "infule"
				}, {
					"value": "inuite"
				}
			],
			"offset": 623,
			"length": 6,
			"context": {
				"text": "...inique ponctue son cou mortel d’une cri inouie, un hurlement de bête. De l’autre nain ...",
				"offset": 43,
				"length": 6
			},
			"rule": {
				"id": "MORFOLOGIK_RULE_FR_FR",
				"description": "Faute de frappe possible",
				"issueType": "misspelling",
				"category": {
					"id": "TYPOS",
					"name": "Faute de frappe possible"
				}
			}
		}, {
			"message": "Faute de frappe possible trouvée",
			"shortMessage": "Faute de frappe",
			"replacements": [{
					"value": "balle"
				}, {
					"value": "ballet"
				}, {
					"value": "baller"
				}, {
					"value": "Galles"
				}, {
					"value": "ba les"
				}, {
					"value": "bal es"
				}
			],
			"offset": 684,
			"length": 5,
			"context": {
				"text": "...de bête. De l’autre nain elle tire deux bales dans l’escalier. Mouche : d’autres cris...",
				"offset": 43,
				"length": 5
			},
			"rule": {
				"id": "MORFOLOGIK_RULE_FR_FR",
				"description": "Faute de frappe possible",
				"issueType": "misspelling",
				"category": {
					"id": "TYPOS",
					"name": "Faute de frappe possible"
				}
			}
		}, {
			"message": "Faute de frappe possible trouvée",
			"shortMessage": "Faute de frappe",
			"replacements": [{
					"value": "rafale"
				}, {
					"value": "rafle"
				}, {
					"value": "Rafale"
				}
			],
			"offset": 766,
			"length": 7,
			"context": {
				"text": "...ris. Puis des hurlements d’enfants. Une raffale déchire le sommier entre mes jambes et ...",
				"offset": 43,
				"length": 7
			},
			"rule": {
				"id": "MORFOLOGIK_RULE_FR_FR",
				"description": "Faute de frappe possible",
				"issueType": "misspelling",
				"category": {
					"id": "TYPOS",
					"name": "Faute de frappe possible"
				}
			}
		}, {
			"message": "Voulez-vous écrire \\" ce \\ " ?",
			"shortMessage": "",
			"replacements": [{
					"value": "ce"
				}
			],
			"offset": 813,
			"length": 2,
			"context": {
				"text": "... déchire le sommier entre mes jambes et se paire contre le mur.",
				"offset": 43,
				"length": 2
			},
			"rule": {
				"id": "SE_CE",
				"subId": "1",
				"description": "SE au lieu de CE",
				"issueType": "uncategorized",
				"urls": [{
						"value": "http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=2440"
					}
				],
				"category": {
					"id": "CAT_HOMONYMES_PARONYMES",
					"name": "Confusion d’homonymes et paronymes"
				}
			}
		}, {
			"message": "Le mot « paire » ne peut pas suivre le mot « se ».",
			"shortMessage": "",
			"replacements": [],
			"offset": 816,
			"length": 5,
			"context": {
				"text": "...chire le sommier entre mes jambes et se paire contre le mur.",
				"offset": 43,
				"length": 5
			},
			"rule": {
				"id": "TE_NV",
				"subId": "1",
				"description": "me/te/se + non verbe",
				"issueType": "uncategorized",
				"category": {
					"id": "CAT_GRAMMAIRE",
					"name": "Grammaire"
				}
			}
		}
	]
}
```

**Comment by robert-hoffmann** [comment] 2017-11-29 11:09
This is the same text, and what chrome's default checker finds

![image](https://user-images.githubusercontent.com/5472296/33372397-2d34f32a-d4fe-11e7-92ca-b151841ffae9.png)

**Comment by danielnaber** [comment] 2017-11-29 11:20
>  i replaced all double spaces with single spaces

Getting an error for two spaces ("Faute de frappe possible : vous avez répété une espace") is actually a feature. I didn't see it because it got lost when I copy+pasted your text from above.

**Comment by danielnaber** [comment] 2017-11-29 11:25
So what is the conclusion, do you think we should add this or are the remaining bugs too bad?

**Comment by robert-hoffmann** [comment] 2017-11-29 12:53
I think the feature is good, but still needs tweaking

![image](https://user-images.githubusercontent.com/5472296/33375654-ed4e5802-d50a-11e7-9f28-e51c7d07dbef.png)

The error ratio is quite high:

Words with suggestions:
`scialitique` = good suggestion
`détonnation` = wrong suggestion
`inouie` = wrong suggestion
`bales ` = wrong suggestion
`raffale ` = good suggestion

Words without suggestions:
`du bâtant` = wrong analysis (right was: `du battant`)
`plaquer` = wrong analysis (right was: `plaqué`)
`homme trapue` = wrong analysis (right was: `homme trapu`)
`une cri` = wrong analysis (right was: `un cri`)
`paire` = wrong analysis (right was: `perd`)


There must be other types of analysises missing. I see in the english folder many many classes that seem to do many specific things (in german too) ..guess french need more work :-)

**Comment by danielnaber** [comment] 2017-11-29 13:55
`détonnation` doesn't work because of an easy-to-fix encoding issue. Most others are probably due to limitations in hunspell's `unmunch`, e.g. number flags not working. This means we cannot generate the list of all word forms needed for our approach. I have no easy solution here.

**Comment by danielnaber** [comment] 2017-12-01 15:31
Some performance numbers for a worst case scenario, where almost every word is misspelled (can happen when the wrong language is selected/detected):

* no suggestions: 3ms/sentence
* LT suggestions (Morfologik): 18ms/sentence
* hunspell (older version, as it comes with LT): 611ms/sentence (The current version of hunspell seems to be 10-20% faster for generating suggestions (tested on command line, unrelated to LT))

So hunspell is so slow that there's no way we can activate it. The only way would be to stop finding errors after some limit, to prevent the servers from being overloaded. @dpelle what do you think?

**Comment by robert-hoffmann** [comment] 2017-12-01 15:49
I think it's still worth it to add this as a feature ..even if you need to pass some arguments to activate it on the server.

In any case, right now without suggestions French i think is pretty unusable in the sense you are telling the user he did something wrong, but then it's up to him to figure it out. If he's no good at spelling, he'll never figure it out ^^

Also even in slowest case scenario, this is not a feature that would be usefull for something like "spell as you type", but still good for a button you hit to validate a whole text in one go, where you actually expect latency after hitting a button.

**Comment by mattpepin** [comment] 2017-12-18 19:46
I'm also testing LT and it seems to work fine in English. Without French spelling suggestions, it's a bummer...

**Comment by retomerz** [comment] 2017-12-20 15:40
This issue was already reported see #409
(we also wait for this feature)

**Comment by cwd24** [comment] 2017-12-20 16:33
> Most others are probably due to limitations in hunspell's unmunch, e.g. number flags not working.

This project might be of use, which was intended for the French Hunspell dictionary (disclaimer, I haven't actually tested this):
https://github.com/Fanaen/Hunspell2WordList

**Comment by danielnaber** [comment] 2017-12-20 21:29
> This project might be of use, which was intended for the French Hunspell dictionary

Thanks! It seems to be working. Here's another version of LT with a French spell checker that should be as accurate as hunspell and still fast: http://danielnaber.de/tmp/LanguageTool-4.0-SNAPSHOT-20171220-fr-spelling-hunspell.zip - could you test this?

Here's how the dictionary was built with the output of Hunspell2WordList:
https://gist.github.com/danielnaber/b194b1a53e5a76373763e206c0ccbf02
The reason that it's fast (or fast enough for us) is that we use hunspell for spell checking but generate the suggestions with Morfologik, based on the expanded hunspell dictionary. We've being doing this for a long time for German, so it should be fine.

**Comment by danielnaber** [comment] 2017-12-21 08:39
@mattpepin @cwd24 @retomerz if you can test this (see my reply above) within the next 2 days, we still have the chance to get this into the 4.0 release.

**Comment by mattpepin** [comment] 2017-12-21 12:33
Thanks, I will report back in a few hours.

**Comment by mattpepin** [comment] 2017-12-21 13:45
Well, it works fine for basic vocabulary mistakes, for example "corection" is corrected to "correction". However, it stops working for accented words, for example: "clementine" is not corrected to "clémentine" (there are no suggestions in this case, but the spelling error is detected). It also does not work when the error is in a conjugated verb, for example: "Ça fonctione" is not corrected to "Ça fonctionne". In this case, the suggestions are wrong. However, I still think the suggestions for vocabulary alone are worth it for 4.0.

**Comment by robert-hoffmann** [comment] 2017-12-21 13:47
Did some basic tests, and even if things could work better, i'd vote to have this integrated in 4.0, instead of having nothing :-)

**Comment by danielnaber** [comment] 2017-12-21 14:24
> However, it stops working for accented words, for example: "clementine" is not corrected to "clémentine" 

I cannot reproduce that, how did you try? With the stand-alone GUI?

![lt-fr](https://user-images.githubusercontent.com/857004/34259565-0cfbef70-e663-11e7-815b-1dc9ada837b4.png)

**Comment by mattpepin** [comment] 2017-12-21 14:28
No, I'm making HTTP requests. Here's the response I get:
`{"software":{"name":"LanguageTool","version":"4.0-SNAPSHOT","buildDate":"2017-11-28 20:18","apiVersion":1,"status":""},"warnings":{"incompleteResults":false},"language":{"name":"French","code":"fr"},"matches":[{"message":"Faute de frappe possible trouvée","shortMessage":"Faute de frappe","replacements":[{"value":"florentine"},{"value":"levantine"},{"value":"Florentine"},{"value":"couventine"}],"offset":0,"length":10,"context":{"text":"clementine ","offset":0,"length":10},"rule":{"id":"MORFOLOGIK_RULE_FR_FR","description":"Faute de frappe possible","issueType":"misspelling","category":{"id":"TYPOS","name":"Faute de frappe possible"}}}]}
`

**Comment by mattpepin** [comment] 2017-12-21 14:33
Ah my bad, the package compiled wrong, my mistake. it ran with the old snapshot in this thread. Let me report back.

**Comment by mattpepin** [comment] 2017-12-21 14:43
Ah yes! It's much better! I could still find some words with wrong suggestions, but it was harder. For example: "Ca fonctionne" should be "Ça fonctionne", but the suggestions were "CA" and "C a". There really is a good improvement in this snapshot.

**Comment by danielnaber** [comment] 2017-12-21 15:11
This has now been committed and it will be live tonight at https://languagetool.org and it will be part of tomorrow's snapshot at https://languagetool.org/download/snapshots/?C=M;O=D. Please open a new issue if there are bugs.

**Closed by danielnaber** 2017-12-21 15:11 UTC
Labels: French
