### ISSUE TITLE
Error message and incorrect suggestions

### ISSUE THREAD

**Issue by stephenaustin** [languagetool-org/languagetool#6160] opened 2021-12-17 02:22 UTC
Each time running Language Tool I get the error message, and the corrections it suggests are incorrect, as per the grab shown below. Using it on Libreoffice 7.2.4.1 on Windows 11 and on Pop OS 2.4. 
![language_tool_01](https://user-images.githubusercontent.com/33739991/146478353-66cf1198-af25-4a13-812a-c65dc92f131b.jpg)
![language_tool_02](https://user-images.githubusercontent.com/33739991/146478380-67a794a5-5bf8-4d11-b7d6-f0dee7728aef.jpg)

**Comment by danielnaber** [comment] 2021-12-17 08:06
Could you try whether the issue is solved with a recent snapshot? https://internal1.languagetool.org/snapshots/LanguageTool-20211216-snapshot.oxt

**Comment by stephenaustin** [comment] 2021-12-17 14:09
Thank you for your reply. However this new version is flagging the correct contractions of [you've] and [I've] as incorrect.
![language_tool_03](https://user-images.githubusercontent.com/33739991/146556547-96216af3-10ea-484a-985c-fd00082f0334.jpg)
![language_tool_04](https://user-images.githubusercontent.com/33739991/146556565-def8a207-6f12-4a66-83cd-8fb29e0540f2.jpg)

**Comment by danielnaber** [comment] 2021-12-17 14:46
@FredKruse Do you know why this might happen?

**Comment by jaumeortola** [comment] 2021-12-17 16:12
Which speller is being used here in LibreOffice? This seems the LanguageTool tokenization, but with the Hunspell spell checker, which perhaps doesn't have the words `'ll`, `'ve`...

**Comment by FredKruse** [comment] 2021-12-17 18:23
Yes, as speller the internal LibreOffice speller is used. The problem was related to the tokenization of the sentences.

**Comment by stephenaustin** [comment] 2021-12-17 22:29
Thanks for replying. What does 'tokenisation of the sentences' mean?

**Comment by FredKruse** [comment] 2021-12-19 18:53
@stephenaustin tokenization is, easily spoken, the splitting of the sentence into words.
The problem is solved, please test the latest snapshot.

**Comment by stephenaustin** [comment] 2021-12-19 22:24
Thanks for your reply. It would appear the app is still incorrectly flagging short forms. 
![language_tool_05](https://user-images.githubusercontent.com/33739991/146692953-4456d238-b479-4965-807a-b353e35c9c5d.jpg)

![language_tool_06](https://user-images.githubusercontent.com/33739991/146692958-3a29d99c-cfca-4453-9602-4790d4eef448.jpg)

**Comment by FredKruse** [comment] 2021-12-22 16:16
@stephenaustin There is not an official new version. But you could try the latest snapshot:
https://internal1.languagetool.org/snapshots/LanguageTool-20211221-snapshot.oxt
And do some tests with it.

**Comment by stephenaustin** [comment] 2021-12-23 03:47
Thanks for your reply Fred. Problem persists I'm afraid. Respectfully suggest that app is not coded to recognise English contractions. 
![languagetool](https://user-images.githubusercontent.com/33739991/147185181-9cc2fd93-5f4f-40d5-b492-61fd10050576.jpg)

**Comment by FredKruse** [comment] 2021-12-28 15:50
The problem should be solved. Please test it with the latest snapshot (after tomorrow)

**Comment by FredKruse** [comment] 2022-06-20 08:10
I think we can close the issue.

**Closed by FredKruse** 2022-06-20 08:10 UTC
Labels: bug, office-integration
