### ISSUE TITLE
[LO-Add-on] black window + underlining in wrong position — 2024-01-11

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10089] opened 2024-01-11 19:58 UTC
Heya, @FredKruse 

A few days of testing:
I have tested the latest nightly with LibreOffice 24.2.0.1 and its window still gets black with this version of LibreOffice, so probably it is an issue with the add-on.

Also, it underlines in green words in the wrong position and if you right-click them, it doesn't do anything.

See the video attached.

Thanks!

https://github.com/languagetool-org/languagetool/assets/5192600/356bcd2d-5b15-41b3-9ae8-9557afd46b1b

**Comment by marcoagpinto** [comment] 2024-01-12 05:20
@FredKruse 

The window blackened:

https://github.com/languagetool-org/languagetool/assets/5192600/c7b66695-b003-4cfa-b4bf-214300c6b91b

**Comment by FredKruse** [comment] 2024-01-12 13:43
The problems with the wrong position and no reaction at right mouse click should be solved. Please test it.
The turning black of the window seams to be a LibreOffice problem in combination of functions of LT that needs more time. The LO Window doesn't refresh. I have no idea how I could solve this by LT. The window refreshes if you e.g. change the size of the window.

**Comment by marcoagpinto** [comment] 2024-01-12 13:56
Thank you, @FredKruse 

My thesis has been causing too much trouble, I guess 😛 😛 😛 😛 😛 😛 😛

**Comment by marcoagpinto** [comment] 2024-01-15 12:19
At least it now underlines whole words instead of the underlines appearing in the middle of words.

**Comment by FredKruse** [comment] 2024-01-15 18:15
> @FredKruse
> 
> I posted, but the post vanished (or maybe I was stressed and didn't press the comment button).
> 
> The bug is still happening:
> 
> https://github.com/languagetool-org/languagetool/assets/5192600/adce40df-fbae-48f4-8dbe-cba790f70c94 (video with audio)

This is a bit crazy. I tried to reproduce the bug. But it works well. I tested it under Linux and Windows.
Could you try a 'Refresh Check Results'?

**Comment by marcoagpinto** [comment] 2024-01-15 19:28
> This is a bit crazy. I tried to reproduce the bug. But it works well. I tested it under Linux and Windows.
> Could you try a 'Refresh Check Results'?

Sure, I will delete the cache.

I will test it at 5am.

😛 😛 😛 😛

**Comment by marcoagpinto** [comment] 2024-01-16 06:39
@FredKruse 

Heya,

It is 100% reproducible here, it doesn't work.

[PhD_thesis_bugged_20240116.docx](https://github.com/languagetool-org/languagetool/files/13946224/PhD_thesis_bugged_20240116.docx)

[LanguageTool.log](https://github.com/languagetool-org/languagetool/files/13946228/LanguageTool.log)



https://github.com/languagetool-org/languagetool/assets/5192600/b54b80dd-e38c-429d-8643-e84ea18a93a3

**Comment by marcoagpinto** [comment] 2024-01-16 07:40
@FredKruse 

And now that we are at it, this .docx always makes the window black, so maybe it will help you fix the black window issue (it is only a one-page document, so it will make things easier to fix).

**Comment by FredKruse** [comment] 2024-01-16 10:18
@marcoagpinto 
I'm very sorry, but I can't reproduce the bug. I did exact what you did in the video. There was no problem (I don't speak Portuguese, but there was definitely a suggestion). 
The difference in the log file are:

- You use Windows 11 - I had run it on my Windows 10 test system (usually a use Linux). I don't think this could be a problem.
- We use the same java version
- In your log file, there is a very strange version number for LibreOffice (LibreOffice 24.2.0.1 (The Document Foundation), en-GB). I use 7.6.4.1. What version do you use?

I'm a little helpless and don't know what I can do.

**Comment by marcoagpinto** [comment] 2024-01-16 10:20
@FredKruse 

I am using LibreOffice prerelease 24.2.0.1, downloadable from LibreOffice's site.

**Comment by marcoagpinto** [comment] 2024-01-16 10:24
or what they call RC1 (release candidate 1).

The new versioning on LibreOffice: 2024 February.

**Comment by FredKruse** [comment] 2024-01-16 12:11
OK, I think I got it. Now, I had tested the bug with LO Version 24.2.0.1 and could reproduce the problem (with 7.6.4 .2 the check works correct). I did many tests and look what happened. LT gives back the right error when you do a right mouse click. It seems to be a problem with LO 24.2.0.1. It doesn't show the correct context menu, although the grammar checker gives an error back. Would you like to provide feedback to the LO team?

**Comment by marcoagpinto** [comment] 2024-01-16 12:18
> OK, I think I got it. Now, I had tested the bug with LO Version 24.2.0.1 and could reproduce the problem (with 7.6.4 .2 the check works correct). I did many tests and look what happened. LT gives back the right error when you do a right mouse click. It seems to be a problem with LO 24.2.0.1. It doesn't show the correct context menu, although the grammar checker gives an error back. Would you like to provide feedback to the LO team?

@FredKruse 
We have a developer who works in LibreOffice, I can't remember his name.

He helped create a fix for that bug that used to eat all RAM.

Let me try to find his name.

**Comment by marcoagpinto** [comment] 2024-01-16 12:22
It is @mikekaganski

Mike, would you mind helping us with this for LO 24.2.0.1?

Thanks!

**Comment by marcoagpinto** [comment] 2024-01-16 12:26
Ohhhh… Mike lives in Russia, so I don't know about his current condition… Just like Yakov, who never appeared again on GitHub.

**Comment by marcoagpinto** [comment] 2024-01-16 12:52
https://bugs.documentfoundation.org/show_bug.cgi?id=159220

**Comment by mikekaganski** [comment] 2024-01-16 12:55
Thank you Marco!
But please don't create stubs like "Here is the bug; go to another site to read some long-ish discussion to try to understand what it is about". Bug tracker issue should be self-contained, have clear problem description, and clear steps to repro. Thanks!

**Comment by marcoagpinto** [comment] 2024-01-16 12:58
Ahhhh... sorry.

**Comment by marcoagpinto** [comment] 2024-01-16 13:04
Done!

**Comment by FredKruse** [comment] 2024-02-06 12:02
@marcoagpinto 
Could we close this issue?

**Closed** 2024-02-06 12:15 UTC
Labels: office-integration
