### ISSUE TITLE
Capitalized in the middle of sentence

### ISSUE THREAD

**Issue by ArtsyDude** [languagetool-org/languagetool#1251] opened 2018-11-06 19:42 UTC
in the sentence I had;

Dad walked over slowly, suspecting me for what I was making a face for.

It wanted to capitalize "what." fix this.

**Comment by danielnaber** [comment] 2018-11-06 19:49
I cannot reproduce, can you send a screenshot?

**Comment by danielnaber** [comment] 2019-06-29 12:00
No reply, closing.

**Closed by danielnaber** 2019-06-29 12:00 UTC
Labels: English
