### ISSUE TITLE
[fr] "24h"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1641] opened 2019-06-19 10:19 UTC
> 24h
> 24H

<img width="363" alt="Bildschirmfoto 2019-06-19 um 12 17 03" src="https://user-images.githubusercontent.com/37363/59757511-36901600-928c-11e9-8351-7f50d3dc351a.png">

Not sure if this is really an anglicism. I guess it's a valid abbreviation of "24 heures".

Shall we add it to the `spelling.txt`? What do you think @dpelle?

**Comment by tiff** [comment] 2019-06-19 10:36
What do you think @vkyfox?

**Comment by dpelle** [comment] 2019-06-19 11:54
This article is relevant:
http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=5249

In French, we'd rather abbreviate as "24 h" with a space.

**Comment by vkyfox** [comment] 2019-06-19 12:03
What's interesting is that we do have a rule that suggests a space (22h -> 22 h) working for every number between 1 and 23, but not 24. I'm looking into it.

**Comment by PoorPocketsMcNewHold** [comment] 2019-06-19 14:08
> What's interesting is that we do have a rule that suggests a space (22h -> 22 h) working for every number between 1 and 23, but not 24. I'm looking into it.

Does the rules have some orders priorities ? This rule prefering other possible words due to being detected as a english word (the one suggested in the issue) could be a general rule, and so, be applied generally and before the specidically written rule for the *h like you was describing. Except if the rule didn't tagged for 24h of course. I'll try to do some test aswell.

**Comment by vkyfox** [comment] 2019-06-19 16:32
It was a regexp checking for 1 to 23, I added 4, should be good once the merging is complete.

**Comment by PoorPocketsMcNewHold** [comment] 2019-06-20 07:20
Does it support however instances where it's written with the minutes? As of 8h36 for example? (Well, By writing it, it doesn’t seem tho)

**Comment by tiff** [comment] 2019-06-23 20:12
Can we close this?

**Comment by vkyfox** [comment] 2019-06-24 13:29
Yes, everything seems to work as intended (except "24h" as I'm assuming it hasn't been merged yet, but should come in time).

**Comment by tiff** [comment] 2019-06-24 13:34
@danielnaber didn't you merge the "24h" change by @vkyfox already? It still happens for me on languagetool.org

**Comment by vkyfox** [comment] 2019-06-24 13:41
This one's on me : I had corrected the issue only in one of the two rules. Fixed it now.

**Comment by tiff** [comment] 2019-06-26 09:53
@vkyfox "24H" (upper case) still has a strange behavior. It suggests replacing it with the same.

<img width="354" alt="Bildschirmfoto 2019-06-26 um 11 52 20" src="https://user-images.githubusercontent.com/37363/60170531-e1628000-9808-11e9-8fd1-ee0820da5197.png">

**Closed** 2019-07-11 05:46 UTC
Labels: French

**Comment by MayeulC** [comment] 2019-12-09 15:24
> It was a regexp checking for 1 to 23, I added 4, should be good once the merging is complete.

That's an arbitrary limit, though. You can still talk about "the next 48h", and though 36, 48, 72, 96 seem to be more common, I wouldn't exclude others.

**Comment by vkyfox** [comment] 2019-12-09 18:22
This was an undocumented change but I opted to do any number rather than 0-24 in the end.
