### ISSUE TITLE
[de] spell check: lowercase/uppercase issue

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#764] opened 2017-08-07 11:55 UTC
Paste the following text into the LT text field:
Ventrolateral Illustratorische Ventrolateral, derzufolge Test.
'Illustratorische' and 'Ventrolateral' are marked as errors mid-sentence, but their lowercase counterparts aren't. Both words are in spelling.txt. Moreover, the supposedly wrong words are suggested as corrections for themselves.
![2017-08-07-132505_1024x768_scrot](https://user-images.githubusercontent.com/4381288/29025574-affa045c-7b77-11e7-99c0-6d45eaab64f0.png)

**Comment by danielnaber** [comment] 2017-08-07 14:13
Indeed, it seems to work for English, i.e. "myword" would be accepted, as would "MyWord". That's not the case for German, probably caused by: https://github.com/languagetool-org/languagetool/blob/44be46022567c88a550ed23961ec26ffb67931ad/languagetool-core/src/main/java/org/languagetool/rules/spelling/SpellingCheckRule.java#L170

**Comment by danielnaber** [comment] 2017-08-07 14:57
Should be fixed now.

**Closed by danielnaber** 2017-08-07 14:57 UTC
Labels: bug, German

**Comment by jaumeortola** [comment] 2017-08-09 13:12
I have added a more general solution here: https://github.com/languagetool-org/languagetool/commit/f5f1a4027d53bac8056b35755cfd3b49d8911118
This avoids capitalizing mixed-case words like pH
