### ISSUE TITLE
LibreOffice: error dialogs appears multiple times

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2718] opened 2020-04-07 14:04 UTC
See #2709. While the issue has been fixed, I think we still have the problem that the error dialog can open hundreds of times if there's an error we don't know about yet.

@FredKruse

**Comment by FredKruse** [comment] 2020-04-22 08:10
@danielnaber The issue is solved: Now, an error dialog appears only at the first time an error is thrown. All following messages are written to the log file. Please close the issue.

**Closed** 2020-04-22 08:26 UTC
Labels: bug, office-integration
