### ISSUE TITLE
LT 5.4 Java null ptr exception; Libre Office 7.2.1.2, Win 10 Pro

### ISSUE THREAD

**Issue by BloomingAzaleas** [languagetool-org/languagetool#5747] opened 2021-09-27 20:14 UTC
LO details: Writer module
Version: 7.2.1.2 (x64) / LibreOffice Community
Build ID: 87b77fad49947c1441b67c559c339af8f3517e22
CPU threads: 8; OS: Windows 10.0 Build 19043; UI render: Skia/Raster; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: threaded

Stack trace msg window upon first start of spell check (F7) in first open of LO Writer (fresh LO session of any kind).  
Repeatable: close all LO, re-launch LO, open first Writer doc.  
JPG of stack trace window screenshot attached.

![2012-09-27-LT-stack-trace](https://user-images.githubusercontent.com/31942133/134978012-f690a826-70b3-4c47-8354-a0d49b458916.JPG)

Subsequent to dismissing the stack trace window, LT seems to function as expected (!!!!!).

Regards.

**Comment by BloomingAzaleas** [comment] 2021-09-27 21:24
It gets worse.  Attached JPG.  Fun!

Possibly slightly different behavior: do not have to launch Spell Check (F7) for the exception to throw.  Just have to wait several seconds.  I am reverting to LT 5.4 and its less scary stack trace.

FYI, the LO Extension Manager, when removing LT, may not cleanly remove the LT *tmp_ directory from AppData/Roaming/LibreOffice/4/user/uno_poackages/cache/uno_packages. LT requests an LO re-start after an ADD or a REMOVE, but the LO Extension Manager does not prevent the user from proceeding with normal use anyway. I am thinking that may potentially leave the LT install or remove in an intermediate state prone to corruption.  I have had to manully intervein on occasion to remove that *tmp_ directory.

![2012-09-27-LT-2010927-snapshot-stack-trace](https://user-images.githubusercontent.com/31942133/134984485-c42284be-d51c-49ff-82b3-48ea9c4029ad.JPG)

Regards.

**Comment by danielnaber** [comment] 2021-09-28 06:36
@FredKruse any idea?

**Comment by BloomingAzaleas** [comment] 2021-09-28 13:27
A first thing could be additional diagnostic visibility, for example, a point version that provides a button to dump the stack trace to text (unless that is already done and I just don't know where those dump files land).  I also note the 2nd stack trace above contains document text, which makes for some privacy anxiety.  A screenshot image can be redacted (GIMP to the rescue) but that is a pain compared to redacting text.

**Comment by FredKruse** [comment] 2021-10-01 08:11
> ![2012-09-27-LT-stack-trace](https://user-images.githubusercontent.com/31942133/134978012-f690a826-70b3-4c47-8354-a0d49b458916.JPG)

This bug was already solved in version 5.5.

**Comment by FredKruse** [comment] 2021-10-01 08:17
> FYI, the LO Extension Manager, when removing LT, may not cleanly remove the LT *tmp_ directory from AppData/Roaming/LibreOffice/4/user/uno_poackages/cache/uno_packages. LT requests an LO re-start after an ADD or a REMOVE, but the LO Extension Manager does not prevent the user from proceeding with normal use anyway. I am thinking that may potentially leave the LT install or remove in an intermediate state prone to corruption. I have had to manully intervein on occasion to remove that *tmp_ directory.

The LT extension manager can not be controlled by LT, so this is probably a bug in LO. Please report it to LO.

**Comment by FredKruse** [comment] 2021-10-01 08:21
> ![2012-09-27-LT-2010927-snapshot-stack-trace](https://user-images.githubusercontent.com/31942133/134984485-c42284be-d51c-49ff-82b3-48ea9c4029ad.JPG)

@danielnaber This is strange. The problem seems to be triggered by a missing (LT-) spell checker. But: The office extension doesn't use the LT spell checker. The LO spell checking is used.

**Comment by BloomingAzaleas** [comment] 2021-10-01 13:11
> 
> This bug was already solved in version 5.5.

FYI: I don't know if/when 5.5 was officially released but the most recent version available on https://extensions.libreoffice.org/en/extensions/show/languagetool, which in turn is referenced on https://languagetool.org/, reports itself as 5.4.

**Comment by FredKruse** [comment] 2021-11-18 18:31
The issue is solved in 5.5.1 and 5.6. I close the issue.

**Closed by FredKruse** 2021-11-18 18:31 UTC
Labels: office-integration
