### ISSUE TITLE
English "wall" --> 'Hint: “wall” (English) means “wand”, “muur" '

### ISSUE THREAD

**Issue by BloomingAzaleas** [languagetool-org/languagetool#5752] opened 2021-09-28 16:37 UTC
English: "I leaned on the corridor wall" --> LT 5.4: "Hint: “wall” (English) means “wand”, “muur” (English). Did you mean “wand”, “muur”?"

Say what?  "muur" not showing in Collins, Webster's, OED.  "murr" (U R R), yes, "muur" (U U R), no.   "wand" is just, well, off the wall.

LibreOffice
Version: 7.2.1.2 (x64) / LibreOffice Community
Build ID: 87b77fad49947c1441b67c559c339af8f3517e22
CPU threads: 8; OS: Windows 10.0 Build 19043; UI render: Skia/Raster; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: threaded

**Comment by FredKruse** [comment] 2021-10-01 08:39
I'm sorry, but I don't understand the bug.
@danielnaber It seems that an English rule is regarded. Why did you label it as office-integration?

**Comment by BloomingAzaleas** [comment] 2021-10-01 13:01
The bug(s) is LT 5.4 
A) apparently not liking the combination of the past tense 'leaned' of the verb form of 'lean' ( as in 'You leaned [your body] against the so-bad-for-you sweets display waiting for your coffee order.') with the noun subject 'wall' (as in one of the vertical sides of a building or room).  'I leaned against the wall' is perfectly valid in English. But note in the actual LT example the adjective use of 'corridor' with 'wall', which may be a contributing factor if 'corridor' is not being recognized correctly, thereby cascading to an incorrect recognition of 'wall'.

B) equating the the definition or semantics of 'wall' (or 'corridor wall') with the word 'wand' (as in a stick, rod, cane, or baton held by the hand and possibly waved around to play with the cat, conduct an orchestra or pull a rabbit out of a hat).

C) equating the the definition or semantics of 'wall' (or 'corridor wall') with the construction 'muur' (M, U, U, R) which does not appear in any major English dictionary.

Smells like this is a database English data error rather than a logic error per se.

**Comment by danielnaber** [comment] 2021-10-01 15:51
> Why did you label it as office-integration?

I cannot reproduce with the API, so I thought it might be LO-specific:

https://api.languagetool.org/v2/check?text=I%20leaned%20on%20the%20corridor%20wall.&language=en-US&motherTongue=nl

**Comment by BloomingAzaleas** [comment] 2021-10-01 23:26
Additional diag data:
A) Using binary search I cut the triggering text down to a minimal case LO text doc consisting only of 'I leaned on the wall.'
B) Test: 
B1) type or copy/paste this text into a LO File->New->'Text Document'.  Important: LO doc is open but not yet saved!  
B2) Run Spell Check F7 and LT does NOT report any issues for un-saved doc. 
B3) Save this new text doc.  Quit all LO so re-start from known state.  
B4) Launch the text doc previously saved (B3). The position cursor at start of text and F7.
B5) LT interface starts up, says initializing then checking then throws #5747 null ptr exception.
B6) Dismiss the Java stack trace then re-position the cursor to beginning of text for another round of F7.
B7) F7
B8) LT appears to operate as expected except showing this bug #5752 as a suggested change to the text.
B9) FYI - neither ngrams nor word2vec active.

![LT-bug-5752-UI-Capture](https://user-images.githubusercontent.com/31942133/135695418-cb7487e2-3e0a-4775-b506-c396095abe65.JPG)

**Comment by FredKruse** [comment] 2021-10-02 18:51
Thank you for testing and for your description. I could reproduce the bug. It will be solved in LT 5.5.
@danielnaber: Till now, I didn't understand the concept of 'false friends'. Therefore, 'motherTongue' is not supported by the extension. I will add this in LT 5.6.

**Comment by danielnaber** [comment] 2021-10-02 19:20
> Therefore, 'motherTongue' is not supported by the extension. I will add this in LT 5.6.

I'm not sure if this is worth it. It uses the ngram data for some (all?) languages and will not work well without. As the ngram data is huge, I guess most users don't have it installed.

**Comment by BloomingAzaleas** [comment] 2021-10-03 06:19
FYI: I have English ngrams downloaded, have tried it, but disabled it for the above diag work.  Even with a Xeon 32GB RAM running on NVMe SSD, ngram intialization takes a while when LT is first launched.

**Comment by BloomingAzaleas** [comment] 2021-10-04 16:46
FYI: Here is another same/similar issue.

![LT-bug-5752-UI-Capture2](https://user-images.githubusercontent.com/31942133/135891118-a5914eb5-f2d8-46f5-8317-4709ed0da727.JPG)

**Comment by FredKruse** [comment] 2021-11-18 18:30
The issue is solved in 5.5 and 5.6. I close the issue.

**Closed by FredKruse** 2021-11-18 18:30 UTC
Labels: office-integration
