### ISSUE TITLE
[pt-br] suggestion for lower case "facebook"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1743] opened 2019-07-23 10:59 UTC
"Facebook" doesn't appear in the suggestions even though it is in the `spelling.txt`:
<img width="388" alt="Bildschirmfoto 2019-07-23 um 12 58 59" src="https://user-images.githubusercontent.com/37363/61706943-a7be5f80-ad49-11e9-938a-50e5bf8c0c7e.png">

Doesn't happen with pt-pt

**Comment by danielnaber** [comment] 2019-07-23 11:57
Indeed, Portuguese is one of the few languages that use class `Hunspell` for spell checking. The others are Galician, Swedish, and Khmer. All others use a combination of hunspell and Morfologik for better performance. `Hunspell` doesn't consider `spelling.txt` for generating suggestions. That's a bug, but we need to decide whether we fix that or whether we can switch to the same Morfologik/hunspell combination as the other languages do.

**Comment by danielnaber** [comment] 2019-07-23 12:08
@TiagoSantos81 Do you remember anything about Portuguese using `Hunspell` and not the Morfologik-based approach?

**Comment by danielnaber** [comment] 2019-07-24 09:34
Our statistics show that PT is roughly 30% slower than EN on average, and that's probably due to hunspell.

**Comment by TiagoSantos81** [comment] 2019-07-25 00:42
@tiff Thank you for the bug report. 
Given the divenge between European Portuguese and Brasilian Portuguese, both languages have different dictionaries and maintainers. Words that are common to both branches and to all spelling agreements have been added to spelling.txt. I do not use to change things specific to Brasilian Portuguese, unless required. Most works I have committed to that branch was do to branching of general functions on the common Portuguese branch.

@danielnaber
"@TiagoSantos81 Do you remember anything about Portuguese using Hunspell and not the Morfologik-based approach?"
Hunspell is still being used, because Hunspell, for now, IMHO, is a superior solution. 
Rule based diphthong replacement suggestions, easy to configure, easy to add affixes that affect the hole dictionary, replacement characters (i.e. apostrophes and ligatures), commentary that creates a base for further POS work. 
It is advanced, easy to develop, the work done here can be easily exported to other programs, such as LibreOffice, and, most of all, easy to maintain.
Key here is, easy to maintain, since the Morfologik based approach requires constant adding of compounds, and suggestions adjustments in a nearly case by case scenario, such I have seen here. A familiar example to you is German. German is well advanced and still has weekly work (and weekly "bug" reports) regarding that.

@danielnaber
"Indeed, Portuguese is one of the few languages that use class Hunspell for spell checking. The others are Galician, Swedish, and Khmer. All others use a combination of hunspell and Morfologik for better performance. Hunspell doesn't consider spelling.txt for generating suggestions. That's a bug, but we need to decide whether we fix that or whether we can switch to the same Morfologik/hunspell combination as the other languages do."
"Our statistics show that PT is roughly 30% slower than EN on average, and that's probably due to hunspell."

Indeed Portuguese has 30% slower performance than English, and that is a fact I am kind of proud of.

When I started, Portuguese already used Hunspell as well as a rule stack that was faster than the Spanish and Galician Language. I remember that the whole regression tests ran in the order or 200-250s back then. Test the Portuguese language in 3.5 version and see for yourself. (https://languagetool.org/download/LanguageTool-3.5.zip )

Now it is 10 times slower (https://internal1.languagetool.org/regression-tests/), but due to all the rule, new analysis modules, changes to LanguageTool core behavior and big databases added. 

Hunspell implementation is slower, but negligibly slower. What slows down Portuguese it is wide range of analysis and heavy processing rules. Look at the compounds database size in Portuguese and compare to other languages. Look at the effect that the rule Dash Java rule has on Portuguese module performance, in comparison with, say for example Russian or English.

@danielnaber
"That's a bug, but we need to decide whether we fix that or whether we can switch to the same Morfologik/hunspell combination as the other languages do."
Indeed, but unrelated to Hunspell or Morfologik. I think the bug is in the way "spelling" relates to Hunspell. Notice that quite often I copy the words list in spelling to the hunspell dictionary, thus, working around this bug. This only applies to the dictionaries I maintain. For other dictionaries, their maintainer needs to have the same care.

This performance issue has been cropping up from time to time, and although I am all for performance increases, they require time and they are prone to regressions, so I ask not to touch in those areas in Portuguse. No need to look far. Look at the many interactions of any performance optimization that as been done here to get the point.

Eventually I will get back to it and do what has to be done, in a proper way but definitely not now.

**Comment by TiagoSantos81** [comment] 2019-07-25 00:54
Sorry about the heated reaction, but these things seem too obvious to have to be pointed out, and I am not even an expert on this field.

**Comment by TiagoSantos81** [comment] 2019-07-25 13:10
Relevant topics, on the reason for not using Morfologik speller in the Portuguese module:

https://forum.languagetool.org/t/better-spelling-suggestions-would-be-really-nice-to-have/1459
https://forum.languagetool.org/t/change-in-run-on-words-spell-checker-behavior/1908/2
https://forum.languagetool.org/t/morfologik-and-uppercase-words/2260
https://forum.languagetool.org/t/words-in-spelling-txt-doesnt-appear-in-suggesting-list/1320

**Closed** 2020-03-25 11:59 UTC
Labels: Portuguese, bug
