### ISSUE TITLE
Exhaust system CPU with big text file input

### ISSUE THREAD

**Issue by evandrocoan** [languagetool-org/languagetool#904] opened 2018-02-14 16:09 UTC
Some times I am writing issues on GitHub and I need to put loads of code or stack traces. Then, language tool keep constantly using all my CPU while I am typing on the browser.

Is there some option like to force language tool only use one of my system threads instead of all them?

What language tool does when the chrome plugin is constantly sending a very big text file? Can they cool down a little bit and not process every keystroke?

Related:

1. https://github.com/languagetool-org/languagetool/issues/902 OutOfMemoryError: Minimum server requirements for HTTP Server

**Comment by danielnaber** [comment] 2018-02-14 16:31
If this is about the add-on, please re-submit this issue at https://github.com/languagetool-org/languagetool-browser-addon/issues with more detailed instructions on how to reproduce. Or is it about the LanguageTool server?

**Comment by evandrocoan** [comment] 2018-02-14 16:38
It is about both. For the add-on part, I will open an issue over there. For this part, language tool server keeps using 100% of my CPU, i.e., all my 4 cores, if some very big text is sent to the server. Can it be restricted to use only 1, therefore, my system is not lagged if some very big text is sent to the server?

**Comment by danielnaber** [comment] 2018-02-14 19:35
> For this part, language tool server keeps using 100% of my CPU, i.e., all my 4 cores,

I cannot reproduce this - how exactly have you started the server?

**Comment by evandrocoan** [comment] 2018-02-15 02:03
I start like this:
```batch
SET VERSION=LanguageTool-4.0
SET CURRENT_PATH=%~dp0

java -cp "%CURRENT_PATH%%VERSION%\languagetool.jar" org.languagetool.gui.Main -t >> "%CURRENT_PATH%output.txt" 2>&1
```

It is not simple to make the application eat everything. But should be more like this:

1. Create a big text (computer power dependent)
1. Start typing at the end of the text
1. Stop some seconds (the server did not have responded yet)
1. Start typing again (the server did not responded yet)
1. Stop some seconds (the server did not responded yet)
1. Start typing again (the server did not responded yet)

On this graph I did this, and the java server got until 66% of my total CPU. The remaining CPU power was also used Google Chrome (about 8%), the monitoring tool graphs used (about 10%), and screen recording and on total I got 100% while simply typing text. Consider that under normal circumstances, I would not get the recording tool neither the graphs open, but the language tool still make the system requires until 100% of processing:

![back2](https://user-images.githubusercontent.com/5332158/36237120-25a06f48-11e1-11e8-9db3-4fa391586415.gif)

If I open my monitor tool and set the core affinity of the language tool process to only one core, it stays around 20% of CPU:

![image](https://user-images.githubusercontent.com/5332158/36237383-7d368048-11e2-11e8-8604-8a24e7a4d98f.png)

![back3](https://user-images.githubusercontent.com/5332158/36237461-ef0b65a8-11e2-11e8-9134-d03067601d0e.gif)

**Comment by danielnaber** [comment] 2018-02-15 07:53
As I cannot reproduce this with curl, it's probably because you have one text but are actually using several threads on the server side (as the results have not yet arrived when you send a new request), and there's one threads per CPU. So this seems to be add-on specific, not server-specfic.

**Comment by evandrocoan** [comment] 2018-02-15 17:45
Makes sense. Then the Chrome add-on should not re reseeding new request to the server until the got an answer?

However, what if the request was too big like would take the server 10 minutes to answer? The add-on seems to be timing out around 30 or 60 seconds. Therefore, the server would still be receiving similar and extremely big requests every few seconds, while it still processing the old requests.

Should the add-on be able to send a `cancel` request to the server before sending a new big request?

**Comment by danielnaber** [comment] 2018-03-10 08:23
Closing here, seems to be add-on specific.

**Closed by danielnaber** 2018-03-10 08:23 UTC
