### ISSUE TITLE
Theming bug with the Libreoffice checking dialog

### ISSUE THREAD

**Issue by CharoSW** [languagetool-org/languagetool#5226] opened 2021-06-20 10:44 UTC
The box that has the error reason and the box that has the within document context both having a theming error when run under Adwaita Dark gtk theme.  Their default text shows up as black when according to the theme it should be white.
![lorem](https://user-images.githubusercontent.com/19259975/122670982-edbb2100-d207-11eb-92a2-bb1144933c0e.jpg)

**Comment by FredKruse** [comment] 2021-11-18 18:51
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 18:51 UTC
Labels: office-integration
