### ISSUE TITLE
Libreoffice 5.3 add-on: nullpointer exception when using custom server

### ISSUE THREAD

**Issue by NoeelMoeskops** [languagetool-org/languagetool#4932] opened 2021-04-29 10:44 UTC
Hi,

I'm using [A Docker LanguageTool 5.3 server](erikvl87/languagetool), and I'm trying to connect to the server using the LibreOffice LanguageTool add-on (also version 5.3). But when changing the settings in the add-on to connect to my private server I get a null pointer exception.
![Exception](https://user-images.githubusercontent.com/10706939/116538568-fbc78200-a8e7-11eb-8479-5d7f21402abb.png)
Apparently the Rule variable is not set in RuleMatch? 
https://github.com/languagetool-org/languagetool/blob/9d7221d2b102c14159668176f30093aad610f308/languagetool-core/src/main/java/org/languagetool/rules/RuleMatch.java#L144
Libreoffice version information:
- Version: 7.0.5.2
- Build ID: 00(Build:2)
- CPU threads: 12; OS: Linux 5.11; UI render: default; VCL: gtk3
- Locale: nl-NL (nl_NL.UTF-8); UI: en-US
- Calc: threaded

OS is Fedora 33.

Any help would be greatly appreciated. I also tried different Java versions (8, 11 and 16) with no luck.
The Firefox add-on is working perfectly fine when connected to my private server.

**Comment by NoeelMoeskops** [comment] 2021-04-29 11:15
Update: I get the same exception when using the default LanguageTool server. Only local seems to work

**Comment by FredKruse** [comment] 2021-05-05 08:14
@NoeelMoeskops Both problems are solved, please test it with 5.4-snapshot tomorrow and close the issue, if the problem is solved.
NOTE: the extension and the custom server has to  join the same version. Otherwise, missing rules at one of the components will not generate any matches.

**Comment by kacnje** [comment] 2021-05-14 09:02
I have the same problems. Can someone help me, how to install 5.4? When it will be available in production?

**Comment by FredKruse** [comment] 2021-11-18 18:59
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 18:59 UTC
Labels: office-integration
