### ISSUE TITLE
all words misspelled with en-GB

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#619] opened 2016-11-24 16:35 UTC
See http://forum.languagetool.org/t/en-gb-wrong-result/1230/

Text to test:

      eta_i This is a long test.

**Comment by f-knorr** [comment] 2016-11-25 20:31
Well, I do not have a fix, but to narrow down the search I can offer some analysis: After calling `morfologik.speller.Speller.findReplacements("eta_i")` in  all words are marked as incorrect and suggestions are no longer generated.

**Comment by danielnaber** [comment] 2016-11-25 20:58
So this seems to be a morfologik bug. Maybe you can set up a minimal test case with only morfologik code (no LT code) and submit it as an issue [here](https://github.com/morfologik/morfologik-stemming/issues)? Or maybe is the internal separator character not supposed to appear in words?

**Comment by jaumeortola** [comment] 2016-11-25 22:53
If you make a dump of the en_GB speller dictionay (with `java -jar morfologik-tools-2.1.3-SNAPSHOT.jar fsa_dump`), you can see that there is an entry for "ETA_I" (all uppercase).  "_" is the separator and "I" is the encoding for the frequency of the word. 
The problem in LT with "eta_i" can be reproduced with other entries:
eprom_g, era_j, esc_i, esr_h, eta_i ... (which are dictionary entries but all uppercase), 
also with:
eta_I, eprom_G...

There are other strange behaviors. If you write "eta_i, this is a test, eta, easto, Eastwoodii" in LT, the suggestions for the last three words contain frequency information.
![eta_i](https://cloud.githubusercontent.com/assets/4289501/20636219/3dc42dee-b369-11e6-85f3-5121e0378cb1.jpg)

**Comment by f-knorr** [comment] 2016-11-29 17:53
I can give it a try to create a minimal working example to reproduce the bug. Might take a while!

**Comment by jaumeortola** [comment] 2016-11-29 18:02
I am working on it now. I have written a test [here](https://github.com/jaumeortola/morfologik-stemming/commit/23ba98e511a7dde42811c100cf394ad73e12c023), and I will start debugging.

**Comment by milekpl** [comment] 2017-04-23 08:44
@jaumeortola Wouldn't it be easier just to produce a sanity check on data? I mean we can easily check whether a given character is contained the entry or not, and if it is, complain that it's not allowed to be included (discard it silently or stop producing the dictionary then). Moreover, I suspect that '_' is to be removed altogether. These are not English dictionary words.

**Comment by jaumeortola** [comment] 2017-04-23 11:38
@milekpl I wrote about this here: https://github.com/morfologik/morfologik-stemming/issues/86. Something like ETA_I is in the dictionary because "ETA" is a word, "_" is the separator and "I" is the frequency of this word. As an English word, of course, it is nonsense. 
In [isInDictionary()](https://github.com/morfologik/morfologik-stemming/blob/master/morfologik-speller/src/main/java/morfologik/speller/Speller.java#L257) there is a faulty logic, because when a perfect match is found, we assume that there are no separators, but in this case there are separators in the dictionary. 

I have written a fix: https://github.com/morfologik/morfologik-stemming/pull/88

**Comment by jaumeortola** [comment] 2017-04-24 10:19
Fixed with new morfologik version: https://github.com/languagetool-org/languagetool/commit/a0c19a8137dfc81ea0469db5ae8fd3705eab70fc

**Closed by jaumeortola** 2017-04-24 10:19 UTC
Labels: bug, English
