### ISSUE TITLE
Frequently shown Error Message "String index out of range: 845

### ISSUE THREAD

**Issue by ghtask** [languagetool-org/languagetool#1018] opened 2018-06-05 01:53 UTC
Hi, the cool guys at languagetool:

I would like to report an error message that frequently shows up on my screen. You can see the pic of of it here:
![error](https://user-images.githubusercontent.com/39933564/40950626-166b5dac-6863-11e8-945c-cdebbd2dce9d.png)

It' annoying, but the Language Tool works nonetheless. Maybe somewhere it does not work well, however, i did not notice that.

I really enjoy this excellent tool and hope it will be better and better.

**Comment by danielnaber** [comment] 2018-06-05 06:51
This is a duplicate of #976 which has been fixed. You can use a recent snapshot (https://languagetool.org/download/snapshots/?C=M;O=D) or wait for the next release in 3 weeks.

**Closed by danielnaber** 2018-06-05 06:51 UTC
