### ISSUE TITLE
"25te"

### ISSUE THREAD

**Issue by xhendrikg** [languagetool-org/languagetool#6208] opened 2022-01-02 17:55 UTC
It's not wrong, it's German, and it's marked as wrong in the Firefox Add-on.

**Comment by f-knorr** [comment] 2022-01-02 19:00
Probably caused by the same reason that caused '3sat' to be marked as an error (see https://github.com/languagetool-org/languagetool/commit/aca7db154a8466c1c00f12a1eba2dc90d66ff85f#):

> digits are removed during hunspell-style tokenization before

**Comment by udomai** [comment] 2022-01-03 07:57
Hi @xhendrikg! Thanks for bringing this to our attention.

The correction for "25te" is indeed not great. @AgnesKleinhans, I think this is a quick win… if we have one or more digits, no space, followed by `te[nr]`, we should suggest `25.`. "25te" is not standard German, do you agree?

@jaumeortola We could suggest `fünfundzwanzigs$1` if we had a NumberSpellerFilter (for cardinals) in German – or do we already have one (from digits to letters)? Could such a filter spell out ordinal numbers just as easily?

**Comment by jaumeortola** [comment] 2022-01-03 10:30
@udomai I can add a filter for spelling German cardinals. Probably, it will be able to spell ordinals as well. I have to check it.

**Comment by jaumeortola** [comment] 2022-01-03 12:26
You can now spell a cardinal number in German. See: https://github.com/languagetool-org/languagetool/commit/cfab4a6de9c85fe10bc59a823420a53c32f7d57b

We could also spell ordinal numbers, if needed. It could be `<suggestion><match no="1" postag="_spell_number_ordinal"/></suggestion>` (not yet implemented). What would the input be? `25`, `25te`, both?

**Comment by udomai** [comment] 2022-01-04 08:01
The input could be `25.` or the nonstandard `25te[nr]`

I've thought this through a little more:

- we'd need to spell out only a handful of ordinals (1., 2., 3.) and only in very specific contexts. We can do that by hand.
- ordinals come with a lot of morphological baggage (number, gender, case, determination), it would be a lot harder to get that right

The fact that we can spell out cardinals now is super helpful. Doing the same for ordinals is not worth it, in my view.

**Comment by danielnaber** [comment] 2022-12-31 12:41
Closing, seems to be fixed

**Closed by danielnaber** 2022-12-31 12:41 UTC
Labels: German
