### ISSUE TITLE
Nighly test does not show picky rules in diff page

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#7679] opened 2023-01-08 06:53 UTC
Why is this? I changed quite some rules to picky, but this is not shown.

**Comment by danielnaber** [comment] 2023-01-08 09:28
Which one are you missing? The "p" indicates it's a picky rule:

![picky](https://user-images.githubusercontent.com/857004/211189022-08556d61-4cdd-470d-92a9-5591ae1357bf.png)

**Comment by baarsrj** [comment] 2023-01-08 10:04
Yes, But I am sure I change a lot more. I will see again tomorrow, since I am making all rules with &vlotter_msg to picky, since these are all on the same level of pickyness.
I also noticed a lot of rules in that category commented out. I don't remember doing that, but it could have been before picky was introduced. Will reactivate those one by one and see what it brings.

**Comment by baarsrj** [comment] 2023-01-09 06:24
If you look here https://internal1.languagetool.org/regression-tests/via-http/2023-01-09/nl/ , many messages disappeared, e.g.  MITS. Looking on the full page, they have also gone. MITS is not there at all.
I do not understand why changing a rule from 'normal' to 'picky' makes it disappear, while other picky rules are still shown.

**Comment by danielnaber** [comment] 2023-01-09 10:04
At https://internal1.languagetool.org/regression-tests/via-http/2023-01-09/nl/result_grammar_MITS[1].html you can see that the matches for `MITS` are gone because they have been replaced by `MITS_TENZIJ`:

![MITS](https://user-images.githubusercontent.com/857004/211283385-a53a5165-ba31-48f0-adce-03d2eb311f50.png)

**Comment by baarsrj** [comment] 2023-01-09 10:08
Ah, I see. Priorities....

Also, maybe the text 'Maybe replaces old match:' should be 'The old match has been replaced by this one:'

**Comment by danielnaber** [comment] 2023-01-09 10:19
We already have "replaces old match" and "replaced by" (screenshot from [here](https://internal1.languagetool.org/regression-tests/via-http/2023-01-09/nl/result_grammar_MITS_TENZIJ[1].html)):

![replaces](https://user-images.githubusercontent.com/857004/211285797-f05cf823-6878-4da4-81ff-504da739b830.png)

**Comment by marshinkar** [comment] 2023-03-21 15:27
This issue seems to be resolved, I am closing. Please reopen should anything still be pending here.

**Closed by marshinkar** 2023-03-21 15:27 UTC
