### ISSUE TITLE
text in suggestion is ignored when match and regexp is used.

### ISSUE THREAD

**Issue by srtxg** [languagetool-org/languagetool#373] opened 2016-03-14 20:53 UTC
Hello, I discovered what seems to be a bug.

I need to catch some incorrect constructions like "nel vola-t i nén" and suggest the proper "vo nel la-t i nén".
For detecting the wrong construct I use a <regexp>[Nn](' el|el|i l') ((ri?|)vo?(la|ci|cial|chal))(-t i|-t ele|) nén</regexp>

Now, if I just use a suggestion with a text with \1 \2 etc, it works correctly;
but in some case, I would need to do an extra transformation.
When the matching is done with "token", then I can have a suggestion with text, and "match" with regexp_replace in it; it works correctly.
But if I try that when the match is done with "regexp", then everything inside the "suggestion" but outside the "match" is ignored.

Here are some test rules to reproduce it.

```
<rulegroup id="TESTS" name="Rîles di saye">
        <rule id="TEST_01" name="xnel vola -> vo nel la">
            <regexp>[Xx][Nn](' el|el|i l') ((ri?|)vo?(la|ci|cial|chal))(-t i|-t ele|) nén</regexp>
            <message>Test 01: <suggestion>vo <match no="1" 
                                    regexp_match="[Xx].* (ri?|)vo?(la|ci|cial|chal)(-t i|-t ele|) nén"
                                    regexp_replace="nel $1$2$3 nén"/></suggestion>.</message>
            <example correction="foo nel la-t i nén"><marker>xnel vola-t i nén</marker> co.</example>
        </rule>
        <rule id="TEST_03" name="znel vola -> vo nel la">
            <pattern>
                <token regexp="yes">znel</token>
                <token regexp="yes">(ri?|)vo?(la|ci|cial|chal)</token>
            </pattern>
            <message>Test 03: <suggestion>vo <match no="1" case_conversion="startlower"
                                    regexp_match="[zZ](nel)" 
                                    regexp_replace="$1"></match> <match no="2" 
                                    regexp_match="(ri?|)vo?(la|ci|cial|chal)" 
                                    regexp_replace="$1$2"></match></suggestion>?</message>
            <example correction="vo nel rila"><marker>znel rvola</marker>-t i nén co.</example>
        </rule>
    </rulegroup>
```

rule 01 catches correctly "Xnel vola nén" but suggest "nel la nén" (the leading "Vo "  disappears, and capitalization is wrong ).
rule 03 catches correctly "'(Znel vola) nén" and correclty suggest "Vo nel la nén" (the problem is that I will need between 2 and 4 rules using <token> to catch the same complex patter as a single <regexp>, due to the apostrophes; that was the reason I looked at a rule with <regexp> to make it simple).

Anyway, we can see the behaviour of the <suggestion> part is inconsistent, in test 01 the "vo " part is ignored, in test 02 it properly displays.

**Comment by danielnaber** [comment] 2016-03-15 09:29
I think the issue is here: https://github.com/languagetool-org/languagetool/blob/54d013824999467700e85bbde0fbc7630cd4342b/languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexPatternRule.java#L90 - we only work on the `errorText` instead of the content of the `<suggestion>` element. However, I'm not sure if I can fix this, this part of the code is in need of a serious cleanup...

**Comment by srtxg** [comment] 2016-03-15 11:23
Mmm, as I saw that the `<suggestion>` can be outside the `<message>` I replicated the first rule by just putting the suggestion outside the message.
Well, in first case (suggestion inside) the `<match no="1" />` matches the whole `<regexp>` (same way as it works with `<token>`) and text inside `<suggestion>` but outside `<match>` is ignored.

While in the second case (suggestion outside) the `<match no="1" />` matches the 1-th retained group of the regexp (not the first, but the equivalent of `\1`), and text inside `<suggestion>` but outside `<match>` is properly included.

I feel that the inconsistency depending on the placement of  `<suggestion>` should not exist.


Also, I first thought that `<match>` would have the same meaning as when used with `<token>`, eg match the whole element.

**Comment by danielnaber** [comment] 2018-03-06 22:47
> should I use <match no="0" /> to refer the whole regexp capture

I don't remember whether that works, can you try it?

**Comment by oserikov** [comment] 2018-03-06 23:32
> I don't remember whether that works, can you try it?
I've tried and found the way it works unobvious. Anyway while fixing the bug I'll follow the documented behavior.

**Comment by danielnaber** [comment] 2018-03-11 08:41
Should be fixed by @oserikov's commit.

**Closed by danielnaber** 2018-03-11 08:41 UTC
Labels: bug
