### ISSUE TITLE
SpellChecking with IgnoreTokens

### ISSUE THREAD

**Issue by paulrinckens** [languagetool-org/languagetool#859] opened 2017-12-12 10:14 UTC
When performing SpellChecking after adding IgnoreTokens to the SpellingCheckRule, LT does not detect spelling errors(missing whitespace) of the form [ignoreToken][some other correct word].

Testing done with LT Java API:
```
JLanguageTool lt = new JLanguageTool(new AmericanEnglish());
for (Rule rule : lt.getAllActiveRules()) {
  if (rule instanceof SpellingCheckRule) {
    List<String> wordsToIgnore = Arrays.asList("Jun", "Jul");
    ((SpellingCheckRule)rule).addIgnoreTokens(wordsToIgnore);
}
}
List<RuleMatch> result = lt.check("Junhome");  // --> produces no error
List<RuleMatch> result = lt.check("phonehome");  // --> does produce error
```

**Comment by danielnaber** [comment] 2017-12-12 10:27
Thanks for the report, I cannot reproduce it, though. Which version of LT are you using? Is that the complete code you need to reproduce this?

**Comment by paulrinckens** [comment] 2017-12-12 10:48
Sorry, the problem originally came up with the SwissGerman spell checker. Here is the exact code:
```
SwissGerman swissGerman = new SwissGerman();
		JLanguageTool langTool = new JLanguageTool(swissGerman);
		
		for (Rule rule : langTool.getAllActiveRules()) {
		  if (rule instanceof SpellingCheckRule) {
		    List<String> wordsToIgnore = Arrays.asList("Jun", "Jul");
		    ((SpellingCheckRule)rule).addIgnoreTokens(wordsToIgnore);
		}
		}
		List<RuleMatch> result = langTool.check("JunHaus");  // --> produces no error
		List<RuleMatch> result2 = langTool.check("JunHaaus");  // --> produces error
		List<RuleMatch> result3 = langTool.check("JuniHaus"); // --> produces error
		
		System.out.println(result.size()); // --> 0
		System.out.println(result2.size()); // --> 1
		System.out.println(result3.size()); // --> 1
```
Sorry for the confusion. Hope you can reproduce it now.

**Comment by danielnaber** [comment] 2017-12-12 11:10
Thanks, I can reproduce now. A short analysis shows that this is caused by `German SpellerRule.ignoreCompoundWithIgnoredWord()`, which considers "JunHaus" a compound like "Junhaus". Maybe accepting ignored words as compound parts goes too far in this case.

**Comment by paulrinckens** [comment] 2017-12-12 11:33
Thanks for the quick reply and analysis. As this is a private method call, currently there is no way to work around this without changing the source, right?

**Comment by danielnaber** [comment] 2017-12-12 11:38
Well, `ignoreWord()` (which calls `ignoreCompoundWithIgnoredWord()`) is protected, so you could maybe overwrite that (and copy some code).

**Comment by f-knorr** [comment] 2017-12-14 19:42
I have comitted a partial fix: Words of the form [ignoreToken][some other correct word] are detected as an error if [some other correct word] starts with an upper-case letter. Is this sufficient?

**Comment by f-knorr** [comment] 2017-12-19 18:56
As the original problem was addressed with 2 commits, I close this issue for now. If there are stll problem, please reopen or open another issue with detailed description of the problem.

**Closed by f-knorr** 2017-12-19 18:56 UTC
