### ISSUE TITLE
LibreOffice - Add-on crash

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3863] opened 2020-11-16 07:37 UTC
Hello!

Last night there was no nightly, but I have installed the one from two days ago.

It crashed while editing a .docx in LibreOffice:
![lt_libreoffice_addon_crash_20201116](https://user-images.githubusercontent.com/5192600/99224633-9a4ea380-27de-11eb-8c7c-33ffd3e15d00.png)

**Comment by danielnaber** [comment] 2021-01-08 16:40
Fixed according to commit log, so can this issue be closed?

**Comment by FredKruse** [comment] 2021-11-18 19:22
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:22 UTC
Labels: office-integration
