### ISSUE TITLE
LibreOffice add-on performance

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2614] opened 2020-03-24 15:39 UTC
Using `jvisualvm` and Marco's test document from #2602, I get this:

![screenshot-2020-03-24-16:31](https://user-images.githubusercontent.com/857004/77445084-ecc0f700-6dec-11ea-8f18-dc9fae1e9eb4.png)

This indicates a lot of time is spent in `FlatParagraphTools.getCurNumFlatParagraph()`. @FredKruse are you aware of this? So far, we assumed checking is slow because the documents are just large, but this seems to show there's quite some LibreOffice-specific overhead.

**Comment by FredKruse** [comment] 2020-03-30 11:52
@danielnaber please test, if the new release solves this issue

**Comment by FredKruse** [comment] 2020-04-22 14:20
@danielnaber I did some testing. The issue is solved. Please close the issue.

**Closed** 2020-04-22 14:21 UTC
Labels: office-integration
