### ISSUE TITLE
Spell-checking in LibreOffice

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3202] opened 2020-07-04 11:47 UTC
First, a question. What does this option ("Add LanguageTool dictionary") do exactly?
![imatge](https://user-images.githubusercontent.com/4289501/86511405-1c729880-bdf9-11ea-8d34-3e2b3c12fe91.png)

In LibreOffice, we disable the spelling rule because we need a spelling dictionary (apart from the tagger dictionary), and that would make the LanguageTool distribution file too large.  
But, in some languages (Catalan, Spanish and French), now the tagger dictionary is used for spelling, and there is no need for another dictionary. That means that in these languages we can do spell-checking in LibreOffice, which is probably better than the Hunspell spell-checking (significantly better in Spanish, and soon also in French when we make some improvements). 
Now the spelling rule is available for these languages in LibreOffice, but disabled by default (see: https://github.com/languagetool-org/languagetool/blob/98789f43a9cfbae0697aa43ffed66f660db827ef/languagetool-office-extension/src/main/java/org/languagetool/openoffice/MultiDocumentsHandler.java#L605)
If users want to use the LanguageTool spell-checking in LibreOffice, they need to disable the Hunspell spell-checking and enable the spelling rule in the LT settings (browsing through the grammar rules). Could we provide an option (only available for some languages) to do this more easily in the settings or in the menus?

This is a related issue: https://github.com/languagetool-org/languagetool/issues/3169. Personal dictionaries are not available to the LanguageTool spelling rule. I don't know if this can be fixed.

**Comment by danielnaber** [comment] 2020-07-04 11:59
ping @FredKruse

**Comment by yakovru** [comment] 2020-07-06 17:38
https://github.com/languagetool-org/languagetool/issues/292

I think added.txt should be removed from this feature. The added.txt file may contain word forms that should not be offered as correct for spelling.

**Comment by FredKruse** [comment] 2020-07-06 18:07
The description is correct. The spell check in LO is done by the internal spell checker. The spelling rules of LT are disabled. To add words to the LO spell checker, that are treated in LT as correct, an internal dictionary is added that contains all words of spelling.txt and added.txt.
@yakovru I'm not familiar with most of the languages supported by LT. I tested the functionality in German and English language. Could you please give me an example for word forms, that should not be used?

**Comment by yakovru** [comment] 2020-07-06 18:42
> Could you please give me an example for word forms, that should not be used?
It may be commonly confused words, that need POS tag to correct working some grammar rules. 
It is necessary to provide the possibility for the language maintainer to disable spell suggestion from added.txt

**Comment by jaumeortola** [comment] 2020-07-07 15:22
Then, the option "Add LT dictionary to LibreOffice spell check" adds the words in added.txt and spelling.txt to LibreOffice. 
What @yakovru is saying makes sense: better to use only words in spelling.txt. That is more consistent with what is done in LanguageTool itself. In some languages all tagged words are ignored in spelling, but not in every language (in English it is not done). 

Any way, for me spelling.txt and added.txt are just temporary solutions before the LanguageTool dictionaries are updated, and spelling.txt and added.txt are regularly emptied. Therefore, this feature is not very useful.

 The solution I am proposing (and using) for Catalan, Spanish and French is more general. The remaining question is this, @FredKruse:
>If users want to use the LanguageTool spell-checking in LibreOffice, they need to disable the Hunspell spell-checking and enable the spelling rule in the LT settings (browsing through the grammar rules). Could we provide an option (only available for some languages) to do this more easily in the settings or in the menus?

**Comment by FredKruse** [comment] 2020-09-26 14:11
The problem is solved, I think. Please close the issue.

**Closed** 2021-01-03 16:47 UTC
Labels: office-integration
