### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ColeBantam** [languagetool-org/languagetool#4046] opened 2020-12-19 11:50 UTC
![LibO_Version](https://user-images.githubusercontent.com/34094836/102688690-a4f2c300-41f8-11eb-9b02-10d1441c769a.PNG)
![exeption](https://user-images.githubusercontent.com/34094836/102688697-af14c180-41f8-11eb-9a32-2c486e1968aa.PNG)

**Comment by danielnaber** [comment] 2020-12-19 14:01
Does it still happen with the latest snapshot? https://internal1.languagetool.org/snapshots/LanguageTool-20201218-snapshot.oxt

**Comment by FredKruse** [comment] 2020-12-22 10:35
@danielnaber: As far as I see, this bug shouldn't happen with the latest snapshots. I did a lot of changes (also at this part of code). The latest version should much more stable.

**Comment by ColeBantam** [comment] 2020-12-22 12:07
I first impression was, that the current snapshot is more stable, but then ....

![Exeption_with_current_snapshot](https://user-images.githubusercontent.com/34094836/102886944-56426480-4456-11eb-93af-c7bd8f472f23.png)

Ahhh, the exact same exeption once again...

**Comment by FredKruse** [comment] 2020-12-22 17:09
@ColeBantam : The issue should be solved. Please test it tomorrow.

**Comment by ColeBantam** [comment] 2020-12-23 10:34
its getting more and more stable... BUT .....

![next-exeption](https://user-images.githubusercontent.com/34094836/102987580-da5a2200-4512-11eb-9b60-1e2277a549db.PNG)

**Comment by FredKruse** [comment] 2020-12-24 12:53
The issue should be solved. Please test tomorrow.

**Comment by ColeBantam** [comment] 2020-12-24 13:06
Thanks, I'll test tomorrow.
Merry Christmas 🎅 to the Languagetool-Team :)

**Comment by ColeBantam** [comment] 2020-12-25 11:22
My X-Mas Present :D

![next-exeption2](https://user-images.githubusercontent.com/34094836/103133632-cdbd0180-46ab-11eb-9b02-c1f979c2d6c1.PNG)

**Comment by FredKruse** [comment] 2020-12-26 12:03
Hopefully my X-Mas present is a little bit nicer ;)
Please test it tomorrow.

**Comment by ColeBantam** [comment] 2020-12-26 12:21
> Hopefully my X-Mas present is a little bit nicer ;)
> Please test it tomorrow.

Thanks, I'll test your Present tomorrow :D

Meanwhile I stumbled upon another exception ...

![next-exeption3](https://user-images.githubusercontent.com/34094836/103151284-ea753a00-477c-11eb-99a7-09b140cd5185.PNG)

This time it didn't happen on a fancy test-situation, but simply on writing a simple letter with 399 English words.

**Comment by FredKruse** [comment] 2020-12-26 12:31
Ok, this seems to be the same bug. Please test tomorrow, if it is solved.

**Comment by ColeBantam** [comment] 2020-12-26 12:43
The same? ok. Looked so different to me... Ill try tomorrows build.

**Comment by ColeBantam** [comment] 2020-12-28 10:55
Current Snapshot seems stable for the moment. Didn't do a lot of real world text processing in Writer yesterday though. But tests with my big test-document were fine.

**Comment by ColeBantam** [comment] 2021-01-01 18:06
Hello again :)

Here is my new years day exception :D

![next-exeption4](https://user-images.githubusercontent.com/34094836/103443967-6f23f480-4c64-11eb-89be-6d46d6dde775.PNG)

**Comment by FredKruse** [comment] 2021-01-01 19:15
Could you please describe, at what user action this exception arise?

**Comment by ColeBantam** [comment] 2021-01-01 20:55
> Could you please describe, at what user action this exception arise?

I think I was deleting the content from several rows from the first of 4 tables in a writer document. Or it happend while cutting & pasting content from one buch of rows to another. Not sure at what step exactly it happened.

**Comment by FredKruse** [comment] 2021-01-02 16:47
I just committed a small workaround to fix the issue. This will solve the problem above. But there seams to be a general problem with the handling of tables. I will test the problem in the next weeks.

**Comment by ColeBantam** [comment] 2021-01-02 17:06
Thanks :) So I'll download the new snapshot tomorrow...

**Comment by ColeBantam** [comment] 2021-01-04 09:41
Okkkkkkkeeyyyy, 5.3 Snapshot crashes on every writer start...

![next-exeption5](https://user-images.githubusercontent.com/34094836/103521620-5b051080-4e79-11eb-81a9-f6a1b12b3442.png)

**Comment by ColeBantam** [comment] 2021-01-04 09:46
LanguageTool-20210102-snapshot seems to work for the moment...

**Comment by FredKruse** [comment] 2021-01-04 09:51
@danielnaber: Do you have any idea? I reported this problem already at issue #4088. I am not able to start the extension. It is not possible to do any tests. It seems to be a problem with the AbstractUnitConversionRule.

**Comment by danielnaber** [comment] 2021-01-04 11:36
#4088 has been fixed now

**Comment by ColeBantam** [comment] 2021-01-05 10:00
LanguageTool-20210104-snapshot seems ok so far.

**Comment by ColeBantam** [comment] 2021-01-08 15:34
Even though it might not be very useful to you, because it doesn't contain any debug information, I wanted to share the last crash with you:

![next-exeption6](https://user-images.githubusercontent.com/34094836/104032672-c418bb00-51ce-11eb-8e5e-60b1ecd4d31e.png)

It's a nice coincidence, that the crash happened while I was writing a news-article about the current languagetool-plugin :D

BTW: If it gets annoying that I reuse that bug on and on, just tell me, then Ill create a new bug for the next crash.

**Comment by ColeBantam** [comment] 2021-01-08 15:38
And the next exception, this time more verbose luckily ...

![next-exeption7](https://user-images.githubusercontent.com/34094836/104033547-f4148e00-51cf-11eb-9160-d32fbe3cd04b.png)

**Comment by danielnaber** [comment] 2021-01-08 15:48
The snapshot gets daily updated, so if you use that, I suggest updating regularly.

**Comment by ColeBantam** [comment] 2021-01-08 15:54
I only use the snapshots because I was being told to do so by you 20 days ago :D
And because the 5.2 release doesn't contain the latest fixes for all the exceptions in this bugreport. So I doubt that its useful to you, if I use the stable build and post exceptions that happen in that one...?
I just upgraded to the last snapshot ...

**Comment by danielnaber** [comment] 2021-01-08 16:44
> So I doubt that its useful to you, if I use the stable build and post exceptions that happen in that one...?

Well, we should try to fix bugs in 5.2, as it's supposed to be a stable release. @FredKruse What do you think, should we publish a 5.2.1 release?

**Comment by ColeBantam** [comment] 2021-01-08 17:13
and once again with the current snapshot ...

![next-exeption8](https://user-images.githubusercontent.com/34094836/104044122-24165e00-51dd-11eb-821b-99297929373b.png)

**Comment by ColeBantam** [comment] 2021-01-08 17:18
> Well, we should try to fix bugs in 5.2, as it's supposed to be a stable release. @FredKruse What do you think, should we publish a 5.2.1 release?

A 5.2.x branch with focus on stability would be really very welcome ... The LibreOffice 7.x and LanguageTool combination is really a pain so far ... :/ Never had that much issues with previous LibO / LanguageTool combos.

**Comment by FredKruse** [comment] 2021-01-09 18:54
In this discussion there are three different problems, I think:

1. OutOfMemoryError: This is not an LT error. It is caused by missing heap space. Properly you try to work with a very huge document or with many large documents in the same session. LT uses caches to handle rules on text level. They grow with the size of the loaded documents. In LO you can expand the size of heap space by  adding the parameter -Xmx1G (for 1 GB, -Xmx2G for 2 GB, etc.) as java parameter in LO in Tools/Options/Advanced.
2. Release 5.2.1: Two bugs were detected, related to release 5.2. One was fixed with commit https://github.com/languagetool-org/languagetool/commit/26080c3688ccf2dd7281e1dd928bbac9164a9fd2. If we create a branch 5.2.1, we should start with this release, but I have to add another small fix, before we release it. @danielnaber: could you create such a branch?
3. NullPointerException on 5.3-snapshot: The code has changed meanwhile. I can not reproduce it. I did some changes at the core of the engine in 5.3 (hopefully the last time) to optimize cache handling. @ColeBantam: Please test it with the newest snapshot and report the bugs here. It would be much easier, if we could fix the bugs of 5.3 before it will be released.

**Comment by danielnaber** [comment] 2021-01-09 20:32
> could you create such a branch?

I think you have permission to do that yourself. Just start from tag `v5.2`, not from current `master`.

**Comment by FredKruse** [comment] 2021-01-10 19:06
@danielnaber: I created the branch https://github.com/languagetool-org/languagetool/compare/v5.2.1-branch and did the changes, which solves the reported bugs regarding the v5.2. I am not familiar with the changes, which have to be done for versioning. Could you please add the changes?

**Comment by danielnaber** [comment] 2021-01-11 15:12
@FredKruse The release is now out (also see https://forum.languagetool.org/t/ann-languagetool-5-2/6465/2?u=dnaber).

**Comment by ColeBantam** [comment] 2021-01-12 12:43
I wish there would have been a possibility to test 5.2.1 prior to release :/

![next-exeption9](https://user-images.githubusercontent.com/34094836/104315722-ae133f00-54db-11eb-98f2-2ad691c5783d.png)

@FredKruse 
Thanks for the hint to the heap-size allocation in LibO. Do you know what default size LibO uses and if its different in x86 and x64 builds?

**Comment by ColeBantam** [comment] 2021-01-12 13:33
While experimenting with different heap space settings:

![next-exeption10](https://user-images.githubusercontent.com/34094836/104320864-28938d00-54e3-11eb-8f17-57167e3a50ad.png)

**Comment by ColeBantam** [comment] 2021-01-12 13:43
Next exception while doing tests with different heap space settings ... Seems related but not the same as before...

![next-exeption11](https://user-images.githubusercontent.com/34094836/104321939-92f8fd00-54e4-11eb-964c-19a4b318fd98.png)

**Comment by FredKruse** [comment] 2021-01-13 10:33
Did all exceptions happens, when you're running the grammar check dialog?

**Comment by ColeBantam** [comment] 2021-01-13 10:36
Yes, I think all the exceptions yesterday were triggered by the "Text erneut prüfen (Umschalt + F7)"-function.

**Comment by FredKruse** [comment] 2021-01-13 17:00
The reported bugs are fixed. Hopefully, I fixed the general problem with the check dialog.
@danielnaber: Could we put an oxt file at some place, that it can be tested, before we release it?
@ColeBantam: Would you be able to test the new version, before we release it?

**Comment by ColeBantam** [comment] 2021-01-13 17:35
Of course I would test a snapshot with new fixes.

**Comment by danielnaber** [comment] 2021-01-13 21:39
Please give it a try: https://languagetool.org/download/LanguageTool-5.2.2-beta.oxt  - note that it will be called "5.2" in the extension manager, it's "5.2.2" in LanguageTool's "About" window.

**Comment by ColeBantam** [comment] 2021-01-14 11:02
5.2.2 looks very promising :) I can't trigger any exception so far with tests. I'd like to use in in real world for a couple of days though before releasing it.

Also the tipp with the "about" window gave me a good insight :) Now I can say, that 32Bit LibO uses 256MB heap space by default. Using 512MB works too. 1024M (or 1G) does NOT work in LibO, at least languagetool doesn't work with that setting. Maybe bigger heap spaces work in 64bit version, but I guess that shouldn't be necessary. My huge-doc (400k words) is a testfile, I don't think thats a typical real world size for most LibO users :D

**Comment by ColeBantam** [comment] 2021-01-15 15:47
Short Update on the 5.2.2 Beta Plugin:
I had two fatal LibO crashes today while working on my newsletter document. Since there was no visible exception I can't tell if it was triggerd by the plugin or LibO itself. After the first crash LibO offered the chance to send an Report to the developers which I did. The second crash did not offer anything. I then removed the -Xmx512M-Parameter and the next 50 minutes in LibO were flawless. No more visible exceptions from the plugin so far.

**Comment by ColeBantam** [comment] 2021-01-18 10:15
Its a big improvement compared to 5.2.1, that speaks for release.
The two fatal crashes might speak against it, if they were triggered from LangTool, which I don't know.
As I don't think we will be able to really say what was responsible for the crashes, I'd say better releasing it, as it fixes serious bugs.

**Comment by FredKruse** [comment] 2021-01-18 14:14
The crashes are a mystery to me. I have worked a lot with the latest version of LT without any crash of LO. However, I am using LO 7.0.4 64-Bit Linux version. The heap space is something between 512 MB and 1 GB depending on the size of the document (It allocates automatically without any use of parameters). Maybe LO is not able to allocate enough heap space, and that is the reason for the crashes.
It seems there are no more LT exceptions now. So, I think, we should release 5.2.2 now.

**Comment by danielnaber** [comment] 2021-01-19 08:01
5.2.2 is now online at https://extensions.libreoffice.org/en/extensions/show/languagetool and https://extensions.openoffice.org/en/project/languagetool. If there are no complaints, I will activate the update from LibreOffice's extension manager (which still offers 5.1).

**Comment by ColeBantam** [comment] 2021-01-20 16:38
Thanks for all your efforts and the 5.2.2 Release :)

But to make it not too boring for you, here is a new exception :D

![next-exeption12](https://user-images.githubusercontent.com/34094836/105206003-24e8b180-5b46-11eb-86ae-be4676fbcdfe.png)

This one came up while my tests with LibO 7.1.0.2, so the Image from my first post here is not correct on this exception. Shall I make a new bugreport for issues in LibO 7.1.x?

**Comment by FredKruse** [comment] 2021-01-21 18:18
@ColeBantam: Thank you for testing, you've found another bug.
@danielnaber: I am not sure, if we should release a new version. The issue was a real bug, but it should happen very rarely. I think, a "check text again" was initiated and LT was faster than LO (LO has not created a xComponent at the moment when LT asked for it).

**Comment by ColeBantam** [comment] 2021-01-22 11:17
Last bug:
Your decision if to release another 5.2.x bugfix :) But, is there a 5.2.x Snapshot that contains a fix that I can test?

Heap Space Issue:
I guess the heap space issue is a LibO bug? As FredKruse mentioned, LibO allocates the heap space dynamically. LibO itself seems to check the heap space size on start, so if I set -Xmx to more then 750M I get a message that JRE is "corrupt". A bit misleading, but ok. But it seems that LibO itself allocates more then 750M. That must have been the culprit, why LangTool didn't start at one of my last tests. So, is there something that can be done by LangTool, or do I have to report that in LibO Tracker? Btw, this all only applies to the 32Bit version of course. In 64Bit LibO I successfully tested heap spaces up to 16G.

**Comment by danielnaber** [comment] 2021-01-22 11:40
Current snapshots are always available at https://internal1.languagetool.org/snapshots/

**Comment by ColeBantam** [comment] 2021-01-22 11:43
> Current snapshots are always available at https://internal1.languagetool.org/snapshots/

I know, but these are master branch snapshots, not 5.2.x branch snapshots.

**Comment by danielnaber** [comment] 2021-01-22 11:45
> I know, but these are master branch snapshots, not 5.2.x branch snapshots.

That's right, we'd need to build branch snapshots manually.

**Comment by ColeBantam** [comment] 2021-01-22 11:48
> That's right, we'd need to build branch snapshots manually.

So it depends on your decision if there will be another 5.2.x release or not. If you want to further stabilize 5.2 branche, a snapshot containing the last fix would be great. Otherwise I would change to testing current snapshots again.

**Comment by ColeBantam** [comment] 2021-02-16 18:00
Hello again :)
Its been a while, but finally I have a new exception:

![next-exeption13](https://user-images.githubusercontent.com/34094836/108102553-f8fb1600-7088-11eb-93c1-38d6e98c9a91.png)

Is this a LT-Bug or can I use it as evidence of a LibO Bug in assigning Java Heapspace? Because it happened while I tried to find a way to reproduce the Problem in LibO that it allocates more heapspace dynamically than it can handle. (in 32Bit LibO).

**Comment by FredKruse** [comment] 2021-02-17 13:19
The Problem with the spell and grammar check dialog should be solved by a change I committed today. Please test it with 5.3-snapshot tomorrow.
The Out-Of-Memory-Error seems to be caused by using the "Use more than one CPU-Core" option. If you choose this option, LT runs in multithread mode, which uses also more memory, I think.

**Comment by ColeBantam** [comment] 2021-02-17 14:11
Thanks for the commit regarding non-responding-spellcheck-window :) Ill test the snapshot tomorrow.

Regarding the exception: Is it possible to say, if the exception was caused by LT itself, or maybe by LibO because of allocating to much heapspace and thus killing java?

If it was a LT-Bug, it should not be skipped just because it was with an "abnormal" setting. I know that it is a "warning" next to the multi-thread-option, but sooner or later that option should become default, shouldn't it? Or will it remain an "experimental feature" forever?

**Comment by ColeBantam** [comment] 2021-02-18 14:37
> Please test it with 5.3-snapshot tomorrow

Well, didnt take too long for the first exception...

![next-exeption14](https://user-images.githubusercontent.com/34094836/108371863-7b591680-71fe-11eb-8320-f92a46d9f088.png)

Because heap-space is mentioned in the exception. I cant really do anything about that. Its the 32Bit version of LibO and heapspace is not limited by me. So LT has about 750MB, more is not possible in the 32bit version. Multi-threading is already disabled! 

![next-exeption15](https://user-images.githubusercontent.com/34094836/108372296-f4586e00-71fe-11eb-9072-8c2704ad910f.png)

After the first exception I started LibO again and began writing this comment and some other stuff. When I looked back a few minutes later, the second exception already was there, without me doing anything in LibO!

I have to revert back to 5.2.2. now, because I need to do some work which is impossible with this snapshot.

**Comment by FredKruse** [comment] 2021-02-22 08:35
I have to test this. It will take a while I have to build a 32 bit test environment. Probably some features have to reduced for the 32 Bit version.

**Comment by ColeBantam** [comment] 2021-02-22 09:07
Thanks for having a look into that. But before reducing functionality for 32bit hosts, have a look at bug #4413.

**Comment by ColeBantam** [comment] 2021-02-22 09:38
This just happened in LibO 7.1.0.2. Is this a LibO bug? Because C++ is mentioned and LT is (I think) pure Java...

![next-exeption16](https://user-images.githubusercontent.com/34094836/108689832-ddb16000-74f9-11eb-8b51-1f5d560aae23.png)

**Comment by ColeBantam** [comment] 2021-02-22 09:41
BTW: Is there a LT version that has a know memory leak, which I could use to demonstrate the LibO heap space allocation bug? Or any other idea how I could make LibO to allocate more and more heap space till it reaches the maximum it can handle? I need something to make that reproducible to file a bugreport in LibO Tracker...

**Comment by FredKruse** [comment] 2021-02-23 12:58
I am a little at a loss. I tested LT on a 32-bit Version of Linux Mint (19.2). The default configuration is LO 6.0.7.3. Openjdk 11.0.10). The latest snapshot is used. Beside the default options I added some optional style rules to generate as many matches as possible and switch to multi thread mode. I loaded four documents (real world texts), each one 300 pages approximately, circa 1200 pages at all. The reserved heap space grows up to more than 1 GB, the used was around 900 MB. LT took a long time, but it runs without crash.
So I wonder what is wrong on your machine? Could there be a problem with your RAM? The last bug is very strange it is triggered by a very old part of code, and it happens in LO itself. It seems also related by a fail of allocation of memory.

**Comment by ColeBantam** [comment] 2021-02-24 16:11
Hi Fred. Thanks for putting so much work into this :)

I also did (and currently do) a lot if tests with LT, and I have some news. But I will post those to the Performance-Bug, as its mostly about heap space.

But I also have a new exception that quite sure really is a LT bug: 

![LibO_7 0 4 2_32Bit_Java10_CurrentSnapshot-Crash](https://user-images.githubusercontent.com/34094836/109029258-f15bf280-76c2-11eb-9778-34f9faa0a999.PNG)

On Windows this happens 100% reproducible on two different machines. Just open LibO, open a new empty document and close the document (but NOT LibO).

More in #4413

**Comment by ColeBantam** [comment] 2021-03-01 18:13
Does the above commit also fix the nullpointer exception?

**Comment by danielnaber** [comment] 2021-07-26 18:08
User feedback:

> wenn ich Text lösche dann kommt seit der installation von Version 5.4 (2021-06-25 09:43:51 +0000) eine java.lang.ArraayIndexOutOfBoundsException

![javaLangError](https://user-images.githubusercontent.com/857004/127037424-ff4910a3-7702-4524-87ce-dcc9849899a4.png)

**Comment by ColeBantam** [comment] 2021-07-27 08:51
I have just tested 5.4 Plugin in LibO 7.1.5, and I didn't notice any exceptions so far, even not on deleting text.

My Specs: Windows 10 20H2, 64Bit, Azul Systems Java 12.0.2

But I noticed two other things that might be a problem:

1.) I couldn't trigger the "using too much heap space → switch to paragraph only mode"- Message. Don't know if the message has been removes, but the functionality is still there, or if the message should show up?

2.) The "LanguageTool" Menu in EXTRAS is greyed out and not accessible though. That means I can't have an eye on heap space usage aso..

**Comment by FredKruse** [comment] 2021-08-01 12:09
The OutOfBundsException arises if the whole text is deleted. This problem is solved now.
Regarding the last comment:
I can't reproduce the second point. If a Writer-window is open, the LanguageTool-menu should be accessible.

**Comment by ColeBantam** [comment] 2021-08-04 12:28
> I can't reproduce the second point. If a Writer-window is open, the LanguageTool-menu should be accessible.

I solved the menu-problem by deleting this file:
"C:\Users\UserName\AppData\Roaming\LibreOffice\4\user\config\soffice.cfg\modules\swriter\menubar\menubar.xml"

**Comment by ColeBantam** [comment] 2021-09-30 17:22
![LangTool-Exeption-2021 09 30](https://user-images.githubusercontent.com/34094836/135501849-be77550a-1bc7-4118-a818-fe23611db1ec.png)
Exeption after deleting a page-break (manueller Seiten Umbruch).

**Comment by FredKruse** [comment] 2021-10-01 07:48
Could you please test, if the same bug exists in the latest 5.5-snapshot: 
https://internal1.languagetool.org/snapshots/LanguageTool-20210930-snapshot.oxt
The problem should be already solved, I think.

**Comment by ColeBantam** [comment] 2021-10-04 08:29
I can't reproduce it in LT5.4, so I can't say if the Snapshot fixes the problem.

**Comment by FredKruse** [comment] 2021-11-18 19:19
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:19 UTC
Labels: office-integration
