### ISSUE TITLE
[pl] Missing biblical names of the scriptures 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3620] opened 2020-09-25 09:33 UTC
Copy of https://forum.languagetool.org/t/not-all-biblical-names-of-the-scriptures-are-detected-in-polish-false/6168

These biblical names cause spelling errors in Polish:
Micheasza
Sofoniasza
1 Koryntian
2 Koryntian
Galatów
Filipian
Kolosan
1 Tesaloniczan
2 Tesaloniczan

**Comment by baarsrj** [comment] 2020-09-26 13:11
My Polish dictionary does not contain these word either. I suggest we find proof for these Polish Bible book names.
There seem to be multiple versions.
Here is a page that contains some book names in Polish
https://www.wordproject.org/bibles/pl/index.htm

Of this page, this are the words that are not accepted:
Samuelowa

Ezdraszowa
Nehemijaszowa
Ijobowa
Jeremijasz
Jeremijaszowe
Ezechyjel
Danijel
Abdyjasz
Micheasz
Abakuk
Sofonijasz
Aggieusz
Zacharyjasz
Malachyjasz
Koryntów
Galatów
Efezów
Filipensów
Kolosensów
Tesalonicensów
Tesalonicensów
Jakóba
Judasa

**Comment by milekpl** [comment] 2022-02-12 20:56
These are very old and non-standard versions (the ones mentioned by @baarsrj). The first post seems also pretty non-standard but I need to make sure ("Koryntian" should be fine)

**Comment by milekpl** [comment] 2022-02-24 11:13
OK, it seems that the problem is there. Some names are missing because they were not included in the original spelling file (they are POS tagged, however). I'll update the spelling dictionary using the newest files from sjp.pl project.

**Comment by milekpl** [comment] 2022-04-15 09:38
I'm updating the spelling dictionary. The following words above are not spelled according to current spelling rules (archaic versions): 

> Ezdraszowa
Nehemijaszowa
Ijobowa
Jeremijasz
Jeremijaszowe
Ezechyjel
Danijel
Abdyjasz
Abakuk
Sofonijasz
Aggieusz
Zacharyjasz
Malachyjasz
Koryntów
Efezów
Filipensów
Kolosensów
Tesalonicensów
Tesalonicensów
Jakóba
Judasa

The rest will be included in the update.

**Closed** 2022-04-15 09:42 UTC
Labels: bug, Polish
