### ISSUE TITLE
jre error

### ISSUE THREAD

**Issue by oumar17** [languagetool-org/languagetool#3206] opened 2020-07-05 22:19 UTC
as per this link bellow, a screen shoot of the error warning is provided
after Changing the JRE from openJDK   11, 13, 14 the same error persist
it LO version 6.4.4.2 running on ubuntu 20.04 and the file type is docx files combined in as master doc file of LO.
a link to the screenshoot of the error is provided
link: https://florycq-my.sharepoint.com/:i:/g/personal/m12919_vip365_ca/EeVpSakwRDpJjNC5gwJFqdEBW2DSYqxZ7ilXF-9h_6xhOQ?e=aiQZSI

**Comment by danielnaber** [comment] 2020-07-06 10:01
This is a duplicate of #3170

**Closed by danielnaber** 2020-07-06 10:01 UTC
