### ISSUE TITLE
java.lang.RuntimeException: Could not check sentence (language: English)

### ISSUE THREAD

**Issue by KwanWaiChung** [languagetool-org/languagetool#6482] opened 2022-03-28 09:09 UTC
I get an error when I am using languagetool on a tex document with the sentence "However, SL does not consider the future effects of the current decision which may lead to sub-optimal behaviour \citep{henderson_hybrid_2008}."

It can be reproduced by creating a document with the above sentence.

I am using the stable 5.6 version in Mac installed by brew.

**Comment by danielnaber** [comment] 2022-03-28 10:11
Do you have a more verbose error message? I cannot reproduce the error, it might be fixed in the current version already.

**Comment by KwanWaiChung** [comment] 2022-03-28 14:17
@danielnaber Sure, the verbose error message is below.

Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English): <sentcontent>However, SL does not consider the future effects of the current decision which may lead to sub-optimal behaviour \citep{henderson_hybrid_2008}.
</sentcontent>
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:217)
	at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:1002)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:929)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:914)
	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:108)
	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:84)
	at org.languagetool.commandline.Main.runOnFile(Main.java:192)
	at org.languagetool.commandline.Main.main(Main.java:464)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English): <sentcontent>However, SL does not consider the future effects of the current decision which may lead to sub-optimal behaviour \citep{henderson_hybrid_2008}.
</sentcontent>
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:214)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English): <sentcontent>However, SL does not consider the future effects of the current decision which may lead to sub-optimal behaviour \citep{henderson_hybrid_2008}.
</sentcontent>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	... 9 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: English): <sentcontent>However, SL does not consider the future effects of the current decision which may lead to sub-optimal behaviour \citep{henderson_hybrid_2008}.
</sentcontent>
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:2026)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1901)
	at org.languagetool.MultiThreadedJLanguageTool.lambda$performCheck$1(MultiThreadedJLanguageTool.java:200)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at org.languagetool.rules.en.CompoundRule.isMisspelled(CompoundRule.java:162)
	at org.languagetool.rules.AbstractCompoundRule.isCorrectSpell(AbstractCompoundRule.java:255)
	at org.languagetool.rules.AbstractCompoundRule.filterReplacements(AbstractCompoundRule.java:176)
	at org.languagetool.rules.AbstractCompoundRule.match(AbstractCompoundRule.java:150)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1409)
	at org.languagetool.JLanguageTool.access$1500(JLanguageTool.java:77)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1986)
	... 8 more

**Comment by KwanWaiChung** [comment] 2022-03-28 15:38
Actually, being a tex document or not is not relevant. To reproduce this problem, I put the line `However, SL does not consider the future effects of the current decision which may lead to sub-optimal behaviour \citep{henderson_hybrid_2008}.` in a txt file. Then I just run ` languagetool test.txt`. This will produce the error I showed above. Hope this helps.

**Comment by KwanWaiChung** [comment] 2022-03-28 15:47
Just to follow up the issue, actually if I only include the word `sub-optimal` is enough to reproduce the problem... That is weird

**Closed as completed** 2022-03-28 15:56 UTC

**Comment by samarulmeu** [comment] 2022-04-08 06:39
Actually I think it should be reopened. I use 5.7 (on Alpine Linux) and thee error still shows using `-l en` , `-l en-US` or `-l en-GB`. Using `-l ro-RO` I have no problem.
