### ISSUE TITLE
TL5.9 Java Runtim errors on LibreOffice Version 7.4 - 7.4.3.1 on MacBookPro M1 MacOS  

### ISSUE THREAD

**Issue by hsm4** [languagetool-org/languagetool#7418] opened 2022-11-11 09:29 UTC
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/39520801/201309754-e700c88c-35b5-48cb-81ec-392d7f921f21.png">

**Comment by danielnaber** [comment] 2022-11-11 10:23
Duplicate of #7045

**Closed by danielnaber** 2022-11-11 10:23 UTC
