### ISSUE TITLE
[en] false alarms ADMIT_ENJOY_VB

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3236] opened 2020-07-10 05:05 UTC
> Roughly two-thirds of the entire world's cocoa is produced in West Africa, with 43% sourced from Côte d'Ivoire, where child labor is a common practice to obtain the product.

> I have a great mind to do that myself.

> I have a good mind to visit the Silk Road.

> The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents.

> I have a good mind to visit the Silk Road.

> However, it was still a common practice to have single sponsor shows, such as The United States Steel Hour.

> I am not trying to change your mind about the money but want you to know that their are employees with feelings and a good mind to think things through and feel you are justified in accepting some reward for the dynasty you have helped to build.

> Lovecraft emphasised the point by stating in the opening sentence of the story that "The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents."

> This also happened prior to Order No. 888, with a number of companies sitting on their hands, using the time delay to protect existing positions, while whipping up State regulators' fears of jurisdictional shift as necessary to boost their own position.

Found in https://internal1.languagetool.org/regression-tests/via-http/2020-07-10/en/result_grammar_ADMIT_ENJOY_VB[1].html

**Comment by tiff** [comment] 2020-07-10 05:06
Also see https://internal1.languagetool.org/regression-tests/via-http/2020-07-10/en/result_grammar_ADMIT_ENJOY_VB[3].html

> Check your credit report to identify errors that could hurt your chances.

...

**Comment by MikeUnwalla** [comment] 2020-07-10 08:48
I have reverted the changes (https://github.com/languagetooler-gmbh/languagetool-premium/issues/1564) that cause these errors. I will add the examples to the disambiguation rules, and then try again to improve the disambiguation.

**Comment by MikeUnwalla** [comment] 2020-07-10 15:11
I will also check all the results from https://internal1.languagetool.org/regression-tests/via-http/2020-07-10/en/index.html and add examples to prevent future regression errors.

**Comment by MikeUnwalla** [comment] 2020-07-10 16:58
As best I can tell, I have added all the applicable examples.

**Comment by MikeUnwalla** [comment] 2020-07-11 10:29
I am closing this issue, because it is about false alarms which have been fixed (by the reversion).

**Closed by MikeUnwalla** 2020-07-11 10:29 UTC
Labels: English
