### ISSUE TITLE
[pt] warn about substantives that became verbs

### ISSUE THREAD

**Issue by Konfekt** [languagetool-org/languagetool#610] opened 2016-11-16 14:44 UTC
This is to keep track of 

https://gist.github.com/Konfekt/ec7bb1360061ca130b51776bae586fc7 

that lists accented substantives and their accent less verb forms, thus slipping through the spell checker and already partially implemented by https://github.com/languagetool-org/languagetool/commit/00738e93f40a69226ad45c2a6a002c32f8e90706

@TiagoSantos81 Unfortunately I keep hitting on new ones every once in a while, but less and less.

**Comment by TiagoSantos81** [comment] 2016-11-18 19:48
Converted a Java rule that you had in mind. 

https://gist.github.com/TiagoSantos81/540eed4d497df22890aacda504959732#file-portugueseaccentuationrule

You need to test thoroughly and give me the exception required (wrong positives) so I can add it to the build. Wordlist are updated with all the words in your Gist until today.

**Comment by Konfekt** [comment] 2016-11-21 00:57
This is a patch to be applied to the nightly build or the master tree? How to apply it?

**Comment by TiagoSantos81** [comment] 2016-11-21 14:43
It is a patch to apply to master, after removing the first comment line. 
From your skill I though you had a local copy of the build already with you. 
To apply the patch, save the text in the gist into a patch file, and, you can easily apply it in git-cola with the apply patch feature. I say git-cola, just because it is easier than command line.
If you do not have the build or that is too much trouble to test, I may had later this as an experimental feature for just one day, so you can download the nightly build with it.

**Comment by Konfekt** [comment] 2016-11-22 21:03
Yep, I would be glad to download it as a nightly build as a Java build system is missing on my  system.

**Comment by TiagoSantos81** [comment] 2016-11-23 14:21
At the momment, there are a lot of other changes that should be pushed first but I will add it one day of this week. I will tell you here when I push this change.

**Comment by TiagoSantos81** [comment] 2016-11-25 19:03
I have reconsidered the possibility of pushing this change. My apologies.
This changes effect also the online version for a day, I will not be able to push the accentuation rule, until I decide to test it more thorougly in my local build. 
It is already great for private use, as long as you figure out a way to compile it. An your feedback will really be appreciated.
I have already planned a week plus of things I want to push. I consider them prioritary to this rule, so, for the meantime this will have to wait.

**Comment by TiagoSantos81** [comment] 2016-12-13 22:43
SNAPSHOT has the feature included. You will have to activate 'Palavras facilmente confundidas' to test it. Notice that I have not places any exceptions, nor adjusted POS tags. Regression tests do not show many positives but this rule is not ready yet.

**Comment by Konfekt** [comment] 2016-12-14 11:07
Is this in the category-ID CONFUSED_WORDS?

**Comment by TiagoSantos81** [comment] 2016-12-14 12:25
Yes, but not in the grammar.xml. Due to different name strings they are two visible as two separate categories (this will be fixed in the next transifex sync).

**Comment by Konfekt** [comment] 2016-12-15 08:58
The version snapshot from 14. december has a list

`org/languagetool/rules/pt/verbos_sem_acento_nomes_com_acento.txt`

but with `--enable-categories CONFUSED_WORDS`, the error
```
No espirito vimos que isto não vale!
```
is not recognized. However, `Na substancia` is.

**Comment by Konfekt** [comment] 2016-12-15 09:00
That substancia is recognized though is due to `<rule id='PARONIMA_SUBSTANCIA_322' name='Uma substancia'>` That rule would be there twice then (if CONFUSED_WORDS worked).

**Comment by TiagoSantos81** [comment] 2016-12-15 15:26
```
Starting check in Portuguese (Portugal posAO)...
1. Line 1, column 4
Message: Se é um nome ou um adjectivo, tem acento. (deactivate)
Correction: espírito
Context: No espirito vimos que isto não vale!
Deactivated rules - click to activate again: Possível erro ortográfico (sem sugestões)

Potential problems found: 1 (time: 11ms)
How you can improve LanguageTool

```

> SNAPSHOT has the feature included. You will have to activate 'Palavras facilmente confundidas' to test it. Notice that I have not placed any exceptions, nor adjusted POS tags. Regression tests do not show many positives but this rule is not ready yet.

**Comment by TiagoSantos81** [comment] 2016-12-15 15:28
and from the other issue:

> I will add PortugueseAccentuationCheckRule as disabled by default, and without java test, tomorrow or one day after, depending on the regression test results of today. This way, you can test and develop it. You will have to activate it on the options to use it.

**Comment by Konfekt** [comment] 2016-12-15 17:22
Because `PortugueseAccentuationCheckRule` is in the category CONFUSED_WORDS, the parameter `--enable-categories CONFUSED_WORDS` should enable it. However the snapshot from 14. December does only include verbos_sem_acento_adj_com_acento.txt, but no rule PortugueseAccentuationCheckRule.

**Comment by Konfekt** [comment] 2016-12-15 17:23
Also, starting java -jar languagetool.jar, there is no rule 'Palavras facilmente confundidas'.

**Comment by TiagoSantos81** [comment] 2016-12-15 19:26
https://languagetool.org/download/snapshots/LanguageTool-20161214-snapshot.zip
This daily build?
Tested moments ago and it has the **category**  `'Palavras facilmente confundidas'`, as well as the **rule**, inside that category, called `'Confusão com acentos gráficos'`. I do not use the commandline tool, but it might be worth testing with the java **rule ID**, `ACCENTUATION_CHECK_PT`.

**Comment by Konfekt** [comment] 2016-12-15 20:08
Please give inside `LanguageTool-20161214/LanguageTool-3.6-SNAPSHOT/org/languagetool/rules/pt/grammar.xml` the line number of that rule Confusão com acentos gráficos.  I cannot find it. The category ID of Palavras facilmente confundidas is in `LanguageTool-20161214/LanguageTool-3.6-SNAPSHOT/org/languagetool/MessagesBundle_pt_PT.properties` set to `CONFUSED_WORD`, which was enabled.

**Comment by TiagoSantos81** [comment] 2016-12-15 20:24
> TiagoSantos81 commented a day ago • edited
> Yes, but not in the grammar.xml. Due to different name strings they are visible as two separate categories (this will be fixed in the next transifex sync).

**Comment by TiagoSantos81** [comment] 2016-12-15 20:25
It a **Java** rule.

**Comment by Konfekt** [comment] 2016-12-16 10:27
Ok, everything fine with `-e  ACCENTUATION_CHECK_PT`. However, since it is in the category `CONFUSED_WORD`, also `--enable-categories CONFUSED_WORDS` should enable it. Now
```
No espirito vimos que isto não vale!
```
gives
```
ACCENTUATION_CHECK_PT Se é um nome ou um adjectivo, tem acento.
```

**Comment by TiagoSantos81** [comment] 2016-12-16 11:52
It should, but since I do not use the commandline, I am not the proper person to diagnose that issue, but I confirm that the category string names are the same in XML and in Categories.java.
It may be advisable to check if LongSentenceRule (in STYLE) also faces the same problem and open a separate bug report for that specific issue.

**Comment by Konfekt** [comment] 2017-01-12 11:43
Just reporting back that this rule works fine no dia-a-dia, has been correcting me since (today, it happened to be refúgio).

**Comment by TiagoSantos81** [comment] 2017-01-12 14:31
That is very good news. Thank you for the report. I am focusing on other parts now, but I will get back to this rule, eventually. 
I have been testing it too, and I also find it great, but I think it is a bit too sensitive when advising to replace verbs, to make it default='on' right now. 
It will require a lot of time making it tighter.

One example is when the verbal form is in the start of the sentence, and inside hifenated forms: "Refugio-me em casa." This example shows both detection problems with the same noun you referred.

I know you have great command of the language, so it should not be a problem, but be mindful of these while accepting suggestions from this rule.

**Comment by Konfekt** [comment] 2017-01-12 17:59
Alas, with the symptoms you deliver the medicine.: Exclude the beginning of sentences for singular nouns and hyphenated forms. 

For me, even more so for a native speaker, I think default=on is more helpful in practice, as the mistake is always by hastiness, omitting an accent is more easily done. But if there is a high priority to avoid wrong positives, I understand.

**Comment by TiagoSantos81** [comment] 2017-01-13 13:00
I do not have a preference between false positives nor negatives. But, in this development state, this rule as a too high rate of false positives, in my opinion. 
It only has low overall positive count because those verbal forms are infrequent.
Since this rule is not a priority for me and I may not work on it any time soon, you are more than welcome to improve it. I will review your changes, and add them if appropriate, as well as set it as enabled by default, if I feel confident about it.

**Comment by Konfekt** [comment] 2017-01-21 21:40
Here's a false positive: isto contraria.

**Comment by TiagoSantos81** [comment] 2019-08-20 09:30
Problem solved. Thread is dead.

**Closed by TiagoSantos81** 2019-08-20 09:30 UTC
Labels: Portuguese, enhancement
