### ISSUE TITLE
Rule suggestion appears in brackets.

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#820] opened 2017-10-26 08:25 UTC
Hello!

I have added the following Portuguese rule:

```
	<rule id='FAZER_DESPORTO' name="Praticar desporto">
    <!--      Created by Marco A.G.Pinto     -->
      <pattern>
		<marker>
          <token inflected='yes'>fazer</token>
		</marker>
        <token min="0" regexp="yes">muito|pouco|algum|bastante|nenhum|mais|menos</token>
		<token>desporto</token>        
      </pattern>
      <message>Substitua por <suggestion><match no='1' postag='V.+'>praticar</match></suggestion>.</message>
        <suggestion><match no='1' postag='V.+'>praticar</match></suggestion>
      <example correction="praticar">Vou <marker>fazer</marker> muito desporto.</example>      
    </rule>	

```

It suggests "(praticar)" instead of "praticar".

Could someone have a look at it?

Thanks!

**Comment by MikeUnwalla** [comment] 2017-10-27 08:19
Snapshot LanguageTool-20171026-snapshot.zip works fine for me:

![image](https://user-images.githubusercontent.com/5816160/32093903-fb4c04ba-baf5-11e7-9c7f-db18d18c7b7e.png)

For English rules, I have seen the problem that you describe. I can't remember the cause, and because your problem seems fixed, I have not investigated more.

Aside 1: The second suggestion is not necessary in the rule.
Aside 2: testrules shows that there are duplicated disjunctions in some Portuguese rules.

**Comment by TiagoSantos81** [comment] 2017-10-27 09:06
Thank you for checking this Mike, but I believe that what Marco means is not exactly that. This is a follow-up of:
https://forum.languagetool.org/t/pt-portuguese-rule-contribution-discussion/1399/150

If the rule in Writer shows a type of suggestion: `(praticar)`, and in the stand-alone tool it shows a correct suggestion: `praticar`, there maybe a problem. 
I haven't lost any time looking into it, but if confirmed, it may be a useful report.

> Aside 2: testrules shows that there are duplicated disjunctions in some Portuguese rules.

I am aware of it, and they are due to complex regexp optimizations. The test engine is unable to cope with some non-capturing disjunctions, but the regexps do not have duplicated elements. If you look at it attentively, it refers to word sub-elements that can not be removed.
E.g. 
`"(?:(?:(?:(?:No[eë]|Isabe)l|Pa(?:sca|u)|Odi)l|G(?:a(?:[eë]|brie)ll|enevi[èe]v)|B(?:é(?:nédict|atric)|ernadett)|(?:Ma(?:dele|rt)i|Hélè|Yvon)n|[EÉ]m(?:manuell|ili)|(?:Domi|Véro)niqu|Fran(?:çois|c)|R(?:ené|os)|Thérès|Sophi|Ev)e|C(?:a(?:(?:th?erin|mill)e|r(?:oline|men))|(?:é(?:cil|lin)|la(?:ir|ud))e|h(?:a(?:rlotte|ntal)|ristine))|A(?:n(?:(?:g(?:ell)?|toinett|dré)e|n(?:ick|e))|(?:li[cn]|méli|ud)e|strid|gnès)|J(?:o(?:s(?:ephe|ée?)|[ëe]lle)|(?:eann|uli)e)|L(?:(?:aur(?:enc)?|[iy][ns]|uc)e|ou(?:ise)?)|[ÉE](?:lis(?:abeth|e)|dith))`

**Comment by marcoagpinto** [comment] 2017-10-27 09:19
It seems fixed with the last nightly or so.
It no longer suggests "(praticar)"

**Comment by TiagoSantos81** [comment] 2017-10-27 09:27
That is odd, because I haven't touch disambiguation not added any tag to praticar or related forms since you reported the issue.
What is the last SNAPSHOT that shows the issue you mentioned?

**Comment by marcoagpinto** [comment] 2017-10-27 09:41
@TiagoSantos81 

I believe it was the 24th because I tested it with the nightly in the same day that I committed the rule.

**Comment by TiagoSantos81** [comment] 2017-10-27 09:48
> I believe it was the 24th because I tested it with the nightly in the same day that I committed the rule.

A log of the previous two days for future debugging.

Commits on Oct 24, 2017
@marcoagpinto [pt] Added 1 rule:  … marcoagpinto committed 3 days ago 16ccb51  
 @TiagoSantos81 [pt] hunspell dictionary update TiagoSantos81 committed 3 days ago e6581eb  
 @TiagoSantos81 [pt] rule fixes TiagoSantos81 committed 3 days ago 46b70f6  
 @TiagoSantos81 [pt] rules improvements  … TiagoSantos81 committed 3 days ago  302832c  
 @TiagoSantos81 [gl] redundancy java rule added  … TiagoSantos81 committed 4 days ago 77827db  
 @TiagoSantos81 [en] add LibreOffice java ruleset  … TiagoSantos81 committed 4 days ago 69dfb0f
  
Commits on Oct 23, 2017
 @arysin [uk] new barbarism rule arysin committed 4 days ago  fef7137  
 @MikeUnwalla [en] Remove category MISC and move each rule to a more specific category  …
 MikeUnwalla committed 4 days ago 37a02f6
@janschreiber [de] spelling janschreiber committed 4 days ago   b225023  
 @TiagoSantos81 [pt-PT] spelling improvements TiagoSantos81 committed 4 days ago  4deb0a6  
 @TiagoSantos81 [pt-PT] rules improvements TiagoSantos81 committed 4 days ago 5fad0cb  
 @TiagoSantos81 [pt] rules improvements TiagoSantos81 committed 4 days ago fb4eadf  
 @TiagoSantos81 [gl] add generic java rules  … TiagoSantos81 committed 4 days ago 4ff224b  

These would be all the relevant commits.

**Comment by f-knorr** [comment] 2017-11-20 11:38
Hi! 
I think I have found the lines of code which explain this behavior:
In `org.languagetool.rules.patterns.MatchState` you can find:
```
if (wordForms.isEmpty()) {
            if (match.checksSpelling()) {
              formattedString[0] = "";
            } else {
              formattedString[0] = "(" + formattedToken.getToken() + ")";
            }
          }
```
Hence, it seems hat when the suggestion requires a change of postag which cannot be resolved the original word is put in brackets. 
You can reproduce this behavior with the following German example:
_Er ist der fünfseitiger Mann dazu._

Im am not sure what to do about this "problem": Maybe one should not offer a suggestions at all?

**Comment by f-knorr** [comment] 2018-04-01 13:22
Can we close this issue? It seems there is an explanation for the behavior

**Comment by f-knorr** [comment] 2018-04-07 10:08
Closed due to inactivity

**Closed by f-knorr** 2018-04-07 10:08 UTC
