### ISSUE TITLE
build issues on Fedora 25

### ISSUE THREAD

**Issue by mcepl** [languagetool-org/languagetool#663] opened 2017-01-27 12:48 UTC
Trying to package languagetool 3.6 for Fedora 25, but the build fails with these errors:
```
matej@mitmanek: languagetool-3.6 (master #%)$ mvn clean test
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.languagetool:languagetool-parent:3.6: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (https://repo.maven.apache.org/maven2): java.security.ProviderException: java.lang.NegativeArraySizeException and 'parent.relativePath' points at wrong local POM @ line 8, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.languagetool:languagetool-parent:3.6 (/home/matej/build/EXTRAS/LanguageTool/languagetool-3.6/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.languagetool:languagetool-parent:3.6: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (https://repo.maven.apache.org/maven2): java.security.ProviderException: java.lang.NegativeArraySizeException and 'parent.relativePath' points at wrong local POM @ line 8, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
matej@mitmanek: languagetool-3.6 (master #%)$ 
```

**Comment by danielnaber** [comment] 2017-01-27 13:13
I cannot reproduce this - which version of Maven are you using? Are you calling this in LT's top directory, i.e. the one that contains `languagetool-standalone` and others as sub directories?

**Comment by mcepl** [comment] 2017-01-27 14:56
```
matej@mitmanek: projekty$ mvn --version
Apache Maven 3.3.9 (NON-CANONICAL_2016-07-01T11:53:38Z_mockbuild; 2016-07-01T13:53:38+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-5.b16.fc25.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.3-200.fc25.x86_64", arch: "amd64", family: "unix"
matej@mitmanek: projekty$ 
```
and yes:
```
matej@mitmanek: languagetool-3.6 (master #%)$ ls
build.sh                     languagetool-gui-commons       languagetool-tools
hunspell-native-libs         languagetool-http-client       languagetool-wikipedia
languagetool-client-example  languagetool-language-modules  pom.xml
languagetool-commandline     languagetool-office-extension  README.md
languagetool-core            languagetool-server
languagetool-dev             languagetool-standalone
matej@mitmanek: languagetool-3.6 (master #%)$ mvn clean test
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.languagetool:languagetool-parent:3.6: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (https://repo.maven.apache.org/maven2): java.security.ProviderException: java.lang.NegativeArraySizeException and 'parent.relativePath' points at wrong local POM @ line 8, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.languagetool:languagetool-parent:3.6 (/home/matej/build/EXTRAS/LanguageTool/languagetool-3.6/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.languagetool:languagetool-parent:3.6: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (https://repo.maven.apache.org/maven2): java.security.ProviderException: java.lang.NegativeArraySizeException and 'parent.relativePath' points at wrong local POM @ line 8, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
matej@mitmanek: languagetool-3.6 (master #%)$ 
```

**Comment by danielnaber** [comment] 2017-01-27 15:22
Even with the same version of Maven I cannot reproduce this. Does it help if you change `<version>7</version>` to `<version>9</version>` in the top-level pom.xml?

**Comment by danielnaber** [comment] 2017-02-24 09:20
Closing, as there was no further feedback.

**Closed by danielnaber** 2017-02-24 09:20 UTC
