### ISSUE TITLE
Languagetool 5.1.1 is broken

### ISSUE THREAD

**Issue by madmanRB** [languagetool-org/languagetool#3638] opened 2020-10-01 14:29 UTC
I tried to use the latest version on Libreoffice 6.3.6.2 on Windows 10 64bit and I get an error!

[9d0a229d74ef3ad5b7c2ea7b9999cb2728cac0c8](https://user-images.githubusercontent.com/46382786/94822498-bb933600-03d0-11eb-9e62-4913c78bfe36.png)

Note: the same message appeared in both 5.1 and 5.1.1
Language tool 5.1.1 is totally borked, it won't load and it sometimes just freezes.
I am no spring chicken here with LibreOffice or LanguageTool here despite being new here and in its current state LanguageTool is unusable here using Windows 10 64bit.
I have tried:
Uninstalling it
Reinstalling it
Removing LibreOffice
Reinstalling LibreOffice

The error is not on my end I assure you, I have the proper versions of both java and LO and its not like I am using anything 32bit here.

Languagetool 5.1.1 is simply just plain broken, will use older version that does work until a fix is made.

**Comment by danielnaber** [comment] 2020-10-01 14:40
How can we reproduce the issue?

**Comment by danielnaber** [comment] 2020-10-01 14:45
@FredKruse Any idea why this is still happening in 5.1.1?

**Comment by madmanRB** [comment] 2020-10-01 14:49
> 
> 
> How can we reproduce the issue?

Just try installing it and use it, I am not lying here.

The error happens on both a clean and long term install of libreoffice I have tried both.
I also tried it with a fresh installation of LanguageTool without having a previous version.

**Comment by madmanRB** [comment] 2020-10-01 15:00
My only guess so for on why I think this is happening is both my machines use an AMD Processor, a Ryzen 5 3600 and a Ryzen 3 3250U.
If its any help I can give you guys my HW info if you need it.
I have a custom-built PC and an HP laptop both featuring AMD processors and Windows 10 64bit.
I also have an older HP Intel Core i5 3320M  Laptop that has Kubuntu Linux 20.04 could see whats happening there.
I am willing to give feedback if you guys want it.

**Comment by FredKruse** [comment] 2020-10-01 16:36
@madmanRB could you please post a screenshot of the error message you got now, because the lines of code have changed a bit.

**Comment by madmanRB** [comment] 2020-10-01 16:39
> 
> 
> @madmanRB could you please post a screenshot of the error message you got now, because the lines of code have changed a bit.

fine enough
![Screenshot 2020-10-01 123900](https://user-images.githubusercontent.com/46382786/94838145-2b122100-03e3-11eb-845b-7d5e978c4865.png)

**Comment by FredKruse** [comment] 2020-10-01 18:14
@danielnaber Do you have the chance to look at the code of 5.1.1? The line 1098 at MultiDocumentsHandler.java at the current code couldn't produce the error:
SpellAndGrammarCheckDialog checkDialog = new SpellAndGrammarCheckDialog(xContext, this, docLanguage);

**Comment by danielnaber** [comment] 2020-10-01 18:40
The git tag for 5.1.1 is now online: https://github.com/languagetool-org/languagetool/tree/v5.1.1

line 1098: `DocumentCursorTools docCursor = new DocumentCursorTools(getCurrentDocument().getXComponent());`

Also, IntelliJ warns that `xComponent` can be null in `if(xComponent.equals(document.getXComponent())) {`

**Comment by madmanRB** [comment] 2020-10-01 19:09
Well with the error in view as I saw it I am reverting to another earlier version.
I have 4.8 and will use that until this is fixed

**Comment by FredKruse** [comment] 2020-10-02 05:59
@danielnaber Could you please change the code for 5.1.1 by replacing the lines from 1098 till 1101 by
          XComponent currentComponent = getCurrentDocument().getXComponent();
          if (currentComponent != null) {
            DocumentCursorTools docCursor = new DocumentCursorTools(currentComponent);
            ViewCursorTools viewCursor = new ViewCursorTools(xContext);
            checkDialog.setTextViewCursor(0, 0, viewCursor, docCursor);
            resetCheck();
          }

**Comment by danielnaber** [comment] 2020-10-02 07:01
> Could you please change the code for 5.1.1 by replacing the lines

A version with that fix is now at https://we.tl/t-ceVYHfKdCQ, can you confirm it works?

**Comment by madmanRB** [comment] 2020-10-02 14:15
I can test it from an end users perspective and if it spits out errors I will take a screenshot of it

**Comment by madmanRB** [comment] 2020-10-02 14:19
and a big fat error message is my result....

![error again](https://user-images.githubusercontent.com/46382786/94933706-c3b6a880-0498-11eb-9d95-c8714778bc41.png)

**Comment by madmanRB** [comment] 2020-10-02 14:58
By the way I just attempted to do a fresh and clean installation of LibreOffice and java even removed my hidden LibreOffice config folder which had my custom dictionary and all that...

Same issue, same error code.

I would attempt a fresh clean install of windows 10 here but that is not my idea of fun to fix an issue that seems to be on your end not mine, reinstalling LO and java is far less annoying for me then a total clean install of windows.
I have no viruses on my system (dont have viruses at all as I am pretty tech-savvy here and don't go clicking on random links and all that)
So once more i dont think the error is on my end as I also have the same issue on my AMD windows 10 laptop and that just recently had a factory reset done to it which is fairly close to a clean install so makes me having to do a clean install of windows kinda pointless methinks.

So either A: the issue is with me using an AMD processor

Or B: the issue is somewhere in the coding

Or even C: a little of both? I dont know, coding stuff is not my forte unfortunately :(

**Comment by FredKruse** [comment] 2020-10-03 18:59
@madmanRB: It is not a problem of your CPU, I think. Also, you don't have to reinstall your windows or LO. This is a bug in the code. I got the problem that I can't reproduce the scenario that leads to this error.
As far as I see you have clicked on the first three LT buttons at the toolbar. In all cases the action was performed before the text was initiated which causes the problems.
I can fix the reported bug, but to prevent following errors I have to understand, what you did exactly. Did you load a long text to LO or a short one? Did you click at the buttons directly after the LO window was shown or later?

@danielnaber: Please add the following lines before line 1111:
        if(docLanguage == null) {
          docLanguage = getLanguage();
        }
But I'm not sure, if there will be following errors.

**Comment by danielnaber** [comment] 2020-10-03 20:02
@FredKruse the branch has now been shared on github, you can make those changes yourself and publish a build for testing: https://github.com/languagetool-org/languagetool/tree/v5.1.x-branch

**Comment by madmanRB** [comment] 2020-10-03 21:20
I loaded both a long and short text document, the error is the same no matter what I do.
It can be a blank document same thing.

I can load a file 12 pages or 2 pages long, same error, no different error code in either condition.

want screenshots again?

Because its pointless

Even one sentence breaks it, same error

but if you want proof:
2 pages:
![Screenshot 2020-10-03 165739](https://user-images.githubusercontent.com/46382786/95001623-9c93d000-0599-11eb-8285-b7156a9dd638.png)


12 pages

![Screenshot 2020-10-03 165739](https://user-images.githubusercontent.com/46382786/95001640-c6e58d80-0599-11eb-9a30-114e0b1d4422.png)

2 sentence

![Screenshot 2020-10-03 170115](https://user-images.githubusercontent.com/46382786/95001669-14fa9100-059a-11eb-89ad-034d7759f973.png)


Same error

I have given you more than enough info and loaded screenshots on my end and now its your job to fix it.

I don't know what else I have to do other than use a older version that works or start using your online tool now and pay you $20 a year now so i can get the same thing only having a price tag attached to it?

I mean is this intentional? Break the free version that has been free for ages so you can sell off your online service?

Yeah not doing that, the source code is free and there would be a fork in 10 seconds flat perhaps not by me though.

If I am going to have to start paying for a grammar check tool I would rather use another service like prowritingaid, same price but it is considerably better than LanguageTool and while it's app lacks Linux support copy and paste is a universal concept here and it can export to the opendocument format.
Yes it doesn't have a open source app but it does work which is more then i can say about LanguageTool in its current state, if I am going to be pigeonholed into using a paid service then I might as well go with the service that asks for money upfront instead of pretending to be a free and then have the free tool break so I have to pay money for it.

Thats awfully shady if this is intentionally done to lead folks into thinking the paid online service is better.

**Comment by danielnaber** [comment] 2020-10-03 21:28
@madmanRB We're trying to fix your error for free, so watch your tone. Sticking to a friendly and constructive tone is a requirement to take part in discussions in this project (I have edited your message).

**Comment by madmanRB** [comment] 2020-10-03 22:57
Fair enough, its just that I already gave the info on my end like three times now and I would have hoped it would be enough without having to jump through hoops.

**Comment by FredKruse** [comment] 2020-10-05 09:38
@danielnaber I got the problem. It is related to lightproof. This is a complicate problem. I haven' t found the full solution. LO still supports only one grammar checker per language. If lightproof is enabled, a first click of a toolbar button, or a menu item will disable lightproof and enable LT, now. A second click on the button does the desired action.  At the branch I have upload a update of extension code, which solves also the issues #3652 and #3575, etc and some bugs I had found by my own.
Please build a new release update form the branch. I have called it 5.1.2.

**Comment by danielnaber** [comment] 2020-10-05 10:08
It's now online at https://languagetool.org/download/LanguageTool-5.1.2.oxt

**Comment by kolAflash** [comment] 2020-10-25 21:45
Since LanguageTool-5.1.2 LibreOffice hangs (no reaction) when opening a text document (even an empty one) if lightproof is installed too.

I reproduced the problem multiple times.
Then the problem disappeared after uninstalling and reinstalling lightproof.

Tested on Debian-11-Beta (Bullseye) with:
apt purge libreoffice-lightproof-en
apt install libreoffice-lightproof-en

**Comment by danielnaber** [comment] 2020-10-25 21:53
> Since LanguageTool-5.1.2 LibreOffice hangs (no reaction) when opening a text document (even an empty one) if lightproof is installed too.

Have you tried LT 5.1.3, too?

**Comment by callegar** [comment] 2020-12-23 21:03
I am seeing this right now with LT 5.1.3 and LibO 7.0.4.2 on Linux. LT makes LibO hang.
Weird enough, I am seeing this after having reset my profile (because of issues trying LibO 7.1.x). Before the reset my LibO install was working just fine with LT.

**Comment by danielnaber** [comment] 2021-01-08 16:42
Does this still happen with 5.2?

**Comment by Elaborendum** [comment] 2021-02-05 19:51
This is what I get with 5.2:
![image](https://user-images.githubusercontent.com/71190696/107080490-5b1d6680-67bf-11eb-83dc-8dfa1d1c3a02.png)

Strangely enough, LibO hangs if I don't click Accept and I change focus to another window. LibO doesn't hang at startup in my case.

**Comment by FredKruse** [comment] 2021-02-06 15:40
Could you please tell me what language you have used?

**Comment by Elaborendum** [comment] 2021-02-06 16:39
Spanish, but I tried with english and it started to work. I changed it back to spanish and it was working again, but it didn't take long before it stopped working altogether. I restarted LibO and, during that process, a similar error as the ones reported previously appeared, but I didn't get to take a screenshot.

I tried once again and it didn't work until I changed the language to english, but even then it worked unreliably. I didn't get to replicate what caused the sudden "an error has occurred" screen, though.

**Comment by FredKruse** [comment] 2021-02-06 17:40
That's strange. Spanish should be supported. Did you have the log-file from the session at which the error occurs?
The file is called: LanguageTool.log
You find it at:

- Windows: \\user\<YourUserName>\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice  
- Linux: /home/<YourUserName>/.config/LanguageTool/LibreOffice 

You have to choose "show hidden directories", to see the directory, 
 Please add the content of the log-file

**Comment by Elaborendum** [comment] 2021-02-06 17:57
This is it, I think:

LT office integration log from Sat Feb 06 11:23:41 COT 2021
LT doesn't support language: es-MX
LinguisticServices failed! LanguageTool can not be started!
LT doesn't support language: es-ES
LinguisticServices failed! LanguageTool can not be started!
LT doesn't support language: es-PE
LinguisticServices failed! LanguageTool can not be started!
Internal LT dicitionary for language en added: Number of words = 25309
getCachePath: documentPath == null!
Internal LT dicitionary for language en added: Number of words = 22647
Internal LT dicitionary for language es added: Number of words = 392
com.sun.star.lang.IllegalArgumentException: 
	at com.sun.star.bridges.jni_uno.JNI_proxy.dispatch_call(Native Method)
	at com.sun.star.bridges.jni_uno.JNI_proxy.invoke(JNI_proxy.java:185)
	at com.sun.proxy.$Proxy40.changeText(Unknown Source)
	at org.languagetool.openoffice.FlatParagraphTools.changeTextOfParagraph(FlatParagraphTools.java:686)
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.changeText(SpellAndGrammarCheckDialog.java:1749)
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.actionPerformed(SpellAndGrammarCheckDialog.java:1551)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

getNextError: y (= 1) >= text size (= 1): Return null
getNextError: y (= 1) >= text size (= 1): Return null
getNextError: y (= 0) >= text size (= 0): Return null
getNextError: y (= 0) >= text size (= 0): Return null
getCachePath: documentPath == null!
Interrupt text level queue for document 1
Interrupt done

**Comment by FredKruse** [comment] 2021-02-07 18:35
Thank you for testing. The bug is fixed. You could test it in the tomorrow snapshot tomorrow.
@danielnaber This is an ugly bug. It caused LO/OO to refuse a check for Spanish language and some variants of other languages. Should we update 5.2.2 to 5.2.3?

**Comment by danielnaber** [comment] 2021-02-08 10:45
@FredKruse If you prepare the branch so that it's release-ready, I can make a release. That means increasing the version number in `JLanguageTool` and having all needed commits (and only those) in the branch. All tests should be green, of course.

**Comment by FredKruse** [comment] 2021-02-08 18:39
@danielnaber The version is changed to 5.2.3. All needed commits are done to v5.2.1-branch. All tests are green. So the release is ready, I think.

**Comment by danielnaber** [comment] 2021-02-08 21:28
@FredKruse I've uploaded the build to https://languagetool.org/download/LanguageTool-5.2.3-beta.oxt, can you confirm it looks good?

**Comment by QazCetelic** [comment] 2021-02-10 20:10
> This is what I get with 5.2:
> ![image](https://user-images.githubusercontent.com/71190696/107080490-5b1d6680-67bf-11eb-83dc-8dfa1d1c3a02.png)
> 
> Strangely enough, LibO hangs if I don't click Accept and I change focus to another window. LibO doesn't hang at startup in my case.

![image](https://user-images.githubusercontent.com/51381523/107565636-29a00300-6be4-11eb-9523-5ad0534a0c12.png)
I'm also getting the same error message (Version 5.2.2, the latest that can be found on LibreOffice.org)

**Comment by FredKruse** [comment] 2021-02-10 20:23
Could you please test the 5.2.3-beta. See the link at the last comment.

**Comment by Elaborendum** [comment] 2021-02-14 01:04
Right clicking the error and selecting the correction works, which I think was the main issue.

However I found some other problems:

- I don't understand the difference between "Check Text" and "Check Text Again". The former almost always pops up an empty dialog screen (I thought this was intended, but it appears complete once I click at least once on "Check Text Again") while the latter's is always adecuate. Either of these dialogs are interrupted by a "Check has been completed" dialog if I click anywhere else without closing it, clicking accept on this last one causes both to close.
![image](https://user-images.githubusercontent.com/71190696/107865571-c4dbe700-6e35-11eb-83ca-a2b3a38620a2.png)
![image](https://user-images.githubusercontent.com/71190696/107865574-cb6a5e80-6e35-11eb-9330-029d8af3c74c.png)
- Clicking anywhere else inside LibO while there the dialog "Check has been completed" is open makes the entire program hang. Or if it pops up (by clicking "Next Spelling or Grammar mistake") while there is another dialog open. Doesn't happen in the situation mentioned in the previous issue.

Some one-offs:

- If I have more than one document open (with different languages?) and do a check on one of them, trying to do a check on the other will just redo the check on the first.
- Despite clicking "Change" text remained the same, sans the line. Subsequent checks claimed there were no mistakes.
- Clicking "change" caused the incorrect text to duplicate. (Image below taken after correcting spelling mistakes with LanguageTool)
![image](https://user-images.githubusercontent.com/71190696/107865576-d8874d80-6e35-11eb-8982-42247da25362.png)

I'm using LibO in spanish so I may be calling certain specific functions differently in this.

Should I create separate issues for these? I don't know if these are unique to this version since I only recently started using LibO and LanguageTool.

**Comment by FredKruse** [comment] 2021-02-17 08:00
@Elaborendum: There were many changes in code in 5.3, also in the development of the spell and grammar check dialog. The problems you found are solved by the last commit. Please test the tomorrow 5.3-snapshot. If there are other bugs regarding the spell and grammar check dialog, please open a new issue. The title of this issue is misleading. I would like to close this issue.
@danielnaber: I think, we should release the 5.2.3 as it is. The fundamental bugs are solved as far as I see. Advanced problems like the last reported have to be solved in 5.3.

**Comment by danielnaber** [comment] 2021-02-17 08:49
I have published 5.2.3 now on https://extensions.openoffice.org and https://extensions.libreoffice.org/ (it will take some time until it appears there).

**Comment by Elaborendum** [comment] 2021-02-21 04:06
@FredKruse Excuse but, where can I find the 5.3-snapshot? I'm not too well versed in the extension's development.

**Comment by FredKruse** [comment] 2021-02-22 08:16
@Elaborendum No problem. Here you will find the latest snapshots: https://internal1.languagetool.org/snapshots/

**Comment by FredKruse** [comment] 2021-11-18 19:25
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:25 UTC
Labels: office-integration
