### ISSUE TITLE
LibreOffice Writer menu bar duplicates when closing and opening a text document

### ISSUE THREAD

**Issue by Amr-Ibra** [languagetool-org/languagetool#2000] opened 2019-10-03 13:42 UTC
See the attached GIF and follow the steps below to reproduce the bug.

0. Start LibreOffice Writer, add the LanguageTool extension and restart LibreOffice
1. Close the text document but not the whole application
2. Re-open a Writer text document
3. Menu bar duplicates each time you close and open a text document

The bug disappears after the LanguageTool extension is deactivated or removed.

LanguageTool version: 4.7
LibreOffice version: 6.2.6.2
OS: Ubuntu 18.04.3 LTS

![LO_Writer_menu_bar_duplicates](https://user-images.githubusercontent.com/45657128/66131661-2100eb00-e5f4-11e9-8efa-561495e13186.gif)

**Comment by gl-pasci** [comment] 2019-10-16 07:08
I'm experiencing the same bug.

LanguageTool 4.7
libreoffice-fresh 6.3.2-2 on arch

**Comment by danielnaber** [comment] 2019-10-16 07:22
According to [this page](https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1825741), it will be fixed in LibreOffice 6.3.3.

Also see https://forum.languagetool.org/t/double-menu-bar-in-libreoffice/4935

**Comment by Amr-Ibra** [comment] 2019-10-19 11:21
This bug is still in LibreOffice 6.2.8.

The upstream bug is different, fixed in 6.2.8 and 6.3.3. It was for using global-menus in LibreOffice, not related to LanguageTool.
https://bugs.documentfoundation.org/show_bug.cgi?id=124391

**Comment by yakovru** [comment] 2020-01-31 12:51
https://bugs.documentfoundation.org/show_bug.cgi?id=128491

**Comment by danielnaber** [comment] 2020-03-13 13:26
@FredKruse Do you know whether this is a bug in LT or in LibreOffice?

**Comment by FredKruse** [comment] 2020-03-14 17:35
I think it is a bug in LibreOffice, even though is seams to be triggered by LT handling the menu (only standard interfaces are used).
@Amr-Ibra you can solve the problem by:
sudo apt-get remove libreoffice-gtk3
sudo apt-get install libreoffice-gtk2
The doubled menu occurs only in gtk3

**Comment by FredKruse** [comment] 2020-03-14 17:51
I just tested the version 6.4.1.2 of LibreOffice. The Bug in gtk3 is solved there.
@Amr-Ibra so better install this version of LibreOffice.

**Comment by FredKruse** [comment] 2020-03-21 19:05
Unfortunately I wasn't right. The problem isn't solved with LibreOffice 6.4.x. On the contrary the dynamic part of the menu doesn't work for LO 6.4.x. Also, gtk2 doesn't work for this version. If you remove gtk3 the LO-surface looks rather ugly.
I'm working on a solution. It will work for LO 6.4.x and gtk3. I tested it also for LO 6.2.8. It works for gtk2 (The doubled menu bar for gtk3 is a LO problem I think). So for older versions gtk2 should be used.
@danielnaber: I hope its OK when I push a bug fix for this issue this evening.

**Comment by Amr-Ibra** [comment] 2020-03-21 19:32
I'm now on LO 6.3.5 and will track the 6.3.x releases because it's the conservative release, and will upgrade to 6.4.x when it becomes the conservative release and 6.3.x becomes end-of-life.

The bug is also reproducible in LO 6.3.5.

**Comment by danielnaber** [comment] 2020-03-21 19:45
> I hope its OK when I push a bug fix for this issue this evening.

Sure, the feature freeze shouldn't prevent bug fixes.

**Comment by ronnystandtke** [comment] 2020-08-28 13:20
I just run into the same issue with the latest and greatest versions of LibreOffice (7.0) and LanguageTool 5.0.1, running Debian stable plus backports.

**Comment by Skydancer9** [comment] 2021-08-12 08:34
Same issue with:
- LibreOffice 7.0.6.2
- LanguageTool 5.4

**Comment by FredKruse** [comment] 2021-11-18 19:29
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:29 UTC
Labels: office-integration
