### ISSUE TITLE
Resets textarea scrolling position

### ISSUE THREAD

**Issue by frumbert** [languagetool-org/languagetool#8450] opened 2023-05-12 01:38 UTC
Language Tool browser plugin resets the scrolling position of textareas after it loads, which (on slower sites) can be some time after the page has loaded and interaction has begun. I've noticed this in Firefox, Chrome & Edge.

I can be scrolling down in the textarea a tens or hundreds of lines then the extension loads and resets the position.

Plese don't change the scrolling position on load.

**Comment by tiff** [comment] 2023-05-12 05:53
@frumbert Thanks. I don't think we do this, and I'm also unable to reproduce this. Do you have an example website where this happens?

**Comment by tiff** [comment] 2023-06-12 20:23
Closing because no feedback from the user.

**Closed by tiff** 2023-06-12 20:23 UTC
Labels: browser-add-on
