### ISSUE TITLE
Out of bounds exception

### ISSUE THREAD

**Issue by aronbos** [languagetool-org/languagetool#5272] opened 2021-06-29 15:01 UTC
See the screendump for the details[
![screendump2021-06-29 15-27-56](https://user-images.githubusercontent.com/48289775/123821183-78cca300-d8fb-11eb-891f-06f3839e4f35.jpg)

This makes languagetool effectively unusable.

**Comment by danielnaber** [comment] 2021-08-18 07:25
@FredKruse Do you think this is still an issue with the current snapshot?

**Comment by aronbos** [comment] 2021-08-18 07:43
Where can I get the current snapshot in XPI (libreoffice extension) format so I can test it?

**Comment by danielnaber** [comment] 2021-08-18 07:49
https://internal1.languagetool.org/snapshots/

**Comment by FredKruse** [comment] 2021-08-18 08:02
I have to look at this bug, but it will take a few days. I am not at home.

**Comment by aronbos** [comment] 2021-08-18 08:08
I installed LanguageTool-20210817-snapshot.oxt  in Libreoffice 7.1.5.2 and will test today.

**Comment by aronbos** [comment] 2021-08-18 09:57
Working for two hours with the current snapshot gave no errors and no runaway CPU usage.

**Comment by aronbos** [comment] 2021-08-18 12:20
Mmm. I spoke to fast. I got a new error
![screenshot2021-08-18 14-15-03](https://user-images.githubusercontent.com/48289775/129896916-65b899ab-2c0c-4d0c-a4bf-a4387a1728f3.jpg)

**Comment by FredKruse** [comment] 2021-08-20 10:44
The bug should be saved.
@aronbos Please test it with the snapshot tomorrow.

**Comment by aronbos** [comment] 2021-08-21 07:45
I checked today the same document with footnotes. Editing and deleting the text went fine. No problems found, but it was a short test. Next week I will test it much longer. If I encounter new problems, I will let you know.

**Comment by aronbos** [comment] 2021-09-01 14:10
Today, I got this error:
![Schermafdruk van 2021-09-01 16-05-30](https://user-images.githubusercontent.com/48289775/131686504-17bf8e6b-c276-41fc-81e9-825895512821.jpg)

**Comment by FredKruse** [comment] 2021-09-01 19:14
The issue should be solved. Please test with the snapshot tomorrow.

**Comment by aronbos** [comment] 2021-09-10 07:08
I did not encounter an error this week.

**Comment by aronbos** [comment] 2021-09-20 08:45
![Schermafdruk van 2021-09-20 10-41-07](https://user-images.githubusercontent.com/48289775/133976583-2de089fe-aa53-49bd-a983-e9e78a29861b.jpg)

**Comment by aronbos** [comment] 2021-09-21 08:07
Error with a double footnote, latest snapshot and version 5.1.
![Schermafdruk van 2021-09-21 10-02-46](https://user-images.githubusercontent.com/48289775/134135030-57e5a0b7-3882-4e48-bdb7-795a5e52ca04.jpg)
6

**Comment by aronbos** [comment] 2021-10-02 08:05
I I did not encounter an error this week.

**Comment by aronbos** [comment] 2021-10-05 08:34
![Schermafdruk van 2021-10-05 10-30-35](https://user-images.githubusercontent.com/48289775/135988939-94377810-2f7f-43eb-8c28-040a10f9a6c7.png)

Perhaps unrelated, but never the less an error.

**Comment by FredKruse** [comment] 2021-11-18 18:50
The issue is solved. I close it. Please open a new issue for the latest version, if an exception should occur.

**Closed by FredKruse** 2021-11-18 18:50 UTC
Labels: office-integration
