### ISSUE TITLE
LibreOffice: "Connection Refused"

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3796] opened 2020-11-05 09:43 UTC
Hello!

I was using the nightly in a Portuguese document.

First, the options were in English and not in Portuguese, then, while checking the grammar, I got:
![connection refused](https://user-images.githubusercontent.com/5192600/98224427-5ee4e700-1f4b-11eb-957b-256e8576dc96.png)

**Comment by FredKruse** [comment] 2020-12-03 16:01
@marcoagpinto: The options should work for the correct language now (next build tomorrow).  They depend on the position of the cursor in a multilingual document, e.g. the one you attached at #3881. In your document are sentences LO detects at English.
The other question is, if you used a remote server. The message above is displayed if the connection to a remote server is refused.

**Comment by danielnaber** [comment] 2021-01-08 16:40
Can this issue be closed?

**Comment by FredKruse** [comment] 2021-11-18 19:22
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:22 UTC
Labels: office-integration
