### ISSUE TITLE
The extension causes Chrome to freeze when visiting certain pages

### ISSUE THREAD

**Issue by marcoiosif** [languagetool-org/languagetool#5983] opened 2021-11-05 14:17 UTC
Hello

To reproduce the error is very easy, create a chrome profile, install and set up the extension and visit the website marca.com, open any post, scroll down to the comments section and click on “View comments”. At that time a lot of CPU is spent and chrome freezes completely.

When you visit the web without the extension installed or in private mode this does not happen at all.

I do not know if this happens only for this website or for others.

![image](https://user-images.githubusercontent.com/83413508/140524492-87fda624-e4f3-4ff9-b9b4-8b45431db900.png)

**Comment by tiff** [comment] 2021-11-05 15:09
Hi @marcoiosif, thanks for reporting this. Unfortunately, I'm unable to reproduce this. Are you sure it is caused by our add-on and not by some of the intrusive ads that are running on that page?
Could you post a link to one of the articles where this is happening?

**Comment by danielnaber** [comment] 2022-12-31 14:34
Closing, as there was no reply

**Closed by danielnaber** 2022-12-31 14:34 UTC
Labels: browser-add-on
