### ISSUE TITLE
Exception while initialization of JLangTool by LO/OO extension

### ISSUE THREAD

**Issue by FredKruse** [languagetool-org/languagetool#4088] opened 2021-01-04 06:41 UTC
While initialization of JLangTool by LO/OO extension, I got the following exception (since a pull yesterday):
![message](https://user-images.githubusercontent.com/23344265/103507706-10c36580-4e60-11eb-876d-8f4b2a33e01d.png)

**Comment by danielnaber** [comment] 2021-01-04 11:36
Should be fixed now, was caused by a dependency update of `javax.measure:unit-api` and `tech.units:indriya`. I have rolled back that update for now.

**Closed by danielnaber** 2021-01-04 11:36 UTC
Labels: bug, code/java
