### ISSUE TITLE
exception: invalid memory access (hunspell)

### ISSUE THREAD

**Issue by Artalus** [languagetool-org/languagetool#580] opened 2016-10-25 17:46 UTC
Version 3.5 downloaded from the site, German language on a russian computer - any action in text editor leads concurrency exceptions. After pressing the "Check text" button, the error box shows and the button disables.

![222](https://cloud.githubusercontent.com/assets/10381253/19696964/15aac5aa-9af2-11e6-9d0d-9e6a62fd169d.png)

**Comment by danielnaber** [comment] 2016-10-25 18:11
Thanks for the bug report. What operating system and what kind of hardware are you using?

**Comment by danielnaber** [comment] 2016-10-25 18:11
This has been reported before (http://forum.languagetool.org/t/deutsch-deutschland/836) but there was no more feedback after the original report.

**Comment by Artalus** [comment] 2016-10-25 18:16
From dxdiag:
           Operating System: Windows 7 Ultimate 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.160902-0600)
               Language: Russian (Regional Setting: Russian)
    System Manufacturer: ASUSTeK COMPUTER INC.
           System Model: X550LB
                   BIOS: BIOS Date: 07/09/13 11:26:27 Ver: 04.06.05
              Processor: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 CPUs), ~2.4GHz
                 Memory: 6144MB RAM
        DirectX Version: DirectX 11
     System DPI Setting: 96 DPI (100 percent)
              Card name: Intel(R) HD Graphics Family
           Manufacturer: Intel Corporation
              Chip type: Intel(R) HD Graphics Family
               DAC type: Internal
             Device Key: Enum\PCI\VEN_8086&DEV_0A16&SUBSYS_131D1043&REV_09
         Display Memory: 1696 MB

**Comment by yakovru** [comment] 2016-10-25 18:18
Java version? 32 or 64 bit?

**Comment by Artalus** [comment] 2016-10-25 18:20
Java X64
`java version "1.8.0_101"`
`Java(TM) SE Runtime Environment (build 1.8.0_101-b13)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)`

**Comment by danielnaber** [comment] 2016-11-01 19:43
Where had LanguageTool be installed? Was there maybe a special character somewhere in the path name?

**Comment by Artalus** [comment] 2016-11-01 19:58
...That was indeed a correct guess. The path was `D:\YandexDisk\University\Sem9M\[ИНО] LanguageTool.org v3.5` - now that I checked it on simply `D:\LanguageTool` it works fine. The problem appears to come from non-ASCII characters - `D:\ЛангуагеТоол` gives the same stacktrace as above.

**Comment by danielnaber** [comment] 2016-11-01 20:08
Also, it seems to be specific to Windows, I cannot reproduce it on Ubuntu.

**Comment by Artalus** [comment] 2016-11-01 20:11
It may be so because on Ubuntu the path consists of Unicode characters, while Windows probably uses something like CP-1251. So Java detects Unicode characters just fine, but fails at CP-1251 characters and tries to read something from a completely gibberish path.

**Comment by yakovru** [comment] 2016-11-10 12:31
I think you can replace hunspell dll library in hunspell-native-libs.jar

**Comment by amake** [comment] 2017-10-03 00:27
This may be related to java-native-access/jna#633, which was fixed in jna 4.3.0, meaning it may be fixed in LanguageTool 3.9 (using jna 4.4.0).

**Comment by danielnaber** [comment] 2019-06-29 08:15
Closing, as this is maybe fixed. Please re-open if the problem still exists.

**Closed by danielnaber** 2019-06-29 08:15 UTC
