### ISSUE TITLE
Performance issues on bigger documents

### ISSUE THREAD

**Issue by ColeBantam** [languagetool-org/languagetool#4413] opened 2021-02-19 11:00 UTC
Since my exception bug is already so bloated, I'll start a separate bug-report for this issue...

As we have seen in #4046, heap space is an endless issue with LT and LibO. So I thought the time for a change to 64Bit LibO has come and without limiting heap space everything should run fine - that was a big mistake!

Problem description:
I did some tests with several 64Bit versions of LibO the last days, and until now, its even more disappointing than the 32Bit version. Yes, heap space is no issue in 64Bit - in terms of that its not limiting. But now there is a different problem. If I open my newsletter-document (a real world document, no silly-huge test-doc) I quickly end up having LibO consuming 7GB RAM! OK, I have 32GB RAM installed, so for me personally that would be acceptable if performance would increase, but thats not the case. In opposite, LibO seems to have a hard time to handle that much ram, and every save takes a lot longer compared to the 32Bit version.

Possible Sollution:
So all falls back to the initial Problem of consuming too much heap space. My approach in solving that is simple - make LT check only the pages that are of interest and not the whole document.

Solution Example:
In my example, my document has about 300 pages. If I edit page 30, I don't care for the grammar on page 300. So, if LT only requests the current page from LibO (and maybe the one before and after) the amount of necessary RAM would be dramatically lower. Also the whole processor usage would go down extremely and everything should be so much more responsive. And 32bit and 64bit versions would benefit both.

Can the API do that?
Since I am not a programmer, I have no idea if the API that LT uses can handle such a selective request (give me the current page, and the one before and after). If LibO can't do that now, I can make a Bug in the LibO Tracker requesting that.

OpenOffice:
Some might ask, what about OpenOffice? If LT changes the API that would break OpenOffice. Answer, let it brake. OpenOffice is dead. If OpenOffice doesn't want to add the new API, older LT-Versions will be fine for OO.

**Comment by FredKruse** [comment] 2021-02-24 15:26
First: I can't reproduce the problem with the limitation of heap space, neither in the 32-bit implementation (I used Linux Mint in a virtualbox), as described in #4046.

Your solution is interesting, but it is not supported by the interface:

LO provides an interface that ask paragraph by paragraph for a grammar check. It begins with the visual page (the order of paragraphs is changed, if the user scrolls to another page. In this case the new visual paragraphs are checked as next). This is the basic interface used by LT.

(By the way: if used in OO or very old versions of LO, LT switches back to use only this interface).

The last versions of LT use more than this interface. The reason is, that many rules on text level needs more than to check one paragraph. For example if you have a citation or direct speech, that spans more than one paragraph. The check will generate at the beginning quote and at the end quote a false match. Therefore, LT runs a so-called "text level check". 

To increase performance, LT works with caches. At default the cache is saved by saving or closing the document, which increases the performance a lot. So you should see marked problems in your text very fast, if open your document the second time. 

(Important note: Use "check text again" <shift-F7> only if really necessary. This function deletes the cache and starts the check from the beginning. Go to the position from which you like to start and run <F7> "check text" instead.)

If you don't like to run a background check (to save CPU power), you can switch it off at the option panel or at the LT menu. In this case no marks are shown in the text. Nevertheless, you can set the cursor to the position at which you want to start the check and press <F7> "Check text". The spell and grammar check dialog is shown, and you can do your check manually (Note: The check may be a bit slower, because it has to be performed directly and can't use the cache).

**Comment by ColeBantam** [comment] 2021-02-24 17:03
I did (and currently do) some more tests with LT on different LibO Versions, bitnesses and Hardware. Some results:

1.) The amount of heap space in LibO depends somehow on the hardware of the system. I tried an old Intel System (Core-i Gen3) and there I can get up until 1,1GB Heap space in 32Bit LibO. On my own System (Ryzen, 32GB RAM) I can go somewhere about 750M Heapspace. Both use the same Oracle Java 32Bit Build, the same Windows Version and the same LibO Version. So for the moment, I have no Idea why the old system offers so much more Heapspace.

2.) To do more tests with Java itself, do you know a Java-Test-Programm that shows the memory allocation of the jvm? I would like to see how much heapspace the jvm can allocate natively, without LibO.

3.) Java Version:
If you do all tests with Java 11, you are far beyond what the "average Joe" on Windows will use. On Windows, typically everyone that uses Java still uses Java 8, because it's the only version you get a JRE from Oracle. The newer Java Versions from Oracle only exist in JDK-Flavour and are well hidden on the Oracle website. So, not sure if it's that good to develop on Java 11 basis (if you do). LibO itself seems not to give any recommendations on the version of Java :/ But on libreofficehelp.com (no idea if that's an official LibO site) they point directly to java.com, where only java 8 is available.

4.) Heapspace is always an issue.
Even though the old Intel system can allocate more Heapspace, the problems remain the same when we ran out of Heapspace. The results vary from try to try, sometimes LibO gets stuck, sometimes you get a exception pointing to a heap space issue, sometimes LibO brings a "osl::Thread::create failed" error. Anyway, the result is always the same, unsaved changes to the document are lost :/

5.) If LT uses two different APIs to get the data from LibO, is it possible to force use of the old API? Because with older versions of LT I never had so many issues compared to the current versions and LibO7. And what Version of LT exactly made the switch? From 4x to 5x?

6.) As said, if the current API in LibO doesn't allow for a clean LT integration, I can file a bugrepot in LibO Tracker for a new API. Of course it will take long until that will happen (if it will happen at all), but I would like to try. But I need some information how exactly the API should work. So It might be better if Fred does that. From developer to developer. Im just a User. Or maybe the current API just needs some tweaks?

7.) Caches
Where are these Caches stored? On Disk? In RAM? Is there a limit for the caches? Because if not, that would possibly explain why LT takes so incredible huge amounts of RAM on 64Bt Version. As said, LibO (even the 64Bit Version) seems to not like huge Heapspaces and becomes unresponsive when saving. Is there an option to set a maximum cache size or disable the cache at all?

8.) Disabling On Canvas Spell Check
You said disabling LT check on Canvas is an option to save CPU power - well, of course that would save cpu-power on idl, because that means effectively disabling LT. Using the separate Spellchecker Windows is not realy an Option (to me), that would trow me back in time into the 80s. No, background spellcecking is definitely ok (I'd say its a "must have"), the problem is just, that currently the whole document is checked and not only the page(s) that is being worked on.

**Comment by ColeBantam** [comment] 2021-02-24 18:04
I just finished some tests with Linux on the same hardware as my regular system (Ryzen, 32GB RAM) but in a VirtualBox Environment just like Fred. Also Mint Linux 19.2 32Bit. That shows some interesting differences to Windows:

1.) I can set "huge" amounts of Heap space in Linux. 2GB was no problem!
2.) If you touch the boundaries of heap space in Linux, the result is much more dramatic then in Windows. In Windows only LibO dies, in Linux the whole OS crashes. (Not a fair comparison of course because 32Bit Lix compared to 64Bit Windows)
3.) The Amount of Heapspace that LT reports (about dialogue) meets EXACTLY the values that were set with -Xms and -Xmx. In Windows, its just an approximation.

I really would like to test Java on these two platforms native with a java-memory-test-programm. I'm curious if the JVM on windows is the limitation compared to the JVM on Linux, or if it's LibO itself.

Whatever the reason currently is, LT developers should keep in mind, that heapspace is a much bigger issue on LibO 32Bit (Windows) than on LibO32Bit (Linux).

**Comment by ColeBantam** [comment] 2021-02-25 12:24
Final Heap Space conclusion!

OK, I will not dive any deeper into Heap Space investigation, as it seems to be logical now. Here's my conclusion:

1.) LibO vs. Native:
The maximum amount of Heap-space in LibO is always a lot less compared to a running a Java-App natively in the JVM. For example on my system:
LibO: About 800M (and thats not stable!)
Native JVM: 1450M
I don’t know if its bad design in LibO or if its “normal” when Java-Code is run from inside another application, but it is what it is and I don’t think that will improve in the near future.

2.) You can’t predict the limit (32Bit)
It seems to be impossible to predict how big the heap-space can get on different systems. Linux is definitely in a way better position, as threads can become up to 4GB in size, whereas in Windows usually its limited to 2GB. So the maximum heap-space is also doubled in Linux compared to Windows. But also other things reduce the amount of heap-space available, like drivers, security software aso. Also, CPU-Security -Features may factor into it. With LibO reducing the amount too, it seems like more than 512M may not be possible/stable on some (Windows)systems.

3.) Work Around
Since heap-space can be very small and unpredictable, the only thing LT can do is to try to use as little RAM as possible. And here we are again with the “spellcheck only whats visible” approach.
- So, it's clear that an API in LibO needs to be created or extended for that, so can we at least think about that or is it a NoGo for you?
- In the meantime, can we make the “old” API selectable via settings, if that needs less memory? (Its clear that spellchecking may not be as effective than).

**Comment by FredKruse** [comment] 2021-02-28 17:56
A control of used heap space is added. The values are received at runtime from default java methods. If 95% of max. heap space is used, LT switches back to single paragraph mode. All caches are freed and LT runs without the advanced features. The rules on sentence level will be handled correct, also all rules that works on the level of one paragraph. The other rules (most of them are optional) can cause some false matches.
From my point of view this is the best solution, because we keep LT running.
As I described in my last comment, in most cases another or extended API is not necessary from my point of view. I see only a problem with very huge texts on 32 Bit machines (a document contained 2500 pages runs on my 32-Bit installation). The fall back installed now should solve the problem.

**Comment by ColeBantam** [comment] 2021-03-01 18:11
That really sounds  like a good fast solution for that issue :)

Nevertheless, I doubt that 95% is a good value on Windows Systems. As I have written before, LibO is extremely bad in determining how much heapspace it can get (xmx). So, if you want to be on the safe side and have it all configured automatically, I'd suggest a much lower threshold. Because I think with 95% the crashes will not go away. I'd tend more into the area about 70%. I know thats much lower, but it still should be triggered only on big documents, so most users won't even notice a difference.

Also this doesn't solve the problem with sluggish performance in LibO 64Bit. Users with very big documents still will get bizarre heap space sizes there, which LibO just doesn't like.

So, the "check only the current pages" approach would still be welcome, even though its clear that it would take a lot more time to implement than your solution.

Anyway, will this commit be integrated in tomorrows snapshot?

**Comment by FredKruse** [comment] 2021-03-03 09:26
@ColeBantam: Please test, if the 95% works. If not, I could change this value.
"check only the current pages" can not be realized on the basis of the current LO/OO grammar checking interface. Maybe you can discuss this idea with the developers of LO.

**Comment by ColeBantam** [comment] 2021-03-05 14:35
I can test this as soon as I know in what snapshots this commit is integrated.

**Comment by FredKruse** [comment] 2021-03-09 08:35
It is integrated in the 5.3-snapshot.

**Comment by ColeBantam** [comment] 2021-03-09 10:46
I already was about to say, that its boring to test that snapshot because its so stable, but then voila :D

![next-exeption17](https://user-images.githubusercontent.com/34094836/110458355-f4e07800-80cb-11eb-91d0-789bb3677101.png)

So, Id say lets try 90% or even lower?

Its interesting to see, that not the systems maximum possible Heapspace Size is the Limit here, but what LibO allocates at first hand. I think LibO increases XmX when there is demand, but in this case it might not be fast enough. Also the 95% barrier might have been to close to the limit. Seems like LT ran out of RAM just before it got a chance to switch to old API and reduce RAM need. That's why I think reducing the threshold to 90% or lower could help.

**Comment by FredKruse** [comment] 2021-03-10 09:40
The heap limit is set to 90%. Please test the 5.3-snapshot tomorrow.

**Comment by ColeBantam** [comment] 2021-03-17 10:27
Sorry for late reply, had some very busy days ...

Here are my impressions from snapshot 20210316:

- First test (32Bit, Huge Doc): Not working at all. No Spell-Check-Window appears, no blue lines on Canvas. Zero CPU time and LibO not responding in the end.

- Second test (same as above but without touching the "rescan document" button): Do have CPU-Time now. Blue lines after some time, and the first exception (the memory warning came after the exception).
![next-exeption18](https://user-images.githubusercontent.com/34094836/111452129-7a8aa600-8712-11eb-90a6-ca62f2c48f98.png)

- Third test (empty document): "Rescan Document" is working.

- 4th test (realworld doc): "Rescan Document" seems to be doing something, at least LibO uses CPU Time. Then empty message and no more CPU-time. LibO can be closed, the empty message is stuck (tried closing the message first of course). Had to kill soffice.bin to get rid of the empty message.
![next-exeption19](https://user-images.githubusercontent.com/34094836/111452250-9d1cbf00-8712-11eb-97aa-391de6a00463.png)

- 5th test: (realworld document): No "Rescan Document" this time, instead just typing in a new paragraph with grammar mistakes. Typing is extremely slow but working. Blue lines after a few seconds. Then the memory-warnig-message. After clicking OK in the message, LibO feels good. Memory is Max247M,Total247M,Free46M. On saving the document LibO crashed, but that might be a LibO fault, I tested with LibO 7.1.0.2. After that crash, the LT-Icons and Menu-Entry was gone, even though LT was still in Extension-Manager. After reinstalling LT the icons were back.

- 6th test (realworld doc): Opening Doc and clicking "Rescan Document" (like Test 4). This time immediate exception - OutOfMemory again. Even though "About" says 91MB free, but the "about" was requested after the exception.
![next-exeption20](https://user-images.githubusercontent.com/34094836/111452618-fdabfc00-8712-11eb-8cb4-eb7833b4a491.png)

Conclusion:
The last Snapshot I tested felt better overall. Not sure if the memory error in the last exception still is because of the 90% or if it was something else. I hope the report helps somehow in stabilizing LT...

**Comment by FredKruse** [comment] 2021-03-23 07:46
Now, a heap test is implemented, when running the LT spell and grammar check dialog. Please test the new snapshot.

**Comment by ColeBantam** [comment] 2021-03-29 10:43
Thanks for implementing that :)

Sadly, the current snapshot is even worse compared ti the previous ones :/ Here are my results:

------------

1st Test: Opening huge doc and press "Recheck document" -> nothing happened, so tried to open "About"-Window wich came up empty. Had to kill soffice.bin to close the window.

2nd Test: Opening huge doc and just wait -> No Switching to paragraph-mode message appeared. Clicked the Settings-Icon to check them, but that window also doesn't come up. Seems like LT ist stuck somehow, even though the blue lines are there. Ah, ok, LibO-Window is frozen too now. Again, had to kill soffice.bin.

Conclusion after first two tests: Huge Doc (800k words) seems to be impossible to edit with LT Snapshot 202110328. Btw, Clipboard also not working anymore now.

3rd Test: Medium Doc (400k Words): Opening doc, wait a few minutes -> no message. Tried to open Settings -> no response. At least I didn't had to kill soffice.bin this time.

4th Test: Opening empty doc -> clicking settings finally brings the settings dialogue up. Had the spellcheck set to "only paragraph", so its clear why no messages regarding switching to paragraph mode came up before. Nevertheless the settings dialogue or the "check al" window should have been shown before, so seems like there is a new error in this build? --> Wow, not it really gets strange! I did change the setting to Option 3 ("Kapitel prüfen") and a memory exception came up. Remember, this was an EMPTY document!. No need to kill soffice.bin.

![next-exeption21](https://user-images.githubusercontent.com/34094836/112825625-4ad18b80-908c-11eb-8f05-b798343d9ade.png)

5th Test: Opening "Huge doc" again, this time with Option 3 enabled -> even after more then 10 minutes, no memory dialogue. "About"-Window not coming up again too.

6th Test: Empty Doc -> all 4 LT-Icons work as expected.

7th Test: 100k word document -> Opened the doc and clicked the "Recheck Document"-Button -> no response. LibO still accessible this time, but no LT-Dialogue.

------------

Stopped testing here, as its obviously impossible to test the changes in the Spellcheck-Window-Code.

**Comment by FredKruse** [comment] 2021-04-02 18:50
These results are very strange. I bought a 32-Bit Windows-Version and will do some test at the end of next week.

**Comment by ColeBantam** [comment] 2021-04-03 14:26
Hi Fred,

Thanks again for putting so much effort into this :) You should be on the first row of the LT Team on the LT Website (instead I didn't find you there at all?! - https://languagetool.org/de/about)

So, if you want to match my System for testing, you should install 64Bit Windows 10. Not sure how common 32Bit Windows still is theses days, as most PCs have 4GB of RAM or more. I have done most of my tests on 64Bit Windows but 32Bit LibO, as this is the setup thats most used at my customers. Fortunately the Windows license is not connected to one bittness, so you can install 64Bit Version even if you bought a licence that comes with a 32Bit DVD. I hope you haven't bought a Windows 10 Licence with DVD though, because you would have spent a lot more money than necessary then :/

Does it make sense to test a more recent snapshot or are they basically the same then 202110328 in this regard?

**Comment by FredKruse** [comment] 2021-11-18 19:13
The issue is solved. I close it.

**Closed by FredKruse** 2021-11-18 19:13 UTC
Labels: office-integration
