### ISSUE TITLE
LibreOffice LanguageTool Extension No Grammar Checking

### ISSUE THREAD

**Issue by promethial** [languagetool-org/languagetool#676] opened 2017-02-26 22:58 UTC
Hello,

Appears the LibreOffice LanguageTool extension is only doing spell checking. No grammar checking is done. Additionally, attempted the steps in the issue checklist (https://languagetool.org/issues/) without success.

I used the below test input from the LanguageTool website.

## String Used:

> Paste your own text here and click the 'Check Text' button. Click the colored phrases for details on potential errors. or use this text too see an few of of the problems that LanguageTool can detecd. What do you thinks of grammar checkers? Please not that they are not perfect. Style issues get a blue marker: It's 5 P.M. in the afternoon.

## System Details:

1. LibreOffice Version: 5.3.0.3
2. LanguageTool: 3.6
3. Operating System: OS X
4. Java Version: 1.8.0_05

Thanks!

**Comment by danielnaber** [comment] 2017-02-27 08:10
Have you checked https://languagetool.org/issues/?

**Comment by promethial** [comment] 2017-02-27 14:29
Yes, went through the debugging steps and used the test ODT document as well.

**Comment by TiagoSantos81** [comment] 2017-03-17 09:10
This may be a OS X only problem. Not reproducible in Windows 7 nor Linux Mint 18.1.

**Comment by danielnaber** [comment] 2017-06-01 18:53
Feel free to re-open if there's more information, for now I have to close it as I cannot reproduce it.

**Closed by danielnaber** 2017-06-01 18:53 UTC
Labels: office-integration
